### ISSUE TITLE
delete all auto-generated .scss.d.ts files at the start of each build

### ISSUE THREAD

**Issue by dkent600** [daostack/alchemy#1000]
.scss.d.ts files are not rebuilt if their date is newer than the date of the associated .scss file.  This can break a build after doing an `npm ci`.  

So the proposal is to delete all auto-generated .scss.d.ts files at the start of each build,

**Comment by jellegerbrandy** [comment]
how does it break the build?

**Comment by dkent600** [comment]
It can break the build if the former, un-rebuilt typings are missing types referenced in newer code.

**Comment by tibetsprague** [comment]
or we could go back to adding the files to the repo and not worry about this

**Comment by jellegerbrandy** [comment]
we also do not want to delete them before each build, as this slows down the building considerably.

**Comment by dkent600** [comment]
> his slows down the building considerably

Looking at `npm run start`, I am not detecting any delay at all, much less anything that would be a significant proportion of the total build time.  What are you seeing?

**Comment by jellegerbrandy** [comment]
I thought I saw a significant dely, but perhaps it was an optical illusion.
