### ISSUE TITLE
Metamask refreshes the entire app on network change

### ISSUE THREAD

**Issue by dkent600** [daostack/alchemy#1006]
Don't refresh the entire app on network change with MetaMask.

According to [this](https://github.com/MetaMask/metamask-extension/issues/3599), one can disable this behavior as follows:

```
window.ethereum.autoRefreshOnNetworkChange = false
```

**Comment by tibetsprague** [comment]
I dont really understand why we care so much about not refreshing the app

**Comment by dkent600** [comment]
To do this best, need to address this at the same time:  https://github.com/daostack/alchemy/issues/1007
