### ISSUE TITLE
problems with webconnect

### ISSUE THREAD

**Issue by jellegerbrandy** [daostack/alchemy#1009]
- Scenario: go to staging app with MM connected to main. Click on "use metamask", it will try to connect to the account, grant it permission. It fails with a "wrong network" error.  We can fail before trying to connect. (`window.ethereum.networkVersion` is already available)
.
- Scenario: log in with MM; log out from MM using the MM dialog (i.e. lock MM).  Now the "please log in" text re0appears, but the button is not responsive.

- The popup window where you choose the wallet provider throws this React error: 

```app.bundle-53850ffc.js:93 Warning: Each child in a list should have a unique "key" prop.

Check the render method of `t`. See https://fb.me/react-warning-keys for more information.
    in Unknown (created by t)
    in t
```

- logging into portis fails silently, the console logs: 

```main.8a82a8196249310206f1.js:1 Uncaught (in promise) Error: Unauthorized action
    at new t (main.8a82a8196249310206f1.js:1)
    at main.8a82a8196249310206f1.js:1
    at main.8a82a8196249310206f1.js:1
    at Object.next (main.8a82a8196249310206f1.js:1)
    at i (main.8a82a8196249310206f1.js:1)
```
I have a portis account and I can log in on wallet.portis.io without problems

- Clicking on fortmatic fails silently. To be fair, also the https://nearprotocol.github.io/fortmatic-demo/ demo gives me the exact same error, so the problem is probably theirs: 

```main.af1c348b.chunk.js:1 Uncaught (in promise) DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
    at t.<anonymous> (https://x2.fortmatic.com/static/js/main.af1c348b.chunk.js:1:475322)
    at _ (https://x2.fortmatic.com/static/js/2.0f72562c.chunk.js:1:474825)
    at Generator._invoke (https://x2.fortmatic.com/static/js/2.0f72562c.chunk.js:1:474613)
    at Generator.t.<computed> [as next] (https://x2.fortmatic.com/static/js/2.0f72562c.chunk.js:1:475004)
    at n (https://x2.fortmatic.com/static/js/2.0f72562c.chunk.js:1:71341)
    at u (https://x2.fortmatic.com/static/js/2.0f72562c.chunk.js:1:71543)
    at https://x2.fortmatic.com/static/js/2.0f72562c.chunk.js:1:71602
    at new Promise (<anonymous>)
    at t.<anonymous> (https://x2.fortmatic.com/static/js/2.0f72562c.chunk.js:1:71484)
    at t.<anonymous> (https://x2.fortmatic.com/static/js/main.af1c348b.chunk.js:1:479843)
``` 
-

**Comment by dkent600** [comment]
> Scenario: go to staging app with MM connected to main. Click on "use metamask", it will try to connect to the account, grant it permission. It fails with a "wrong network" error. We can fail before trying to connect. (window.ethereum.networkVersion is already available).

If I understand what your saying, this is a dup:  https://github.com/daostack/alchemy/issues/1007

**Comment by dkent600** [comment]
> log in with MM; log out from MM using the MM dialog (i.e. lock MM). Now the "please log in" text re0appears, but the button is not responsive.

I"m sorry, I don't understand this.

What is the precise starting point?

"log in with MM"  Exactly how?  Using the MM UI or our UI?

No idea how to do "log out from MM using the MM dialog (i.e. lock MM)".  

"Click on "use metamask"  Where?  I'm not aware of such a UI control.

Can you please give a more precise steps?  Thanks!

**Comment by dkent600** [comment]
" The popup window where you choose the wallet provider throws this React error"

Yes, as described in the PR, this is known and I have [reported it to Web3Connect, here](https://github.com/web3connect/web3connect/issues/47).

I am not aware that it has any effect on the functionality here so I suggest to ignore.  Though an alternative is to fix it in our fork.

Note again I have seen and reported the same error in Alchemy:

https://github.com/daostack/alchemy/issues/992
https://github.com/daostack/alchemy/issues/970

**Comment by dkent600** [comment]
> logging into portis fails silently, the console logs:

I can't reproduce this.  Perhaps need more precise steps.

**Comment by leviadam** [comment]
> > log in with MM; log out from MM using the MM dialog (i.e. lock MM). Now the "please log in" text re0appears, but the button is not responsive.
> 
> I"m sorry, I don't understand this.
> 
> What is the precise starting point?
> 
> "log in with MM" Exactly how? Using the MM UI or our UI?
> 
> No idea how to do "log out from MM using the MM dialog (i.e. lock MM)".
> 
> "Click on "use metamask" Where? I'm not aware of such a UI control.
> 
> Can you please give a more precise steps? Thanks!

@dkent600 
I just reproduced this.
Say you start clean, namely with nothing.
You click login, select MM from the web3connect options, and you are all set.

Now say you click log-out, not on our UI, but on MM itself. 
The app will change the button, back to "please log in!" but it will be disabled.

**Comment by dkent600** [comment]
> Clicking on fortmatic fails silently

I can't reproduce this either.   No problem logging in to Fortmatic.

**Comment by dkent600** [comment]
@leviadam 

> Now say you click log-out, not on our UI, but on MM itself.

Sorry I've never seen this Log-out button in MM.  Where is it?

**Comment by dkent600** [comment]
@leviadam   I had never seen this Logout button before even though I've looked!!!  Just found it.

**Comment by dkent600** [comment]
I believe everything has been covered here.  Note https://github.com/daostack/alchemy/issues/1026.
