### ISSUE TITLE
let's write "connect to wallet" instead of "log in"

### ISSUE THREAD

**Issue by jellegerbrandy** [daostack/alchemy#1010]
- "Log in" ->> "Connect your wallet"
- "Log out" -> "Disconnect your wallet"
-"Log out" now also resets the account information (i.e. usage becomes "anonymous"). Is that what we want?

**Comment by leviadam** [comment]
I agree that log in and out are not very good.
How about "Connect wallet"? To make it shorter? @jellegerbrandy @A-Zak

**Comment by dkent600** [comment]
> -"Log out" now also resets the account information (i.e. usage becomes "anonymous"). Is that what we want?

This should be a separate ticket.  @jellegerbrandy
