### ISSUE TITLE
Redemption button not showing up

### ISSUE THREAD

**Issue by arsena21** [daostack/alchemy#1016]
Hi there, 

It looks like we are having DAO specific redemption issues. 

I recently passed proposals in DAOfund, and none of them have a "Redeem" button: http://prntscr.com/opa24a

Same thing with PravduhDAO: http://prntscr.com/opa1wq

This is pretty urgent as we are trying to get partners loaded up (at least for DAOfund)... thanks

**Comment by dkent600** [comment]
This appears to be fixed.  @arsena21 let us know if not, thanks.
