### ISSUE TITLE
Hovering over reputation should show the reputation count, not the DAO's total

### ISSUE THREAD

**Issue by tibetsprague** [daostack/alchemy#1019]
Commit 3ae64cd6bae1bbc6fc0fd282fb28091baedf6072 changed this behavior. Why? It's quite confusing to me to mouse over 1.19% reputation and see the total DAO rep not the total rep count that equals that 1.19% reputation.

**Comment by jellegerbrandy** [comment]
follow up here: https://daostack.tpondemand.com/RestUI/Board.aspx#page=board/4789434231796866533&appConfig=eyJhY2lkIjoiMEFGRDcyNjIyOTgzRjFFMkMwRjIwMDBCNzA0QjRGMzQifQ==&boardPopup=bug/1421/silent
