### ISSUE TITLE
Fortmatic and Portis fail silently when third-party cookies are disabled

### ISSUE THREAD

**Issue by dkent600** [daostack/alchemy#1026]
From Jelle: Fortmatic and Portis fail silently when third-party cookies are disabled.  We should consider detecting this condition and report to the user when it happens.

**Comment by jellegerbrandy** [comment]
follow up here: https://daostack.tpondemand.com/RestUI/Board.aspx#page=board/4789434231796866533&appConfig=eyJhY2lkIjoiMEFGRDcyNjIyOTgzRjFFMkMwRjIwMDBCNzA0QjRGMzQifQ==&boardPopup=bug/1429/silent
