### ISSUE TITLE
Redemption Error Scheme Registrar CuraDAO

### ISSUE THREAD

**Issue by LuukWeber** [daostack/alchemy#1027]
Hi,

I'm trying to redeem a Scheme Registrar proposal from the CuraDAO but am getting an error.

I was able to redeem one of the Contribution Reward proposals form the CuraDAO yesterday, so I'm not sure what happened here. Thanks for the help! 

Screenshot of error + console: 
![image](https://user-images.githubusercontent.com/51293333/62704638-22df7100-b9ec-11e9-9ab8-cdf91803e73b.png)

**Comment by A-Zak** [comment]
[This proposal](https://alchemy.daostack.io/dao/0xe8e1d0f1783b22ff409deb14fa5acc9cce2a3d15/proposal/0x451c5374d016653b91cf5e082a98ba05382723653248f3cb6bae6b1cc9cf19c7) also seems to not be redeemable...
Tried to redeem it through [etherscan on this contract](https://etherscan.io/address/0x6646d0a32d6b9c1d1a7389a6b8da7e5fd780f316#contracts)
and I get this error:
![image](https://user-images.githubusercontent.com/302774/62712281-2fbb8f00-ba03-11e9-8d3b-e0f065ecbc9a.png)

**Comment by jellegerbrandy** [comment]
Alex's proposal is the proposal with id 0x451c5374d016653b91cf5e082a98ba05382723653248f3cb6bae6b1cc9cf19c7

you can see the subgraph info ere: https://subgraph.daostack.io/subgraphs/name/v24/graphql?query=%7B%20proposals%20(where%3A%7B%20id%3A%220x451c5374d016653b91cf5e082a98ba05382723653248f3cb6bae6b1cc9cf19c7%22%0A%20%7D)%20%7B%0A%0A%20%20votingMachine%0A%20%20contributionReward%20%7B%0A%20%20%20%20id%0A%20%20%20%20contract%0A%0A%20%20%7D%20%20%0A%0A%7D%0A%7D

The contributionReward contract is this one: 0x08cc7bba91b849156e9c44ded51896b38400f55b

So Alex, you've been trying on the wrong contributionReward contract, it seems. Where did you get that from?

**Comment by dkent600** [comment]
@jellegerbrandy   This is a proposal on SchemeRegistrar, whose address is: 
 0xf050f3c6772ff35eb174a6900833243fccd0261f.

**Comment by dkent600** [comment]
I find that I can't redeem on that proposal either (using Alchemy)

**Comment by dkent600** [comment]
@A-Zak  The proposal you linked to above is not even in the correct DAO.

**Comment by dkent600** [comment]
@A-Zak   @jellegerbrandy   This is the correct proposal:

https://alchemy.daostack.io/dao/0x0b93ba560283350d4216f29dc57e15df38d0eace/proposal/0x01d2b5d939e9f585a6c7a422f44b2d11ae6050f574267d46a4dd638c22ede7af

**Comment by jellegerbrandy** [comment]
ok, so ignore alex's remarks here :smiling_imp: 

I have a hunch that the problem is with non-contribution reward proposals. We have another report here: https://github.com/daostack/alchemy/issues/1018

I'll look into this.
