### ISSUE TITLE
redeem transaction goes through but  card remains in redemption list

### ISSUE THREAD

**Issue by jellegerbrandy** [daostack/alchemy#1028]
https://cdn.discordapp.com/attachments/534675585440677890/609186600718434315/455935771_419335.jpg
![image](https://user-images.githubusercontent.com/1306173/62763994-27a83180-ba8d-11e9-8ea7-43897ef8ccc9.png)

https://etherscan.io/tx/0x801c836dca46eac66ad6b6d198acc1496af361cabf6511e94fc43b8dbeaff024

**Comment by jellegerbrandy** [comment]
This is not a bug. There are 300 GEN protocol rewards pending, which the DAO can not send, because it has no funds

**Comment by dkent600** [comment]
Do we report this fact to the user so they can understand what is happening?

**Comment by tibetsprague** [comment]
we used to....
