### ISSUE TITLE
Cannot redeem proposal from the dxDAO

### ISSUE THREAD

**Issue by pimato** [daostack/alchemy#1032]
I am trying to redeem the dxDAO proposal: 

https://alchemy.daostack.io/dao/0x519b70055af55a007110b4ff99b0ea33071c720a/redemptions/

but alchemy says:
<img width="283" alt="Screenshot 2019-08-10 at 21 07 44" src="https://user-images.githubusercontent.com/5337809/62825883-ea3dc400-bbb2-11e9-9575-cb569f5d8b22.png">

based on closed issues, there seems to be a lot of problems with redeeming proposals. How can we fix that?

**Comment by pimato** [comment]
seems like it is the same issue as: https://github.com/daostack/alchemy/issues/1018

**Comment by jellegerbrandy** [comment]
We have just deployed what we think is a fix. Please open a new issue if the problem persists. 
Thanks for the bug report!
