### ISSUE TITLE
Voting buttons are visible on expired proposal

### ISSUE THREAD

**Issue by dkent600** [daostack/alchemy#1033]
This is in dev, accessing the proposal details from the History list:

![image](https://user-images.githubusercontent.com/1821666/62834595-bf885580-bc1c-11e9-8799-09da56c2a235.png)

Seems like the For and Against buttons should not be visible unless it is possible to vote.

**Comment by jellegerbrandy** [comment]
follow up in target process: https://daostack.tpondemand.com/RestUI/Board.aspx#page=board/4789434231796866533&appConfig=eyJhY2lkIjoiMEFGRDcyNjIyOTgzRjFFMkMwRjIwMDBCNzA0QjRGMzQifQ==&boardPopup=bug/1440/silent
