### ISSUE TITLE
Empty whitespace at bottom of voting context menu

### ISSUE THREAD

**Issue by dkent600** [daostack/alchemy#1034]
I'm seeing this on staging:

![image](https://user-images.githubusercontent.com/1821666/62834928-b305fc00-bc20-11e9-8279-ca89158f535c.png)

**Comment by jellegerbrandy** [comment]
follow up here: https://daostack.tpondemand.com/RestUI/Board.aspx#page=board/4789434231796866533&appConfig=eyJhY2lkIjoiMEFGRDcyNjIyOTgzRjFFMkMwRjIwMDBCNzA0QjRGMzQifQ==&boardPopup=bug/1441/silent
