### ISSUE TITLE
Popups on mobile devices are clipped off viewport

### ISSUE THREAD

**Issue by dkent600** [daostack/alchemy#1041]
Should be vertically centered.

![image](https://user-images.githubusercontent.com/1821666/62936370-a0620300-bd97-11e9-929b-f6043627b462.png)

**Comment by dkent600** [comment]
Same thing happens with the voting popup:

![image](https://user-images.githubusercontent.com/1821666/63093933-f02a0100-bf34-11e9-8c67-d003b4d22171.png)

**Comment by dkent600** [comment]
in fact, every single popup in the app has the same behavior

**Comment by jellegerbrandy** [comment]
folow up here: https://daostack.tpondemand.com/RestUI/Board.aspx#page=board/4789434231796866533&appConfig=eyJhY2lkIjoiMEFGRDcyNjIyOTgzRjFFMkMwRjIwMDBCNzA0QjRGMzQifQ==&boardPopup=bug/1448/silent
