### ISSUE TITLE
Alchemy does not load when going directly to a proposal

### ISSUE THREAD

**Issue by stratisdaostack** [daostack/alchemy#1050]
Clicking on this [link](https://alchemy.daostack.io/dao/0x294f999356ed03347c7a23bcbcf8d33fa41dc830/proposal/0xf53d825881795b16360765105ff949468415942a6fc2bd2f55e0880be03fd741) displayed this error:
<img width="1440" alt="Screenshot 2019-08-15 at 13 07 39" src="https://user-images.githubusercontent.com/41568024/63088571-0ac4a000-bf5e-11e9-9d71-36223700158c.png">

Normal refreshing didn't work but cache-resetting-refreshing worked :)

**Comment by dkent600** [comment]
The link given above works fine for me.  I'm not sure how we can reproduce this.

**Comment by tibetsprague** [comment]
I cant replicate right now, but I have seen this...

**Comment by jellegerbrandy** [comment]
I've seen this too, but have not been able to reproduce this reliably :-/
