### ISSUE TITLE
History page crashes on mobile

### ISSUE THREAD

**Issue by dkent600** [daostack/alchemy#1053]
STEPS:

1. browse to Alchemy on iPhone iOS (the only one I tried).  I tried in both Safari and Chrome.
2. the Log In button in upper left should be visible.  Ignore it.
3. open a DAO
4. click on the Menu hamburger button
5. click on History

RESULT:
"Report Feedback"  TypeError: null is not an object (evaluating 't.toLowerCase')

**Comment by dkent600** [comment]
I am seeing the same error on non-mobile when I click on any proposal listed in the History page.

**Comment by jellegerbrandy** [comment]
following up in target process: https://daostack.tpondemand.com/RestUI/Board.aspx#page=settings/customFields&searchPopup=bug/1466

**Comment by dkent600** [comment]
@jellegerbrandy   The TP link above seems to be wrong
