### ISSUE TITLE
Notifications with long text should look better on mobile

### ISSUE THREAD

**Issue by dkent600** [daostack/alchemy#1054]
![image](https://user-images.githubusercontent.com/1821666/63095861-4baabd80-bf3a-11e9-8585-3a53d20554a6.png)

**Comment by jellegerbrandy** [comment]
follow up here: https://daostack.tpondemand.com/RestUI/Board.aspx#page=board/4789434231796866533&appConfig=eyJhY2lkIjoiMEFGRDcyNjIyOTgzRjFFMkMwRjIwMDBCNzA0QjRGMzQifQ==&boardPopup=bug/1467/silent
