### ISSUE TITLE
Request: History page should also show rewards requested

### ISSUE THREAD

**Issue by stratisdaostack** [daostack/alchemy#1059]

**Comment by dOrgJelli** [comment]
+1

**Comment by parrachia** [comment]
+1

**Comment by tibetsprague** [comment]
need a design for this, no easy obvious way to fit it in... ill think about it

**Comment by EzraWeller** [comment]
@dOrgJelli do you still think this is important?

**Comment by dOrgJelli** [comment]
I think so @EzraWeller, as seeing the amount of funds each proposal had been granted or denied is generally useful to understand the flow of funds within the DAO.

For example, checkout one of the "proposal summary" pages on Eyal's app: http://heroku.deepdao.world/DaoSummary

**Comment by roienatan** [comment]
Closing, History Page is deprecated.
