### ISSUE TITLE
Bug in redemptions page

### ISSUE THREAD

**Issue by stratisdaostack** [daostack/alchemy#1060]
I clicked this [link](https://alchemy.daostack.io/dao/0x66f1a21ae7c68bb8a87a912e8fa8fdadd17f8ef6/redemptions/) and got the following error: 
<img width="523" alt="Screenshot 2019-08-20 at 11 58 07" src="https://user-images.githubusercontent.com/41568024/63333335-f576b980-c341-11e9-9274-7df59581a3f2.png">

**Comment by stratisdaostack** [comment]
I also got the same error message when I clicked [here](https://alchemy.daostack.io/dao/0x66f1a21ae7c68bb8a87a912e8fa8fdadd17f8ef6/history/)

**Comment by dkent600** [comment]
This has been addressed here:  https://github.com/daostack/alchemy/pull/1056
