### ISSUE TITLE
scheme info tab : permission - add  "can mint/burn reputation" 

### ISSUE THREAD

**Issue by orenyodfat** [daostack/alchemy#1064]
it will be good to add "can mint or burn reputation" for any registered scheme permissions info.
which is currently the case by default.

**Comment by jellegerbrandy** [comment]
good point, will follow up in TP

**Comment by dkent600** [comment]
Hmmm, looking here I don't see such a permission:  https://github.com/daostack/arc/blob/2b8d465931294d2fdadfbe7f9045c53bd2cce651/contracts/controller/Controller.sol#L18

**Comment by orenyodfat** [comment]
can mint/burn reputation is a default permission for each registered scheme

**Comment by dkent600** [comment]
@orenyodfat  where is this permission referenced in any of our code?

**Comment by orenyodfat** [comment]
> @orenyodfat where is this permission referenced in any of our code? What are you suggesting Alchemy do about it? Display it _as if_ it were a real permission, always turned on, disabled in the GUI so it can't be altered?
https://github.com/daostack/arc/blob/2b8d465931294d2fdadfbe7f9045c53bd2cce651/contracts/controller/Controller.sol#L141 
and 
https://github.com/daostack/arc/blob/2b8d465931294d2fdadfbe7f9045c53bd2cce651/contracts/controller/Controller.sol#L83 

yes, display it  as if it were a real permission always turned on ,disabled in the GUI so it can't be altered.
as this is the current situation right now. and the user should be aware of that.
