### ISSUE TITLE
Looking into proposal details page hits a snag and the page fails to render

### ISSUE THREAD

**Issue by hemulin** [daostack/alchemy#1069]
DAO: 0xbe1a98d3452f6da6e0984589e545d4fc25af7526
Proposal: 0xd60fc846142e30c43435411091cbe02f387ca995baa975e4072616654a0b89b5

Reproduction link:
https://alchemy.daostack.io/dao/0xbe1a98d3452f6da6e0984589e545d4fc25af7526/proposal/0xd60fc846142e30c43435411091cbe02f387ca995baa975e4072616654a0b89b5

![Selection_001](https://user-images.githubusercontent.com/1885510/63389305-96e62580-c3ab-11e9-8c81-2cddedcf71f1.jpg)

Console log:
[alchemy.daostack.io-1566340600658.log](https://github.com/daostack/alchemy/files/3522877/alchemy.daostack.io-1566340600658.log)

Also seems unrelated but the `disqus` widget is a little off:
```
Uncaught TypeError: Cannot read property 'appendChild' of null
    at k (daostack-alchemy.disqus.com/embed.js:36)
    at Object.l [as isSerif] (daostack-alchemy.disqus.com/embed.js:36)
    at h.i.toJSON (daostack-alchemy.disqus.com/embed.js:36)
    at Object.c.loadEmbed [as _loadEmbed] (daostack-alchemy.disqus.com/embed.js:37)
    at daostack-alchemy.disqus.com/embed.js:38
```

**Comment by jellegerbrandy** [comment]
Hi @hemulin , thanks for your report. I cannot reproduce this issue - the page works fine for me. Can you recheck, and if so, re-open this issue with perhaps some more information (did you connect with metamask, for example?)
