### ISSUE TITLE
Can't send  transaction after changing account

### ISSUE THREAD

**Issue by dkent600** [daostack/alchemy#1070]
STEPS:

1. do a transaction using any MetaMask account
2. change the current account in MetaMask
3. try a transaction

RESULT:

Nothing happens except an error in the console:

> Error: WalletMiddleware - Invalid "from" address.

EXPECT:

What should happen is the 2nd transaction should just work, or if necessary, invoke InitializeArc, or issue any necessary MM prompts as needed.  The latter should happen at the time the user requests to make the tx.

**Comment by jellegerbrandy** [comment]
I just tried, this seems fixed.
