### ISSUE TITLE
Can not redeem DAO to DAO rep

### ISSUE THREAD

**Issue by arsena21** [daostack/alchemy#1078]
This is still not fixed. Here is an example:

I submitted this proposal to redeem (Genesis DAO redeems a proposal from DAOfund): https://alchemy.daostack.io/dao/0x294f999356ed03347c7a23bcbcf8d33fa41dc830/proposal/0x383f6b963bded059dabcfaa82552ab45914301006417805a0db166f884cf015e

This is the original proposal in DAOfund giving rep to Genesis DAO: https://alchemy.daostack.io/dao/0xe8e1d0f1783b22ff409deb14fa5acc9cce2a3d15/proposal/0x8d9963c78692c9aacd99a67c16510872a769f37f30da6601237138342028b723

There is no reputation given to Genesis DAO.

_Originally posted by @arsena21 in https://github.com/daostack/alchemy/issues/1018#issuecomment-523644398_

**Comment by dkent600** [comment]
Thanks @arsena21.  We are investigating.

**Comment by dkent600** [comment]
Following up here:  https://daostack.tpondemand.com/entity/1555-can-not-redeem-dao-to-dao

**Comment by dkent600** [comment]
My mistake.  I'm going to close this as a dup of #1018.
