### ISSUE TITLE
Proposal forms don't fit vertically on 100% scaled screen

### ISSUE THREAD

**Issue by dkent600** [daostack/alchemy#1084]
On a desktop platform, have to zoom the browser out to 80% to fit.  This should not be necessary.  Should either fit by default or there should appear scrollbars in the popup.

![image](https://user-images.githubusercontent.com/1821666/63636700-af22a280-c640-11e9-829d-c16adae72f6f.png)

**Comment by dkent600** [comment]
Same happens to ENS proposals:

![image](https://user-images.githubusercontent.com/1821666/66714729-69ed3800-ed88-11e9-93bb-ca0c42f1bcbe.png)

**Comment by dkent600** [comment]
See Target Process:  https://daostack.tpondemand.com/RestUI/Board.aspx#page=board/4789434231796866533&appConfig=eyJhY2lkIjoiMEFGRDcyNjIyOTgzRjFFMkMwRjIwMDBCNzA0QjRGMzQifQ==&boardPopup=bug/1742/silent

**Comment by jellegerbrandy** [comment]
seems fixed to me

**Comment by dkent600** [comment]
It is not fixed.  I was just seeing this yesterday.  It may depend on one's screen size.  I have the browser maximized on the following screen dimensions:

![image](https://user-images.githubusercontent.com/1821666/66749541-1c400080-ee58-11e9-9a20-3f027ce924dd.png)

**Comment by jellegerbrandy** [comment]
:+1:  I don't have enough pixels to reproduce this :-D

**Comment by dkent600** [comment]
I don't think it is pixel that matter, I think it is the aspect ratio.

**Comment by dkent600** [comment]
As far as I can tell, this is fixed.  @jellegerbrandy
