### ISSUE TITLE
Feature: embed videos in a new proposal

### ISSUE THREAD

**Issue by stratisdaostack** [daostack/alchemy#1085]
Inspired by [this proposal](https://alchemy.daostack.io/dao/0x294f999356ed03347c7a23bcbcf8d33fa41dc830/proposal/0x62eb5051373945d2a65d69a32b1f8f5403657cd42a336f415c4776eb33b77fe9)

How cool would it be if he could've embedded the video directly in the proposal page?

Next level: integrate with something like [Loom](https://www.loom.com/) and shoot your video from inside Alchemy.

**Comment by jellegerbrandy** [comment]
This is indeed a cool idea. It is not likely that the Alchemy dev team will pick this up for the LTS version, though. But  a PR from any dev implementing this would be welcome (for the embedding part, not for the "shoot yr vid from inside alchemy" part :-) )

**Comment by tibetsprague** [comment]
pretty easy to implement embedding a youtube widget when we see a youtube link, and same with vimeo. that sound good for now?

**Comment by EzraWeller** [comment]
A couple issues:

1. The youtube video appears as a short rectangle here. It should be more square if possible.
<img width="1323" alt="Rectangle video" src="https://user-images.githubusercontent.com/5414803/80143538-f4ee8c80-857a-11ea-9acb-5cf55777c7bc.png">

2. The page (or component) is reloading when any notification pops up -- this stops the video and feels jarring.

3. We need some indication that videos can be embedded in the proposal form. It looks like some form UI library is being used in the form, so I'm not sure what options we have, but even just a short note under the text box that says `Paste a youtube or vimeo link to embed the video` would probably be fine.

Haven't tested Vimeo, but I imagine similar issues are available.

**Comment by dkent600** [comment]
@EzraWeller Can you please give the url of the youtube video you used as an example?

**Comment by dkent600** [comment]
@EzraWeller I'm not sure how to deal with this.  It is stupid React stuff.  There is something I can try, but no guarantees it'll work.

**Comment by dkent600** [comment]
> We need some indication that videos can be embedded in the proposal form.

This should have been part of the spec.  But sure, I can add that text under the description textbox.

**Comment by dkent600** [comment]
As far as that notification goes, I have always thought it was weird having been implemented as a React component.  I wouldn't mind refactoring it to appear above all the React stuff, independent of it. Then there would be no issues with stopping the video, and many components would then cease to rerender whenever the notification pops up.
