### ISSUE TITLE
Pre-boosting doesn't work?

### ISSUE THREAD

**Issue by stratisdaostack** [daostack/alchemy#1101]
I pre-boosted a proposal, tx went through and nothing happened.

TX: https://etherscan.io/tx/0xae898b559708eb217fdb74bd385d751fc641c24fb8a9c1a02c47e02b270e97ff

Proposal: https://alchemy.daostack.io/dao/0x294f999356ed03347c7a23bcbcf8d33fa41dc830/scheme/0x28c5b9efd5bdec2c69c613d2df4b5e1b92e44a2d3c2f5092fb45187570029009

**Comment by dkent600** [comment]
If there is a tx, then _something_ must have happened.  Any messages in the console?  Did you try refreshing the screen to see if the GUI changes?

**Comment by stratisdaostack** [comment]
Yes I cache-refreshed multiple times and it's also been many hours but
nothing has changed.

Unfortunately I didn't check the console at the time of the tx

**Comment by jellegerbrandy** [comment]
Hi stratis :-)
The transactio you posted is a redemption (I think), not a boosing tx. Also, you did not link to a specific proposal, so it is hard to check. I'm closing this, plz re-open with more specific info if you find this unjust :-)
