### ISSUE TITLE
Numbers less than 1000 should not be displayed as "0.51k"

### ISSUE THREAD

**Issue by pat-daostack** [daostack/alchemy#1103]
It is not proper form, nor good UX, to list numbers as decimal points of a higher power.

Something like "0.51k" should be properly displayed as "510" until it is higher than 1000.

Consequently in a proposal like so: https://alchemy.daostack.io/dao/0x294f999356ed03347c7a23bcbcf8d33fa41dc830/proposal/0xf53d825881795b16360765105ff949468415942a6fc2bd2f55e0880be03fd741 you should not have "0.1M GEN," but "10k GEN"

**Comment by dkent600** [comment]
This has already been addressed [here](https://github.com/daostack/alchemy/pull/1097)

**Comment by pat-daostack** [comment]
What about the 0.1M issue? Is that also resolved?

**Comment by dkent600** [comment]
I think you meant "0.01M" on that proposal page.

**Comment by dkent600** [comment]
@pat-daostack   Yes, just confirmed, it is all fixed.
