### ISSUE TITLE
How to deploy a new version of Alchemy

### ISSUE THREAD

**Issue by shivgupt** [daostack/alchemy#1105]
A lot of devs while playing around with DAOs want to deploy their DAO and start interacting with it without waiting for the manual process of getting their DAOs whitelisted, specially on testnet.

It would be nice to have a proper documentation on how to deploy your own version of Alchemy for both testnet and mainnet.

**Comment by jellegerbrandy** [comment]
This is definitely true, but it would help to be more specific about what you mean by "how to deploy your own version of alchemy". 

The most straightforward way is propably to "just" run the docekr-compose file as in here: https://github.com/daostack/alchemy/blob/dev/docs/docker.md#if-you-just-want-to-see-it-running and add some info about how to configure system variables. 

I.e. something like?

- install all the required software
- edit the docker-compose file and set the following sys variables to connect to main/test/local
- [not sure if the subgraph source can be also set with sys vars, probably not]
- run the docker-compose file and to to http://127.0.0.1:3000

**Comment by jellegerbrandy** [comment]
@shivgupt I'm closing this :-)
