### ISSUE TITLE
GEN amounts still being displayed incorrectly

### ISSUE THREAD

**Issue by pat-daostack** [daostack/alchemy#1106]
Instead of "500 GEN," DAOs are showing ".5k GEN"

This is improper form -- decimals should not be used until a higher order has been reached, e.g. 1200 GEN should display as "1.2k GEN" but 120 GEN should NOT display as ".12k" GEN.

**Comment by dkent600** [comment]
Dup of https://github.com/daostack/alchemy/issues/1103

@pat-daostack The fix for this has not yet been released.

@jellegerbrandy Maybe we shouldn't close tickets until they have been released?
