### ISSUE TITLE
Bug: Closing Transaction Toast Causes Multiple Genesis DAO Tiles

### ISSUE THREAD

**Issue by dOrgJelli** [daostack/alchemy#1107]
Repro:
- Cause a toast notification to show up by sending a transaction within Alchemy (vote, stake, etc).
- Go to the home page of Alchemy where you can see all DAOs.
- Close the toast.
- See a duplicate Genesis DAO tile appear. This happens every time you close a toast (see images below).

![Screenshot from 2019-09-08 14-17-33](https://user-images.githubusercontent.com/5522128/64492616-c28a5c00-d243-11e9-9177-33ff3d1b3d39.png)
![Screenshot from 2019-09-08 14-17-47](https://user-images.githubusercontent.com/5522128/64492618-c5854c80-d243-11e9-8ea9-38c89e955809.png)
![Screenshot from 2019-09-08 14-18-00](https://user-images.githubusercontent.com/5522128/64492619-c74f1000-d243-11e9-878c-51ac640492a2.png)

**Comment by dkent600** [comment]
Those notifications are also showing up in an odd position on the page.
