### ISSUE TITLE
Incorrect call data of dxDAO proposal on Rinkeby

### ISSUE THREAD

**Issue by Procrat** [daostack/alchemy#1122]
When you go the redemptions page of dxDAO (/dao/0x1eb3bcae24d42fde2f90e91d26313ac3946c4764/redemptions/) while logged in as the Ganache 0 account in the staging environment with Rinkeby, an error is thrown: "Error: No action matching these callData could be found".

I couldn't find a way to reproduce this locally, but I nevertheless reconstructed a stack trace.
```
Error: No action matching these callData could be found
    at genericSchemeInfo.decodeCallData (genericSchemeRegistry/index.ts:180)
    at ProposalSummaryDutchX.render (components/Proposal/ProposalSummary/ProposalSummaryDutchX.tsx:21)
    at ProposalSummaryKnownGenericScheme.render (components/Proposal/ProposalSummary/ProposalSummary/ProposalSummaryKnownGenericScheme.tsx:28)
    at ProposalSummary.render (components/Proposal/ProposalSummary/ProposalSummary/ProposalSummary.tsx:40)
```

The error seems to be triggered by a particular dxDAO proposal with id `0x88827921faba033fb7c2daeb23f4326db324c8772a0324e928de8c4573a173bb`. [Here](https://rinkeby.subgraph.daostack.io/subgraphs/name/v26/graphql?query=%7B%0A%20%20proposal(id%3A%20%220x88827921faba033fb7c2daeb23f4326db324c8772a0324e928de8c4573a173bb%22)%20%7B%0A%20%20%20%20id%0A%20%20%20%20accountsWithUnclaimedRewards%0A%20%20%20%20boostedAt%0A%20%20%20%20confidenceThreshold%0A%20%20%20%20contributionReward%20%7B%0A%20%20%20%20%20%20id%0A%20%20%20%20%20%20beneficiary%0A%20%20%20%20%20%20ethReward%0A%20%20%20%20%20%20externalToken%0A%20%20%20%20%20%20externalTokenReward%0A%20%20%20%20%20%20externalToken%0A%20%20%20%20%20%20nativeTokenReward%0A%20%20%20%20%20%20periods%0A%20%20%20%20%20%20periodLength%0A%20%20%20%20%20%20reputationReward%0A%20%20%20%20%20%20alreadyRedeemedReputationPeriods%0A%20%20%20%20%20%20alreadyRedeemedExternalTokenPeriods%0A%20%20%20%20%20%20alreadyRedeemedNativeTokenPeriods%0A%20%20%20%20%20%20alreadyRedeemedEthPeriods%0A%20%20%20%20%7D%0A%20%20%20%20createdAt%0A%20%20%20%20dao%20%7B%0A%20%20%20%20%20%20id%0A%20%20%20%20%20%20schemes%20%7B%0A%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20address%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%20%20description%0A%20%20%20%20descriptionHash%0A%20%20%20%20executedAt%0A%20%20%20%20executionState%0A%20%20%20%20expiresInQueueAt%0A%20%20%20%20genericScheme%20%7B%0A%20%20%20%20%20%20id%0A%20%20%20%20%20%20contractToCall%0A%20%20%20%20%20%20callData%0A%20%20%20%20%20%20executed%0A%20%20%20%20%20%20returnValue%0A%20%20%20%20%7D%0A%20%20%20%20genesisProtocolParams%20%7B%0A%20%20%20%20%20%20activationTime%0A%20%20%20%20%20%20boostedVotePeriodLimit%0A%20%20%20%20%20%20daoBountyConst%0A%20%20%20%20%20%20limitExponentValue%0A%20%20%20%20%20%20minimumDaoBounty%0A%20%20%20%20%20%20preBoostedVotePeriodLimit%0A%20%20%20%20%20%20proposingRepReward%0A%20%20%20%20%20%20queuedVotePeriodLimit%0A%20%20%20%20%20%20queuedVoteRequiredPercentage%0A%20%20%20%20%20%20quietEndingPeriod%0A%20%20%20%20%20%20thresholdConst%0A%20%20%20%20%20%20votersReputationLossRatio%0A%20%20%20%20%7D%0A%20%20%20%20gpRewards%20%7B%0A%20%20%20%20%20%20id%0A%20%20%20%20%7D%0A%20%20%20%20scheme%20%7B%0A%20%20%20%20%20%20id%0A%20%20%20%20%20%20paramsHash%0A%20%20%20%20%20%20name%0A%20%20%20%20%20%20address%0A%20%20%20%20%20%20canDelegateCall%0A%20%20%20%20%20%20canManageGlobalConstraints%0A%20%20%20%20%20%20canRegisterSchemes%0A%20%20%20%20%20%20canUpgradeController%0A%20%20%20%20%20%20name%0A%20%20%20%20%7D%0A%20%20%20%20gpQueue%20%7B%0A%20%20%20%20%20%20id%0A%20%20%20%20%20%20threshold%0A%20%20%20%20%20%20votingMachine%0A%20%20%20%20%7D%0A%20%20%20%20organizationId%0A%20%20%20%20preBoostedAt%0A%20%20%20%20proposer%0A%20%20%20%20quietEndingPeriodBeganAt%0A%20%20%20%20schemeRegistrar%20%7B%0A%20%20%20%20%20%20id%0A%20%20%20%20%20%20schemeToRegister%0A%20%20%20%20%20%20schemeToRegisterParamsHash%0A%20%20%20%20%20%20schemeToRegisterPermission%0A%20%20%20%20%20%20schemeToRemove%0A%20%20%20%20%20%20decision%0A%20%20%20%20%20%20schemeRegistered%0A%20%20%20%20%20%20schemeRemoved%0A%20%20%20%20%7D%0A%20%20%20%20stage%0A%20%20%20%20stakes%20%7B%0A%20%20%20%20%20%20id%0A%20%20%20%20%7D%0A%20%20%20%20stakesFor%0A%20%20%20%20stakesAgainst%0A%20%20%20%20totalRepWhenCreated%0A%20%20%20%20totalRepWhenExecuted%0A%20%20%20%20title%0A%20%20%20%20url%0A%20%20%20%20votes%20%7B%0A%20%20%20%20%20%20id%0A%20%20%20%20%7D%0A%20%20%20%20votesAgainst%0A%20%20%20%20votesFor%0A%20%20%20%20votingMachine%0A%20%20%20%20winningOutcome%0A%20%20%7D%0A%7D%0A)'s all the info about that proposal.

Its `genericScheme.callData` is `0x123455` while the encoded function signatures of the actions defined in `genericSchemeRegistry/schemes/DutchX.json` are `0x65b0d711`, `0xe1c95bb9`, `0xc6af43f9`, `0x403fbf54`, `0xf625ee28`, `0x796a8076`.

**Comment by jellegerbrandy** [comment]
This is as expected.
The dxDAO on rinkeby is not connected to a "real" dxDAO, but to a dummy contract instead. That dummy contract does not have the dutchx functions implemented, and so these calls will fail.

**Comment by Procrat** [comment]
@jellegerbrandy Would you also expect the whole UI to crash because of it? Remember that it made it hard to test #1047 because of that?
