### ISSUE TITLE
dao's history page takes around 20 seconds to load 

### ISSUE THREAD

**Issue by orenyodfat** [daostack/alchemy#1161]
https://alchemy.daostack.io/dao/0x294f999356ed03347c7a23bcbcf8d33fa41dc830/history/ 
this query take around 5 seconds.
```
{
  proposals(where:{dao:"0x294f999356ed03347c7a23bcbcf8d33fa41dc830"},first:1000) {
title
    votesFor
    votesAgainst
    scheme {
      name
    }
    stakesFor
    stakesAgainst
  }
}
```

**Comment by jellegerbrandy** [comment]
yes because it runs many different separate queries. This will be addressed in https://github.com/daostack/alchemy/pull/1166
