### ISSUE TITLE
125 % of rep ?

### ISSUE THREAD

**Issue by orenyodfat** [daostack/alchemy#1171]
<img width="1075" alt="Screen Shot 2019-10-15 at 14 48 35" src="https://user-images.githubusercontent.com/5994398/66829057-31518800-ef5b-11e9-8cd0-acef905e8099.png">

**Comment by orenyodfat** [comment]
- I was the only rep holder in the dao .
- created a proposal 
- vote 
- redeem rep.

**Comment by jellegerbrandy** [comment]
which dao?

**Comment by orenyodfat** [comment]
Necdao
