### ISSUE TITLE
scheme info - activation time present wrong value

### ISSUE THREAD

**Issue by orenyodfat** [daostack/alchemy#1173]
<img width="1378" alt="Screen Shot 2019-10-15 at 18 01 41" src="https://user-images.githubusercontent.com/5994398/66843735-dc6f3b00-ef75-11e9-8af2-71a134c16a24.png">

**Comment by dkent600** [comment]
That means the activation time is zero.

**Comment by orenyodfat** [comment]
no. in this dao the activation time is not zero. 
and if it was zero it should have been January 1st, 1970 (active)

**Comment by dkent600** [comment]
ah indeed I didn't catch the "19"

**Comment by dkent600** [comment]
@orenyodfat  what is the correct activation time?

**Comment by orenyodfat** [comment]
15 Oct 2019 14:30
