### ISSUE TITLE
what is the '+' for at the regular proposals number ?

### ISSUE THREAD

**Issue by orenyodfat** [daostack/alchemy#1186]
![Screen Shot 2019-10-23 at 15 52 07](https://user-images.githubusercontent.com/5994398/67394603-275c0480-f5ad-11e9-936e-07ecbd72d617.png)

is it suppose to disappear when scrolling down and back up ?

**Comment by jellegerbrandy** [comment]
it's a bug, and there is an issue (in targetprocess) that addresses this

**Comment by orenyodfat** [comment]
👍
