### ISSUE TITLE
Detect & Display DAO Profile Information

### ISSUE THREAD

**Issue by dOrgJelli** [daostack/alchemy#1199]
If an address is a DAO, show its details just like a normal user who has created a profile in Alchemy. Some examples of the current behavior are shown below:

1. dOrg's DAO in Members list
![image](https://user-images.githubusercontent.com/5522128/67925811-cdbb9180-fbcd-11e9-9ccb-4d357252fe9a.png)

2. Detroit DAO as a Proposal Beneficiary
![image](https://user-images.githubusercontent.com/5522128/67925835-e3c95200-fbcd-11e9-8eb3-907595970f2c.png)
![DetroitDAO](https://user-images.githubusercontent.com/5522128/67925963-3b67bd80-fbce-11e9-9bd0-4dcf5892aa32.png)

It would be great if someone viewing the above proposal would immediately know that this is a DAO, and I can click on a link to view its details in Alchemy.

**Comment by tibetsprague** [comment]
@jellegerbrandy how would you do this? load a list of every single DAOs address into the apollo cache and if an address is found there look up the rest of the data in the subgraph? eventually we will have a lot of DAOs....

**Comment by tibetsprague** [comment]
aha, maybe the subgraph can check if a reputationholder is a DAO and if it is add a flag to that object. then we know to look up the DAO info for that address. still do we need to make individual calls for each address? probably since we have no idea when or where which address will appear.

**Comment by dOrgJelli** [comment]
@tibetsprague you can check to see if the address is a contract using something like this: https://ethereum.stackexchange.com/a/28527

Then, if it is, you can query to see if the address is a DAO:
```
// please verify my syntax, off the top of my head :P
gql`
daos(where: { address: "${memberAddress}" }) {
  getTheThings...
}
`
```

You probably only want to do this for addresses that don't have a 3box profile?
