### ISSUE TITLE
Disqus Integration Reloads Frequently & Logs Out User

### ISSUE THREAD

**Issue by dOrgJelli** [daostack/alchemy#1206]
I believe this is caused by notifications appearing while someone is interacting with Disqus on a proposal page, but it happens very frequently for me so I'm unsure. Long story short, the proposal details page reloads frequently for me and causes my Disqus session to be restarted, where I have to log back in to interact with comments and post my own comments.

**Comment by parrachia** [comment]
Check your adblocker, I started seeing that too but lowering my adblocker a bit was the answer

**Comment by dOrgJelli** [comment]
This doesn't work for me unfortunately, turning off adblocker completely, and clicking on the "Stake" button where it has an overlay causes the refresh to still happen.

**Comment by dOrgJelli** [comment]
Should be fixed in https://github.com/daostack/alchemy/pull/1259#event-2831226370. Will close after validating in production. Thank you @dkent600!
