### ISSUE TITLE
user profile pop up is cut and not display correctly when the curser is hover on it..

### ISSUE THREAD

**Issue by orenyodfat** [daostack/alchemy#1207]
-  happened when the proposal is on the left side of the proposals dashboard.
- saw that only in regular proposals section..though not sure it is related 
<img width="508" alt="Screen Shot 2019-11-03 at 18 21 01" src="https://user-images.githubusercontent.com/5994398/68088401-90723080-fe67-11e9-8fd8-630a1ef294a5.png">

**Comment by dkent600** [comment]
This is already represented in https://daostack.tpondemand.com/RestUI/Board.aspx#page=board/5209716961861964288&appConfig=eyJhY2lkIjoiQjgzMTMzNDczNzlCMUI5QUE0RUE1NUVEOUQyQzdFNkIifQ==&boardPopup=bug/1730/silent

**Comment by dkent600** [comment]
Appears to be fixed.
