### ISSUE TITLE
display scheme permissions - even if it is "unsupported" scheme

### ISSUE THREAD

**Issue by orenyodfat** [daostack/alchemy#1210]
- this [dao](https://alchemy.daostack.io/dao/0x74504b811bbf357edb6daa8346d51f6dd113113f) has an "unsupported"  scheme  which full permission . and it is not a contract. 
- I guess users would like to know this info

**Comment by orenyodfat** [comment]
same as for ReputationFromToken scheme (no info/permission) tab

**Comment by dkent600** [comment]
Related to:  https://github.com/daostack/alchemy/issues/929

**Comment by tibetsprague** [comment]
@orenyodfat looks like the subgraph is not actually giving us the schemeParams for this unknown scheme so we cant display them in alchemy

**Comment by tibetsprague** [comment]
https://github.com/daostack/subgraph/issues/493

**Comment by orenyodfat** [comment]
I closed daostack/subgraph#493 . see my comment at the issue. @tibetsprague

**Comment by tibetsprague** [comment]
gotcha, ok so we just want to show permissions, no other scheme params
