### ISSUE TITLE
something went wrong :(

### ISSUE THREAD

**Issue by orenyodfat** [daostack/alchemy#1214]
<img width="909" alt="Screen Shot 2019-11-05 at 21 40 43" src="https://user-images.githubusercontent.com/5994398/68240165-0962bb00-0015-11ea-92e0-64e827873248.png">

**Comment by orenyodfat** [comment]
well, seems like this was due to subgraph issue at that moment. 
though does this is the right way to inform the user that something got wrong ? ux wise ?

**Comment by jellegerbrandy** [comment]
we have different (better?) error handling for network connections now, and although we should still do a round of controlling and checking error messages, I'm closing this issue as it is not directly relevant anymore.
