### ISSUE TITLE
reputation holders tab fail :(

### ISSUE THREAD

**Issue by orenyodfat** [daostack/alchemy#1215]
Error: Network error: Failed to fetch query ReputationHolderSearch { reputationHolders (where: { dao: "0x74504b811bbf357edb6daa8346d51f6dd113113f" dao_not: null }first: 100 orderBy: balance orderDirection: desc ) { ...ReputationHolderFields } } fragment ReputationHolderFields on ReputationHolder { id address contract dao { id } balance }

**Comment by orenyodfat** [comment]
well, seems like this was due to subgraph issue at that moment.
though does this is the right way to inform the user that something got wrong ? ux wise ?

**Comment by jellegerbrandy** [comment]
Depends. i think that if this was due to the subgraph throwing an error (say the query had wrong syntax) then this is good; if this was because the subgraph was down or slow to respond, we should probably say tot he user just that, and not mention the query in the error message

**Comment by orenyodfat** [comment]
not sure that a normal user may understand this msg : ) 
you might hide it under a link or something
