### ISSUE TITLE
fix the "copy address" buttons which are not doing anything

### ISSUE THREAD

**Issue by orenyodfat** [daostack/alchemy#1228]
<img width="718" alt="Screen Shot 2019-11-11 at 14 19 45" src="https://user-images.githubusercontent.com/5994398/68587020-b06caa00-048e-11ea-8867-50b9b8f9e055.png">

**Comment by jellegerbrandy** [comment]
to copy the value, same icon as in the address info above

**Comment by tibetsprague** [comment]
Actually they are working, there just isnt a notification telling you so anymore. How important is it to have one? I will make the buttons have a pointer cursor at least so they are more obviously buttons
