### ISSUE TITLE
All Tooltips Persist

### ISSUE THREAD

**Issue by dOrgJelli** [daostack/alchemy#1232]
When interacting with the UI and making a lot of votes & stakes, the UI got into a very laggy state and all hover tool-tips persisted forever. No exact repro available except trying to place multiple transactions while making hover tool-tips show up, and also clicking the close button on transaction toast notifications.

![image](https://user-images.githubusercontent.com/5522128/68597521-63dc9b00-049d-11ea-9613-f47fb176ba9c.png)

**Comment by dkent600** [comment]
Maybe related to this?  https://github.com/react-component/tooltip/issues/169

**Comment by jellegerbrandy** [comment]
This should be much better now, plz re-openif the issue persists
