### ISSUE TITLE
voter's details are too down at Votes popup 

### ISSUE THREAD

**Issue by orenyodfat** [daostack/alchemy#1236]
<img width="649" alt="Screen Shot 2019-11-13 at 10 56 52" src="https://user-images.githubusercontent.com/5994398/68748192-a40a5d80-0604-11ea-917c-bbef8d46c86c.png">

**Comment by dkent600** [comment]
@orenyodfat Can you be more specific?  The voter's rep is .3 percent, a small proportion.  I would expect to see in the graph an even smaller amount of visible green.  Is that it?

**Comment by orenyodfat** [comment]
The only voter (Edson ...) is located at the bottom of the pop up windows .
I expect that to somewhere at the center or upper side of the pop up window .
In this case we also might not need such a big pop up window.
