### ISSUE TITLE
Add search to DAO list (that also includes unregistred DAOs)

### ISSUE THREAD

**Issue by dOrgJelli** [daostack/alchemy#1246]
Now that newly deployed DAOs will automatically show in alchemy if you visit their URL (.../dao/0xaddress), it'd be nice to also allow users to be able to find their DAO without having to save the avatar address somewhere.

In order to do this I propose we:
- Provide an option on Alchemy's homepage to list all DAOs, instead of only the DAOregister'd ones:
https://github.com/daostack/alchemy/blob/0584e412111a10a244a5f72d9d9a177aae8597b6/src/components/Daos/DaosPage.tsx#L25-L26
- Ability to search DAOs by name.
- Filter DAOs by the ones you're a member of.
- Ability to "Favorite" a DAO, which saves its address in the browser's local storage so that the next time the user visits the page their favorited DAOs are shown first.

**Comment by jellegerbrandy** [comment]
@A-Zak

**Comment by dOrgJelli** [comment]
Would really appreciate a response to this @A-Zak

**Comment by jellegerbrandy** [comment]
:+1: for adding search. Not sure when we can schedule this in, though..

**Comment by tibetsprague** [comment]
@dOrgJelli i am going to work on this! however I dont think we should add an option to show all DAOs, the whole point of the whitelist in my mind is to not show sketchy DAOs we dont want to highlight in Alchemy. That's my opinion. @orenyodfat ? @jellegerbrandy @leviadam ?

My proposed solution is to 
1) add a search bar that finds DAOs by name 
2) Always show all DAOs that the person is a member of
3) Always show DAOs that the person follows (our version of favorites)

Sound good?

**Comment by tibetsprague** [comment]
so i added search and showing followed DAOs. but I now think that it is too much to query for all members of every DAO on this page. maybe we can just ensure that people follow new DAOs that they create? that would help. i can create a new ticket for this

**Comment by tibetsprague** [comment]
ok i managed to get it to show DAOs you are a member of now!
