### ISSUE TITLE
Alchemy will show any DAO ,when the user mention  explicitly its URL, only if it is Registered or Proposed 

### ISSUE THREAD

**Issue by orenyodfat** [daostack/alchemy#1248]
according to this https://docs.google.com/document/d/11yvLQc64MyVCj23aRnRLoD78zsx4i7yGi7UzyzLf93A/edit#

**Comment by jellegerbrandy** [comment]
This is a limitation on Alchemy behavior, but it is not clear to me what the use of it is. Reasons for not doing this:

- On staging, we are working (and testing) with DAOs that are not registered, so implementing this would break that.
- It seems to me that the subgraph should be the gatekeeper here. Why did we index that DAO in the first place if we do not want users to see be able to interact with it?
