### ISSUE TITLE
Show All DAOs You're A Member Of

### ISSUE THREAD

**Issue by dOrgJelli** [daostack/alchemy#1263]
Since newly deployed DAOs won't be discoverable through the home-page or through search, and instead users will have to remember the specific link to their DAO, it would be nice if there was a filter of the Alchemy home-page that allowed you to see all DAOs you were a member of.

**Comment by jellegerbrandy** [comment]
This is a dupliate of #1246

**Comment by jellegerbrandy** [comment]
so I'm closing htis one
