### ISSUE TITLE
privacy policy

### ISSUE THREAD

**Issue by NukeManDan** [daostack/alchemy#1277]
![image](https://user-images.githubusercontent.com/35669742/70681897-41839c00-1c5a-11ea-90a7-730418d2bb4d.png)

policy links appear twice: one IPFS and one native.

This is distinction is not obvious, consider using only one.

Also the two docs show different dates and content, so at least need to be updated to match :grin: 
One option: use IPNS for dynamic data.

https://github.com/daostack/alchemy/blob/dev/src/assets/privacy_policy.pdf

**Comment by jellegerbrandy** [comment]
@A-Zak which one is the right one?
