### ISSUE TITLE
wrong info at scheme info. 

### ISSUE THREAD

**Issue by orenyodfat** [daostack/alchemy#1282]
look at https://subgraph-master.herokuapp.com/dao/0xa0bce1b03b7f1934580e445d6274e87e582149c1/scheme/0xefbdfc23f445e50bac70fe24dad9d905cc6392adbc5050ed2a94e5cddef8d5e9/info/

3888000 is 45 days . not 14 days.

<img width="1011" alt="Screen Shot 2019-12-17 at 10 22 11" src="https://user-images.githubusercontent.com/5994398/70977783-45c71380-20b7-11ea-9098-d73408c77c23.png">

**Comment by orenyodfat** [comment]
this is not totally solved.
see https://alchemy.daostack.io/dao/0xe56b4d8d42b1c9ea7dda8a6950e3699755943de7/scheme/0xa4a97084ad598a0addf4759e2711ad8e1042ceb15c6f7d12a3bfc178052ae2c9/info/ 

<img width="1002" alt="Screen Shot 2019-12-24 at 14 15 05" src="https://user-images.githubusercontent.com/5994398/71412882-45e78600-2658-11ea-9d33-738f1a2d2115.png">

**Comment by dkent600** [comment]
@orenyodfat 

> this is not totally solved.

Those most recent numbers look correct

**Comment by orenyodfat** [comment]
what is 0.166666666666d ?

**Comment by dkent600** [comment]
@orenyodfat  If you're concerned about the precision, then please close this and open a separate ticket.  This one does appear to have been fixed.
