### ISSUE TITLE
"Could not find a DAO with id"

### ISSUE THREAD

**Issue by perlmutterlabs** [daostack/alchemy#1289]
It seems that non whitelisted DAOs (not on the ["All DAOs" front page](https://alchemy.daostack.io/daos)) are not showing up on Alchemy. KourtarooDAO was created with dOrg's DAOcreator, and was on Alchemy for about 1 week, but is now [returning an error at the URL](https://alchemy.daostack.io/dao/0xb53D5E0e5e6295277D4d68ca3882f5271B442bE0).

**Comment by perlmutterlabs** [comment]
If we launched a new DAO with DAOcreator, maybe it would work? Or is it that all non whitelisted DAOs are now not being hosted on Alchemy?

**Comment by dOrgJelli** [comment]
Oh wow, this is indeed very strange and bad :( @ben-kaufman @jellegerbrandy @orenyodfat do you know what might have happened in the back end that is causing this?

I can confirm that an original test DAO I created is not working: https://alchemy.daostack.io/dao/0x7a373624D7C34b3d1bB77eE0422d7cbF3172e66F

**Comment by dOrgJelli** [comment]
@perlmutterlabs you can see your DAO now, it looks like this was caused because the the subgraph was restarting itself.

**Comment by jellegerbrandy** [comment]
It was a bug, and it was fixed  last night, thanks @ben-kaufman !
