### ISSUE TITLE
none pleasant presentation at scheme info

### ISSUE THREAD

**Issue by orenyodfat** [daostack/alchemy#1290]
see https://alchemy.daostack.io/dao/0xe56b4d8d42b1c9ea7dda8a6950e3699755943de7/scheme/0xa4a97084ad598a0addf4759e2711ad8e1042ceb15c6f7d12a3bfc178052ae2c9/info/ 

<img width="1002" alt="Screen Shot 2019-12-24 at 14 15 05" src="https://user-images.githubusercontent.com/5994398/71412882-45e78600-2658-11ea-9d33-738f1a2d2115.png">

- it can show only 2 decimal digits after dot or find a better way to represent it.

**Comment by jellegerbrandy** [comment]
Will be included int he next release

**Comment by orenyodfat** [comment]
> Will be included int he next release

which one ? when ?
