### ISSUE TITLE
scheme registrar proposals should not show paramsHash in proposal form for non-universal schemes

### ISSUE THREAD

**Issue by jellegerbrandy** [daostack/alchemy#1296]
the parameter is ignored (?) but it is confusing in any case.

**Comment by dkent600** [comment]
FYI This would apply to `ContributionRewardExt`, part of the `Competition` feature.

**Comment by dkent600** [comment]
@jellegerbrandy Do we have a nice API from the client lib for telling us that a scheme is not universal?

**Comment by jellegerbrandy** [comment]
Good question, answer is no. 

At the moment, the user can fill in any address as the scheme address, and we have no way of knowing what type of scheme we are talking to. We could get some information from ContractInfos, and one the basis of that decide if we know the scheme, and if so, add  or remove the paramsHahs to the form.  

But this wil ln any case not fix the major UX problem here: the "paramsHash" field is hostile to our users (and "filling in any address" is as well).

So I'm closing this issue, because I think it needs more thought, and should be part of a more complete refactor.
