### ISSUE TITLE
Add unit tests

### ISSUE THREAD

**Issue by tsuberim** [daostack/alchemy#13]
Adding unit tests could help, especially for `redux-thunk` actions.

**Comment by tibetsprague** [comment]
this would be a great thing to take on :)

**Comment by tibetsprague** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add automated tests](https://trello.com/c/pjdvXnPi/127-add-automated-tests)

**Comment by jellegerbrandy** [comment]
closing this as it is a year old tomorrow :-)
