### ISSUE TITLE
Logo design

### ISSUE THREAD

**Issue by Batarian711** [daostack/alchemy#130]
Hi. I design a free logo to support projects. I designed one for you. I can give you a gift. 

![alchemy](https://user-images.githubusercontent.com/41051393/42969528-1bd1d860-8baf-11e8-801a-bccada328627.jpg)

**Comment by Garbash** [comment]
Thank you for your lovely gift,
I really appreciate your take on the app!
Unfortunately, it's not exactly our brand style. You are welcome to check out daostack.io to learn more about the colors and styles we use.
