### ISSUE TITLE
reputation should not be rounded down..

### ISSUE THREAD

**Issue by jellegerbrandy** [daostack/alchemy#1316]
In this example, the user has 100% of the rep, which are like 100 tokens. This is represented as "0 tokens"  (also on the popups):

![image](https://user-images.githubusercontent.com/1306173/72735426-15820180-3b9c-11ea-9d04-88530687541b.png)

**Comment by jellegerbrandy** [comment]
This error is probably related:

![image](https://user-images.githubusercontent.com/1306173/72735653-8a553b80-3b9c-11ea-9409-3f9b984f14e3.png)

**Comment by jellegerbrandy** [comment]
![image](https://user-images.githubusercontent.com/1306173/72736176-88d84300-3b9d-11ea-855f-605acc1a7c2f.png)

**Comment by tibetsprague** [comment]
can you share an example DAO to see this?

**Comment by tibetsprague** [comment]
unclear how to reproduce so closing for now
