### ISSUE TITLE
upgrade to latest web3connect release

### ISSUE THREAD

**Issue by dkent600** [daostack/alchemy#1320]
The latest web3connect release breaks our build.

**Comment by jellegerbrandy** [comment]
can you elaborate,  at which point does it break? And why do we need to use this build-breaking release?

**Comment by dkent600** [comment]
They have altered their API.  We can simply lock in to the version that works for us.  No rush to upgrade that I know of.

**Comment by jellegerbrandy** [comment]
I do not understand this issue.
So you do _not_ want to upgrade to the latest release?
What is the problem here? What is broken?

**Comment by dkent600** [comment]
The build is broken, that is, the code doesn't compile because we are using functions that have been deleted.  If you refresh the package-lock.json file you will see this happen as the new package i pulled in.

There is no rush until we refresh package-lock.json.

**Comment by dkent600** [comment]
Done

**Comment by jellegerbrandy** [comment]
Why'd you reopen this?
