### ISSUE TITLE
bundle optimization: our loader animation weighs > 500Kb

### ISSUE THREAD

**Issue by jellegerbrandy** [daostack/alchemy#1326]
This is because we are using `react-lottie` to render it.

Goal: lose the lottie dependency.

**Comment by jellegerbrandy** [comment]
@A-Zak , @tibetsprague asks: " is there any way that Dana could redo the loading animation in CSS or give us a simpler one? im having a hard time figuring out how to do that myself and its too expensive to load a massive library (500k) just for that one animation"

**Comment by dkent600** [comment]
I want a shot at this  :-)

**Comment by dkent600** [comment]
Waiting for a new icon from Colin.
