### ISSUE TITLE
bundle optimization: we are including src in the bundle, 

### ISSUE THREAD

**Issue by jellegerbrandy** [daostack/alchemy#1329]
this adds a useless  667kb

**Comment by tibetsprague** [comment]
hmm @jellegerbrandy, are you sure about this? if i do a build i don't see the src. i think what you are seeing is simply the source map laying out all the files in the app bundle

**Comment by tibetsprague** [comment]
@jellegerbrandy did you see my comment?

**Comment by jellegerbrandy** [comment]
this was in npm run analyze; I'm not seeing it anymore
