### ISSUE TITLE
add burner wallet to web3connect

### ISSUE THREAD

**Issue by jellegerbrandy** [daostack/alchemy#1342]
[from Eylon:] 
I want to test the Web3connect wallet asap, the burner wallet supports it and we need to add it to alchemy
https://web3connect.com/

The walkthrough to test it is:

1. Create a fortmatic account in the burnerapp at https://denver-demo.burnerfactory.com/
1. click the number in the top right hand corner of the burnerapp to get your burner wallet address
1. from the DAO Mint reputation to your address
1. Go to https://alchemy-competition-mainnet.herokuapp.com/—> Click connect and use burner connect.
1. Vote / propose / submit from the burner connect

**Comment by jellegerbrandy** [comment]
the denver-demo thing is connected to kovan (not to rinkeby or main), so we cannot test the integration in the way that you describe

**Comment by jellegerbrandy** [comment]
also, the burner connect button is not working for me at web3connect.com
```
hub.js:11 Uncaught DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
    at loadWallets (https://burnerconnect.xyz/hub.js:11:24)
    at Object.getWallets (https://burnerconnect.xyz/hub.js:41:20)
    at receiveMessage (https://burnerconnect.xyz/hub.js:54:34)
loadWallets @ hub.js:11
getWallets @ hub.js:41
receiveMessage @ hub.js:54
hub.js:56 Unknown command undefined
```

**Comment by jellegerbrandy** [comment]
related #1320

**Comment by dmihal** [comment]
@jellegerbrandy Are you running Brave? We've notice that Brave's anti-tracking shield seems to break BurnerConnect

**Comment by dkent600** [comment]
Done

**Comment by jellegerbrandy** [comment]
@dmihal I'm running chrome..

**Comment by jellegerbrandy** [comment]
Connecting to burner wallet in main net on https://alchemy-competition-mainnet.herokuapp.com/ gives me error “please connect your wallet provider to mainnet”.  Something to solve on our end.

In addition, I opened the following issues on the burner-connect repo:

* [ ] https://github.com/burner-wallet/burner-connect-hub/issues/1
* [ ] https://github.com/burner-wallet/burner-connect-hub/issues/2
* [ ] https://github.com/burner-wallet/burner-connect-hub/issues/3
* [ ] https://github.com/burner-wallet/burner-connect-hub/issues/4
* [ ] https://github.com/burner-wallet/burner-connect-hub/issues/5

**Comment by jellegerbrandy** [comment]
Connecting to burner wallet in main net on https://alchemy-competition-mainnet.herokuapp.com/ gives me error “please connect your wallet provider to mainnet”.  Something to solve on our end. --> this is solved in ff71e58c1bd93a205e093f99467ee1f59b0a5921

**Comment by jellegerbrandy** [comment]
I solved my chrome issue by allowing third-party cookies. We need to catch that error and show it to the user - which needs https://github.com/burner-wallet/burner-connect-hub/issues/2 to be solved.

**Comment by dkent600** [comment]
> I solved my chrome issue by allowing third-party cookies. We need to catch that error and show it to the user - which needs [burner-wallet/burner-connect-hub#2](https://github.com/burner-wallet/burner-connect-hub/issues/2) to be solved.

Should be mentioned in a troubleshooting doc somewhere.
