### ISSUE TITLE
add tor.us to web3connect

### ISSUE THREAD

**Issue by jellegerbrandy** [daostack/alchemy#1343]

**Comment by dkent600** [comment]
Torus

**Comment by dkent600** [comment]
Forgive me, I commitred this to the Competition branch by accident.

**Comment by jellegerbrandy** [comment]
Why is this blocked?

**Comment by dkent600** [comment]
blocked because:  https://github.com/torusresearch/torus-embed/issues/100#issuecomment-588980747

**Comment by dkent600** [comment]
Blocked because I have insufficient auth to access heroku to determine why the review app is not building.  @orenyodfat

**Comment by dkent600** [comment]
@orenyodfat FYI pulling in the latest torus does not fix the problem.  I will let them know...

**Comment by orenyodfat** [comment]
Heroku review app should work with this fix https://github.com/daostack/alchemy/commit/5c93b68c2c5b4edd5519bd4bcb99b33886fa3a22 
(tested on other test branch)
