### ISSUE TITLE
Mixpanel issues outside from the "official" urls

### ISSUE THREAD

**Issue by jellegerbrandy** [daostack/alchemy#1347]
The mixpanel update broke all (many?) of our review apps - it only seems to work on localhost and the "official" staging and production urls.

I fixed this by defining `doTracking` in `analytics.ts` like this:
```
const doTracking = (
  (process.env.NODE_ENV === "staging" || process.env.NODE_ENV === "production") &&
  (window.location.origin in [
    'https://alchemy.daostack.io',
    'https://alchemy-staging-rinkeby.herokuapp.com/',
    'http://127.0.0.1:3000',
    'http://localhost:3000'
  ])
)
```
But this seems unsatisfactory, as we cannot test the mixpanel stuff in the review apps.

**Comment by tibetsprague** [comment]
I don’t think we can fix this. Why do we need to keep testing it? I’ll see if mixpanel can handle arbitrary urls but otherwise maybe we just use on production

**Comment by tibetsprague** [comment]
actually i cant see any reason why the Mixpanel token wouldn't be working on review apps, are there specific ones that broke that you know of that i can test on?

**Comment by tibetsprague** [comment]
the only reason this might happen is if a review app doesnt have a mixpanel token
