### ISSUE TITLE
Reputation from tokens does not update correctly when siwthing accounts

### ISSUE THREAD

**Issue by jellegerbrandy** [daostack/alchemy#1348]
Basically, it seems it always resets to 0, and you need to reload the page to see the actual amount you can redeem..

**Comment by dkent600** [comment]
I'm not sure it updates after redeeming, either.

**Comment by tibetsprague** [comment]
i actually dont know how to test this. if i go to the Nectar DAO on ganache and click on Reputation from Token i see this error: 
Uncaught (in promise) Error: Returned values aren't valid, did it run Out of Gas? You might also see this error if you are not using the correct ABI for the contract you are retrieving data from, requesting data from a block number that does not exist, or querying a node which is not fully synced.

**Comment by tibetsprague** [comment]
with the way we do client calls now i dont know of any good way to detect that redeem succeeded and then set the tokens to redeem to 0 in the component...

**Comment by tibetsprague** [comment]
ohhhh, looking at the code it only fires after 23 confirmations. this is confusing I think, can we make it fire after 3?
