### ISSUE TITLE
<a> console errors

### ISSUE THREAD

**Issue by dkent600** [daostack/alchemy#1349]
I'm seeing a lot of this in the console:

> Warning: validateDOMNesting(...): <a> cannot appear as a descendant of <a>.
    in a (created by Link)
    in Link (created by AccountProfileName)
    in AccountProfileName (created by AccountPopup)
    in div (created by AccountPopup)
    in div (created by AccountPopup)
    in div (created by AccountPopup)
    in AccountPopup (created by Connect(AccountPopup))
    in Connect(AccountPopup) (created by WithSubscriptionComponent)
    in WithSubscriptionComponent (created by ProposalData)
    in div (created by ProposalData)
    in div (created by ProposalData)

@tibetsprague

**Comment by tibetsprague** [comment]
yeah this is really annoying. this is because of the ticket to make the whole proposal card clickable. when I made this change I didn't see these errors, but now they are appearing, which is very weird and annoying
