### ISSUE TITLE
reputation more than 100%

### ISSUE THREAD

**Issue by dkent600** [daostack/alchemy#1357]
This was on ganache.

1. reward yourself a ton of reputation
1. redeem it
1. after the redeem tx has been confirmed, but without refreshing the app, hover over the account menu.

RESULT: see screen shot below.
EXPECT:  should be under 100%, if only slightly

![image](https://user-images.githubusercontent.com/1821666/73595637-87354600-44e0-11ea-8722-c8cc64290e00.png)

**Comment by tibetsprague** [comment]
hmm, i cant reproduce this. can you try again @dkent600 ? maybe the subgraph wasnt updating when you tried this?

**Comment by dkent600** [comment]
I am blocked on retrying this by:  https://github.com/daostack/alchemy/issues/1470

**Comment by dkent600** [comment]
I am no longer able to reproduce this.
