### ISSUE TITLE
auto detect network.

### ISSUE THREAD

**Issue by orenyodfat** [daostack/alchemy#1359]
Currently alchemy use different urls for different network .
Also different instances for different networks as there is a different subgraph for each network. 

this can be avoided by : 
1.  detect the network from the user wallet. 
2. switch to the relevant subgraph vxxx_network.

**Comment by jellegerbrandy** [comment]
I consider having a separate url for each network a feature

- the app also works when not connected with any wallet to the network
- the user wallets we support depend on the network we are connecting to, so we muyst know the network before connecting to a user wallet
- some wallets (like the burner wallet) do not support choosing of the network

**Comment by dkent600** [comment]
@jellegerbrandy actually, burner wallet requires that you choose the network.  If you want to connect to rinkeby, you have to tell it to, otherwise it will always try to connect to mainnet.

**Comment by tibetsprague** [comment]
I’m on the fence here because if we keep adding more networks it will get annoying to have them all be separate environments. Also it would be nice to make it easier to use each environment (dev, staging, prod) with any network. What if for each ENV we just have a default network it connects to but then you can switch networks from the wallet and have that detected in alchemy?

**Comment by dkent600** [comment]
@tibetsprague Most of these wallets don't allow you to "switch networks within the wallet".  They aren't like MetaMask in that respect.  Rather, you have to configure the wallet when you instantiate the provider to talk to a specific network.

So we would need to have a UI in Alchemy that enables users to switch networks.

**Comment by jellegerbrandy** [comment]
What @dkent600  says. It is not a matter of usability, it is just not always possible to switch networks from the wallet (or to "auto-detect the network"). 

The whole discussion is not relevant at all for our UX, I think. We support **only one network** at this moment. We **maybe** will support xdai. All the other things (ganache, rinkebey, whatever) are just part of the dev process, and are not front-end facing, and so do not present UX problems to end-users that we need to solve.

Closing this again.
