### ISSUE TITLE
wrong winners calculation

### ISSUE THREAD

**Issue by dkent600** [daostack/alchemy#1365]
Reported by Eylon: Have a look at this competiton, it just ended and I think there is a problem with the winners:

https://alchemy-competition-mainnet.herokuapp.com/dao/0x00ea828bf150ec08cad91ee93841785c827b78f4/crx/proposal/0x0fe7704cb125f8ebdf18f6f1267351d393af640201f31687e7212edbb37de1a6

@ben-kaufman @orenyodfat

**Comment by jellegerbrandy** [comment]
fixed with new subgraph v37-3
