### ISSUE TITLE
Custom Alchemy App for ETHDenver

### ISSUE THREAD

**Issue by Theylon** [daostack/alchemy#1366]
Create a custom alchemy deployment for ETHDenver.  

- ETHDenver.alchemy.io to include all ETHDenver DAOs (main and sponsor DAOs) 
- xDAI support
- "Connect" button will only try burnerwallet/prioritize if burnerwallet exists and connect to it
- Change "Rep/Reputation" to "XP/Experience"
- Add a ETHDenver logo/Pegabufficorn in the sidebar, URL sends the user back to the "ETHDenver Dashboard"

**Comment by Theylon** [comment]
Additional cosmetic changes:

- Block explorer should link to blockscout rather than etherscan: (DAO holdings)
https://blockscout.com/poa/xdai/address/0xe248a76a4a84667c859eb51b9af6dea29e52f139/transactions
- Change % to number of reputation (Long debate yes, for this it should be # of rep and not %)

**Comment by dkent600** [comment]
@Theylon everywhere I look I can see the absolute value of rep when I hover over the %.  Is this not sufficient?

**Comment by Theylon** [comment]
It should be the other way around, showing % is just counterintuitive, especially in a voting game like this, and I would argue for the entire of Alchemy.  

This has also been the feedback from Genesis DAO members.
