### ISSUE TITLE
Replace Disqus with Commento

### ISSUE THREAD

**Issue by Theylon** [daostack/alchemy#1369]
I don't think there's anyone who has used Alchemy and haven't experienced an issue with disqus. in addition, it seems like Disqus is the cause of one of our biggest issues / problems - Alchemy payload size. 

Thankfully someone has done the research for us:

https://victorzhou.com/blog/replacing-disqus/

> It gets even better. Here are more reasons I was sold on Commento:
> 
> - It’s open source and can be self-hosted.
> - It’s privacy focused - it doesn’t sell user data and tries to collect as little as possible. This is especially nice given that my blog’s audience is probably more privacy-conscious than the average internet user.
> - You can pay what you want. Disqus’s free tier is ad-supported, and its cheapest paid tier is $9/month. Commento is actually cheaper (if you want it to be)!
> - It’s configurable. If you scroll down to the comments of this post, you’ll see that the styling of the Commento integration matches the styling of the rest of the site.
> - It has an Import from Disqus tool that’s easy to use. I was able to quickly migrate all of my old Disqus comments to Commento

**Comment by Theylon** [comment]
More stuff here actually 

https://idratherbewriting.com/blog/switch-from-disqus-to-commento/ lot's of positive feedback on commento

**Comment by jellegerbrandy** [comment]
That's a nice idea, but I'm closing this issue as we will not do this in the near future (and if we replace disques, we'll probably go for the 3box solution, because it is blockchainnetaive, decentralized and we already use 3box for our profiles)
