### ISSUE TITLE
Optimize client lib queries associated with Competitions

### ISSUE THREAD

**Issue by dkent600** [daostack/alchemy#1370]
Optimize client lib queries associated with Competitions.  No more server subscriptions than required. Review the queries that they are efficient in working from the cache.

**Comment by dkent600** [comment]
- [x ] SchemeContainer:  already done (pulling in executed proposals)
- [ ] (Competition)Card: submissions and votes (should do in List?)
- [ ] (Competition)Details: submissions and votes
- [ ] SubmissionDetails: submissions and votes

**Comment by dkent600** [comment]
Somehow the proposal data caching code is able to arrange that proposal votes, stakes and rewards are "cached with each proposal", and it is possible to do something like `(new Proposal(proposalId)).votes()` without hitting the server. I think we need to figure out how to similarly do the following without hitting the server:

1. `(new Competition(proposalId)).suggestions()`
2. `(new Competition(proposalId)).votes()`
3. `(new CompetitionSuggestion(suggestionId)).votes()`
4. `(new CompetitionSuggestion(suggestionId)).suggestions()`
5. `(new CompetitionSuggestion(suggestionId)).state()`

I have refactored all of the queries so that they all use the above patterns.

However, the queries are not pulling from the cache.

1. Are changes required in the client, such as what appears to have been done for proposal votes, stakes and rewards?
2. Is there something else, besides pre-querying all suggestions and votes, which I'm doing,  that needs to happen in the app for this to work?

**Comment by jellegerbrandy** [comment]
1. yes
2. no

**Comment by jellegerbrandy** [comment]
Re this:

`(new CompetitionSuggestion(suggestionId)).suggestions()` --> that does not make sense to me

`(new CompetitionSuggestion(suggestionId)).state()` <- that should be cached no problem

**Comment by jellegerbrandy** [comment]
Also, as all of this is specific cache designing for the alchemy use case:what is the use case for getting all votes in a competition?

**Comment by dkent600** [comment]
> Re this:
> `(new CompetitionSuggestion(suggestionId)).suggestions()` --> that does not make sense to me

Indeed, that should not have been in the list.  I'll remove it.

**Comment by dkent600** [comment]
> `(new CompetitionSuggestion(suggestionId)).votes()`
> 
> as all of this is specific cache designing for the alchemy use case:what is the use case for getting all votes in a competition?

We display a count of Competition votes in the Competition card.

**Comment by jellegerbrandy** [comment]
> We display a count of Competition votes in the Competition card.

Ok. Getting all the votes and counting them is not very nice. I opened this here: https://github.com/daostack/subgraph/issues/468
