### ISSUE TITLE
ProposalCard should not show this warning

### ISSUE THREAD

**Issue by dkent600** [daostack/alchemy#1374]
Seeing this in the console:

> react-dom.development.js:530 Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.
    in WithSubscriptionComponent (created by ProposalCard)
    in ProposalCard (created by SchemeProposalsPage)
    in Transition (created by CSSTransition)
    in CSSTransition (created by Fade)
    in Fade (created by SchemeProposalsPage)
    in div (created by TransitionGroup)
    in TransitionGroup (created by SchemeProposalsPage)
    in div (created by InfiniteScroll)
    in div (created by InfiniteScroll)
    in InfiniteScroll (created by SchemeProposalsPage)
    in div (created by SchemeProposalsPage)
    in div (created by SchemeProposalsPage)
    in div (created by SchemeProposalsPage)
    in div (created by SchemeProposalsPage)
    in SchemeProposalsPage (created by WithSubscriptionComponent)
    in WithSubscriptionComponent (created by Connect(WithSubscriptionComponent))
    in Connect(WithSubscriptionComponent) (created by Route)

@tibetsprague

**Comment by tibetsprague** [comment]
@dkent600 when do you see this?

**Comment by dkent600** [comment]
https://alchemy-staging-rinkeby.herokuapp.com/dao/0x72939947e7a1c4ac94bb840e3304b322237ad1a8/scheme/0x16b81c56297ae81ffa32ed128f17dbf7b108eb9200d2c8110a9ff2e05e095995
