### ISSUE TITLE
Redeem Issue (a new one)

### ISSUE THREAD

**Issue by knowyourdao** [daostack/alchemy#1377]
It's just "Expired", no option to redeem on Alchemy, for this proposal that I upstaked but it was never boosted: https://alchemy.daostack.io/dao/0x294f999356ed03347c7a23bcbcf8d33fa41dc830/proposal/0xff2afa5a3394d8c96fe8d6d65c3890378f81e82d826dad6d4022d9e628d79e5d

Tryin' to dump my $GEN since the proposal failed, let me redeem it and exit! ;)

<img width="1192" alt="Screen Shot 2020-02-04 at 11 24 20 PM" src="https://user-images.githubusercontent.com/60011897/73793013-cb0ca180-47a5-11ea-8ee5-fa6c09d71a27.png">

**Comment by jellegerbrandy** [comment]
"redeem" also seems to have disappeared from the history page.

Sorry about this, @knowyourdao , we'll get to it asap

**Comment by tibetsprague** [comment]
This is a subgraph issue. Also I thought removing the redeem from the history page was on purpose but I’ll figure that out...

**Comment by knowyourdao** [comment]
> This is a subgraph issue. Also I thought removing the redeem from the history page was on purpose but I’ll figure that out...

Yeah it seems there are some numerous and tricky permutations around proposal redemption. I imagine there are at least 10 different permutations. Maybe worth treeing out, whiteboarding, if haven't tried yet.

**Comment by tibetsprague** [comment]
reopened this issue: https://github.com/daostack/subgraph/issues/455

**Comment by tibetsprague** [comment]
as far as redeem not being on the history page that was a design choice by @A-Zak. its been that way at least since July...

**Comment by knowyourdao** [comment]
It seems that something changed, and it's semi-functional now, but I'm pretty sure redeem is still super buggy.

I think there are just a lot of permutations to redeem (nodes and leaves?), maybe worth whiteboarding it.

**Comment by jellegerbrandy** [comment]
@knowyourdao I agree that that logic needs a serious refactor, although I am not sure we will have time to schedule that in. 

If you have any specific bugs you know of, please open a new issue.
