### ISSUE TITLE
In competition "Submissions can only be created by you" doesn't enforce you as the only submittor

### ISSUE THREAD

**Issue by Theylon** [daostack/alchemy#1384]
When creating a competition there is an option to make it so only you can create submissions. 

*Submissions can only be created by you

Using this doesn't work currently, tested in these 3 competitions on rinkeby.

https://alchemy-competition-rinkeby.herokuapp.com/dao/0x123f3722cf8cfcecc6ee833b08e895516eb36f31/crx/proposal/0x3286b000e3def99b1fc6f026f017491d4411475315ce7242ab9b924f2e5fb2e4

https://alchemy-competition-rinkeby.herokuapp.com/dao/0x123f3722cf8cfcecc6ee833b08e895516eb36f31/crx/proposal/0x0e1ecabe03efcf7c3038335f80aec653bfc764a4525d60fe0728225934297f50

https://alchemy-competition-rinkeby.herokuapp.com/dao/0x123f3722cf8cfcecc6ee833b08e895516eb36f31/crx/proposal/0xd6d63174452ab1e7ed411e891b0047a4eacf8b9f3bbd74731ed0312984dfd2de

**Comment by dkent600** [comment]
Looks like the subgraph is not supplying `Proposal.proposerIsAdmin` as it should be.

@ben-kaufman or @orenyodfat can you please take a look and confirm?  Try this:

This won't compile:

```
{
  proposals {
    id, competition {
      proposerIsAdmin
    }
  }
}
```

here:  https://thegraph.com/explorer/subgraph/daostack/v37_3_rinkeby?version=current, which is where Alchemy rinkeby is pointed for this ticket.

**Comment by jellegerbrandy** [comment]
@dkent600 ; can you explain why you say this is "as it should be?"  (and  If this is a information we need, please open an issue in the subgraph?) 

In any case, this does not seem to be related to @Theylon's original issue.

**Comment by dkent600** [comment]
@jellegerbrandy it is definitely related.  The app cannot correctly disable the New Submission button without knowing the correct value of `proposerIsAdmin`.

But the real problem here is described in [this ticket in the client](https://github.com/daostack/client/issues/407);

**Comment by dkent600** [comment]
When this is all working right I can uncomment some code that will show a meaningful tooltip on the New Submission button in the case of a user who has no right to submit,

**Comment by Theylon** [comment]
It seems like this is working, although the error is a nasty one :) 



![image](https://user-images.githubusercontent.com/27952472/74076086-1d7ed580-49d3-11ea-827a-40209b0884b8.png)
