### ISSUE TITLE
In the competition: When scrolling down on a submission disqus has bugs and blends with the background

### ISSUE THREAD

**Issue by Theylon** [daostack/alchemy#1386]
Mobile Only:
https://alchemy.daostack.io/dao/0x00ea828bf150ec08cad91ee93841785c827b78f4/crx/proposal/0x0fe7704cb125f8ebdf18f6f1267351d393af640201f31687e7212edbb37de1a6/competition/submission/0x76810bb9b9481e376bf2d575657a9e0c8c527e4973bac9c9974005f1e7c2b2b0

![image](https://user-images.githubusercontent.com/27952472/73967487-3a34e380-48d5-11ea-916e-a74d1188f0a2.png)

**Comment by dkent600** [comment]
Closing because we no longer display disqus in the submission details popup.
