### ISSUE TITLE
Url should reference scheme contract address rather than subgraph scheme id

### ISSUE THREAD

**Issue by dkent600** [daostack/alchemy#1389]
It is a pain that in an Alchemy url that references a scheme, the scheme is identified by its subgraph id instead of its contract address.  Then it is so much easier for anyone to copy the address and go to etherscan to inspect the contract.  This would be consistent with what we do with DAOs in the URL.

**Comment by jellegerbrandy** [comment]
I do not think copying from URLs and pasting in etherscan is a pattern we need to support or change our code for.  The scheme address is in the info tab, including a link to etherscan, which seems to cover the use case pretty well.

**Comment by dkent600** [comment]
Ah, OK, didn't realize it was in the scheme tab
