### ISSUE TITLE
Competition: Before a user is logged in he sees random green thumbs up (voted) on submissions, upon logging in this disappears

### ISSUE THREAD

**Issue by Theylon** [daostack/alchemy#1404]
![image](https://user-images.githubusercontent.com/27952472/74118719-d121ca00-4b79-11ea-97d3-fe9ee0b2edb7.png)

**Comment by dkent600** [comment]
What is the account showing before and after in?

**Comment by jellegerbrandy** [comment]
I suspect this is because you switched accounts - alchemy will show the data of the last account you "logged in with". Clicking "connect" changed that address (apparently) and the UI updated.

Could that explain the problem?

**Comment by Theylon** [comment]
mmm I don't think so, this was reported by a user on his first login. 
+ it has like 5 thumbs up where you can only vote twice

**Comment by Theylon** [comment]
Sorry adding URL to that: 
https://alchemy-competition-xdai.herokuapp.com/dao/0xe248a76a4a84667c859eb51b9af6dea29e52f139/crx/proposal/0xcec4b3377180d361b8acacdd1d48cc9c9d80f4933f3120c0435b4493e81dee96

**Comment by dkent600** [comment]
Thanks @Theylon This is already fixed.
