### ISSUE TITLE
Competition: Allow anyone to redeem submissions (Not only beneficiery)

### ISSUE THREAD

**Issue by Theylon** [daostack/alchemy#1408]
I see this as being an annoyance at ETHDenver
![image](https://user-images.githubusercontent.com/27952472/74191550-0decd000-4c11-11ea-9da6-bad4d752fb5f.png)

**Comment by Theylon** [comment]
@dkent600 We're getting some bad UX feedback on this from people using the competition in the Fittogether DAO. 
I believe in the first versions this wasn't included and was added later. Could this come up in the next meeting @EzraWeller

**Comment by dtbx** [comment]
Second @Theylon there, it's becoming really challenging to get people to have to click redeem so many times instead of let a community manager redeem for everyone.
