### ISSUE TITLE
alchemy should warn if the subgraph is not getting updates

### ISSUE THREAD

**Issue by jellegerbrandy** [daostack/alchemy#1419]
This requires getting block info from the subgraph (which is not available form the subgraph itself, but from the "subgraph of subgraphs")

**Comment by tibetsprague** [comment]
any more info to get started on this? how do i do this @orenyodfat @ben-kaufman ?

**Comment by ben-kaufman** [comment]
Hi @tibetsprague 

The URL to access this "subgraph of subgraphs" is: `https://api.thegraph.com/index-node/graphql`. You can see here an example of how I interact with it: `https://github.com/daostack/alchemybots/blob/aaff67cb9f88e7476fdb1eedc9b46fab3aca51ec/check-subgraph-status.js#L142`.

**Comment by dkent600** [comment]
@ben-kaufman This github link you gave above is 404.

**Comment by ben-kaufman** [comment]
@dkent600 They're POST only.

**Comment by dkent600** [comment]
@ben-kaufman Can you please send a url for "an example of how I interact with it" that we can GET?

**Comment by ben-kaufman** [comment]
No, there is none that allows GET requests. But you could use http://altair.sirmuel.design/ which lets you play with it nicely.

**Comment by tibetsprague** [comment]
@ben-kaufman the link i want to see is the one you said shows an example of how to interact with it. that is also a 404

**Comment by tibetsprague** [comment]
oh, @ben-kaufman i think i just dont have access to that repo. @leviadam can you add me to alchemybots?

**Comment by dkent600** [comment]
> No, there is none that allows GET requests. But you could use http://altair.sirmuel.design/ which lets you play with it nicely.

@ben-kaufman @tibetsprague that Altair app was blocked by my virus detector (Windows Defender) as containing a threat.

**Comment by ben-kaufman** [comment]
Strange, so you can either ignore the warning or try another one. This worked for me too and is online soo no download: https://lucasconstantino.github.io/graphiql-online/

**Comment by imolorhe** [comment]
> that Altair app was blocked by my virus detector (Windows Defender) as containing a threat.

@dkent600 I believe you mean that Windows considered the file as not trustworthy because the application isn't signed 🙂not necessarily that it contains a virus.

Ps: You also have the options of using Altair as a browser extension in both Chrome and Firefox.

**Comment by orenyodfat** [comment]
pr #1546 have an issue that it shows errors where not suppose to.

**Comment by dkent600** [comment]
Code to implement this was merged in #1546 but has been disabled until we figure out why it sometimes thinks we're disconnected when we aren't.

I saw this start to happen against rinkeby, coincidentally or not, _I think_ it was when I went to vote on a proposal, and I was automatically asked to Connect, I did, some notifications appeared, then blame, it thought I wasn't connected.
