### ISSUE TITLE
Competition: Change Competition tab and Proposals tab

### ISSUE THREAD

**Issue by Theylon** [daostack/alchemy#1464]
Competitions tab should be the first tab a user sees, this caused us A LOT of problems at ETHDenver. 

@dkent600

**Comment by jellegerbrandy** [comment]
I totally agree that the UX was way problematic at ethDenver. 

I however do not think that the right solution here is to make small changes of this type to the UX. That will just make Alchemy even more chaotic then it already is. 

Instead this needs a more systematic approach.

(For example, this particular request: it will improve, somewhat, the exp of a user that wants to participate in a competition and somehow lands on the Competition Scheme page. But it will make the expreience of the user that s there to vote or stake in the protcol less good. So we need to think this trhough more systaemtically.)

**Comment by dkent600** [comment]
> Instead this needs a more systematic approach.

Exactly the reaction I had
