### ISSUE TITLE
should be able to create a CR proposal

### ISSUE THREAD

**Issue by dkent600** [daostack/alchemy#1470]
local build with ganache, on latest dev branch, in the DAO "Adamant Apples", trying to create a proposal, clicking "Submit proposal" does nothing.

![image](https://user-images.githubusercontent.com/1821666/75783367-145cfc00-5d26-11ea-8aa1-730b5bb4832b.png)

**Comment by dkent600** [comment]
Perhaps should wait to work this until https://github.com/daostack/alchemy/pull/1469 is merged.  @tibetsprague

**Comment by tibetsprague** [comment]
i will look at it

**Comment by tibetsprague** [comment]
@dkent600 worked for me!

**Comment by dkent600** [comment]
Works ok for me now
