### ISSUE TITLE
"Fetching more proposals" can be more accurate

### ISSUE THREAD

**Issue by dkent600** [daostack/alchemy#1481]
Can we reword "Fetching more proposals" to something like "Awaiting new proposals..."

Fetching always makes me think that more proposal already exist that have simply not yet been fetched for display.

(maybe even better would be to eliminate this text altogether.)

![image](https://user-images.githubusercontent.com/1821666/76106127-db2dc180-5f9b-11ea-99ef-84b6b030d1af.png)

**Comment by tibetsprague** [comment]
i dont understand this. it is fetching more proposals that already exist and have not yet been fetched...

**Comment by dkent600** [comment]
> i dont understand this. it is fetching more proposals that already exist and have not yet been fetched...

Rephrase:

Reading the word "Fetching" always makes me think that more proposals already exist, have been created, that are not yet visible simply because they haven't arrived to the app.  So I can thumb the table and soon some more proposals will arrive, or if not, maybe there is something wrong with my internet connection.  I'll just refresh the page and see if they show up.

This is as opposed to the reality which is that no more proposals exist to be fetched, we are not "fetching" anything, rather we are waiting for new proposals to be created. So I can chill.

**Comment by tibetsprague** [comment]
that is not true. fetching is supposed to mean that we are fetching more proposals that already exist. if it is saying that when there no more proposals to load then it is a bug

**Comment by tibetsprague** [comment]
I think we can eliminate the text

**Comment by dkent600** [comment]
I can't reproduce this now.
