### ISSUE TITLE
DAO search should not stop responding after loading more DAOs

### ISSUE THREAD

**Issue by dkent600** [daostack/alchemy#1484]
In staging:

1. go to All DAOS page
1. scroll down 2 or 3 times, enough to pull in some more DAOs
1. type something in the DAOs filter textbox

RESULT:
The filter will work on the first character typed, but after that, no longer responds

**Comment by dkent600** [comment]
@tibetsprague

**Comment by tibetsprague** [comment]
cannot reproduce

**Comment by dkent600** [comment]
If I mess with it enough I can still get it to happen

**Comment by dkent600** [comment]
Another issue that is easier to reproduce:

In staging,

1. go to the AllDaos page, fresh
1. don't scroll down
1. type to filter on "Buffi"

Result:
Nothing happens

Expect:
Should see the BuffiDaos

**Comment by tibetsprague** [comment]
hmm yeah thats trickier, having the search access the server... I guess I can do that

**Comment by dkent600** [comment]
Maybe we can just disable the filter until all the daos have appeared, and always fetch all the daos on page load?

**Comment by tibetsprague** [comment]
we cant fetch all DAOs, the subgraph seems to limit fetching to 100. also I dont think we would want to load more than 100 at a time. so we have to do server side searching if we want it to work right

**Comment by dkent600** [comment]
I was imagining automatically fetching one page at a time until there is nothing left to fetch, _as if_ the user were scrolling down.

**Comment by tibetsprague** [comment]
that could work...
