### ISSUE TITLE
Get test working for bounty integration

### ISSUE THREAD

**Issue by tibetsprague** [daostack/alchemy#1502]
The new bounty feature doesn't have a working integration test, it is currently commented out. Let us get a basic one that tests the most important functionality working

**Comment by tibetsprague** [comment]
@edsonayllon would you be down to take this on?

**Comment by edsonayllon** [comment]
So, I made the integration test currently commented out. For it to work, the [Standard Bounties](https://github.com/Bounties-Network/StandardBounties) contract would need to be added to ganache from what I understand, as tests are done through ganache. I didn't know the process for that within Alchemy, so I couldn't complete it. I remember @jellegerbrandy stating he was willing to fix testing when he was available. I would contact him for more context.

**Comment by edsonayllon** [comment]
Also, there's another missing feature that would help user experience in the Standard Bounties scheme. I can make a new issue for that.

**Comment by jellegerbrandy** [comment]
Hi @edsonayllon sorry for the late reply

1. Can you link to the test that is commented out so I can see what it does. I am assumig they do not really depend on having the bounty contracts deployed, but just to have a Generic Action in place.
2. The thing to do would be to create a new test_env release with a DAO called (say) "Bounty DAO", in the same spririt as the "dutchX dao" that is created here: https://github.com/daostack/test_env/blob/master/deployEthereum.js#L85

If you feel up to it/have time/have enough info, you can create a PR in test_env..
