### ISSUE TITLE
tokens list should not overflow the space in the sidebar

### ISSUE THREAD

**Issue by dkent600** [daostack/alchemy#1505]
This is Genesis:

![image](https://user-images.githubusercontent.com/1821666/76557215-c00df680-6460-11ea-97db-2ff822a9f9de.png)

**Comment by tibetsprague** [comment]
what shall we do in this case? have a minimum height and add a scrollbar?

**Comment by dkent600** [comment]
maximum height and scrollbar seems simplest and easiest
