### ISSUE TITLE
Submit Proposal on ETHregistrar does not do anything

### ISSUE THREAD

**Issue by pimato** [daostack/alchemy#1507]
<img width="749" alt="Screenshot 2020-03-13 at 17 57 52" src="https://user-images.githubusercontent.com/5337809/76643287-0ba1cc80-6555-11ea-9900-28a492b92ae7.png">

nothing happens after clicking on submit proposal:

<img width="462" alt="Screenshot 2020-03-13 at 18 15 47" src="https://user-images.githubusercontent.com/5337809/76644130-b23a9d00-6556-11ea-8730-b90bfd1cbcdc.png">

**Comment by orenyodfat** [comment]
Are you using MetaMask ? 
I got the MM popup on my end . @pimato

**Comment by pimato** [comment]
worked!

**Comment by pimato** [comment]
Seems like it only works if I use `0` as token id. It does not work if I use`49995323467760481030863469747148008882800293023271997235971042985847959749287` which is the token id for dxoasis.eth.

**Comment by orenyodfat** [comment]
for some reason it works for <16 digit number. @tibetsprague ?
