### ISSUE TITLE
Error on viewing unsupported scheme 

### ISSUE THREAD

**Issue by EzraWeller** [daostack/alchemy#1518]
Related to #1517 
On rinkeby staging, when I click on the address of an unsupported scheme, I am getting this error:
![Annotation 2020-03-16 182537](https://user-images.githubusercontent.com/5414803/76804910-dba43480-67b3-11ea-8343-8baf80024b69.png)
![Annotation 2020-03-16 182536](https://user-images.githubusercontent.com/5414803/76804901-d8a94400-67b3-11ea-85aa-6dcb9c2ac50d.png)
Is this an issue with #1501 or am I misinterpreting what that was meant to change?

**Comment by tibetsprague** [comment]
good catch @EzraWeller somehow I didn't test with a scheme that has no name
