### ISSUE TITLE
View all redemptions error

### ISSUE THREAD

**Issue by EzraWeller** [daostack/alchemy#1519]
Related to release at #1517 
Getting an error on the redemption page on rinkeby staging:
![Redeem page error](https://user-images.githubusercontent.com/5414803/76806723-9c2c1700-67b8-11ea-90f0-11864ac459bb.png)
(clicked on "view all" from the redemption drop down)

**Comment by tibetsprague** [comment]
Oof, this is an issue on Rinkeby where it is looking for a proposal's DAO but we havent loaded all the DAOs because there are too many to load at once... so the dao state doesnt exist

**Comment by tibetsprague** [comment]
shouldnt block deploy though
