### ISSUE TITLE
Torus login doesn't let you switch accounts

### ISSUE THREAD

**Issue by EzraWeller** [daostack/alchemy#1540]
After logging in once with Torus on rinkeby (Chrome), I see no way to switch which Torus account I am logged in with (this is a problem in this case because the default account has no Eth/Rep/etc.).

Logging out and then logging back in just gives me the same default account, and even going to the Torus site, importing one of the test accounts using private key (which seems to work on that end) doesn't show up in Alchemy.

I hope this is a clear enough explanation--I wasn't able to take good screenshots of the mouseover information.

**Comment by dkent600** [comment]
This seems to be a limitation of Torus.  Will try to find out more.

**Comment by dkent600** [comment]
Currently there are only two ways to supposedly get this functionality:

1) enable the Torus module to automatically display a button in our GUI somewhere.  I assume we could write CSS to control it's position and appearance, but limited in position (like not in a dropdown menu).

2) write our own custom button that we could put anywhere (like in a menu) that would manually make the call into the Torus module to display the necessary GUI.

I have let Torus know that we would prefer that they manage this button themselves.
