### ISSUE TITLE
Redemption not showing in dropdown (rinkeby)

### ISSUE THREAD

**Issue by EzraWeller** [daostack/alchemy#1549]
After passing a proposal that granted only rep in a DAO I created using the DAOcreator, the proposal shows up as passed and redeemable in the history page, but not in the top bar (rinkeby, Mac, Chrome)

<img width="1328" alt="Redemption not showing up in top bar" src="https://user-images.githubusercontent.com/5414803/78030451-1ec3e300-7330-11ea-9ac0-66895921cfac.png">

**Comment by tibetsprague** [comment]
should I work on this one?
