### ISSUE TITLE
Torus login requires extra clicks

### ISSUE THREAD

**Issue by EzraWeller** [daostack/alchemy#1550]
When logging in with Torus, the current flow goes like this:
1. Click login
1. Click Torus from the menu
1. Click "Login with gmail" or similar option in the Torus popup
1. After successfully doing that, you're now back at Alchemy and the menu of logins is still there
1. Click away from that menu, and Alchemy is still showing that you are not logged in
1. Click login again, and your Torus account appears

Ideally, we should take people directly from 3 to 6: once you login in the Torus popup, you go directly back to Alchemy with the Torus account showing.

**Comment by dkent600** [comment]
Created a ticket on Web3Modal here:  https://github.com/Web3Modal/web3modal/issues/138
