### ISSUE TITLE
3box comment threads

### ISSUE THREAD

**Issue by orenyodfat** [daostack/alchemy#1553]
replace Discuss with 3box msging threads .
https://docs.3box.io/build/web-apps/messaging

"3box could be better because its decentralized and uses the same profile as everywhere in the app"

Re already Discuss msgs ,one option will be to leave a link to Discuss so users can reach out to see old discussions.
@EzraWeller your opinion please.

**Comment by tibetsprague** [comment]
@EzraWeller i can do this one next, but lets make a judgement call on whether to link to old Disqus conversation or just move on as a reset

**Comment by EzraWeller** [comment]
I can think of at least one example where people were using the Disqus on the DAO wall to link to onboarding docs for the DAO and that kind of thing. Losing this would only be annoying, though, and wouldn't actually lose that DAO any actual work.

If it's going to add significant work to keep the Disqus conversation histories, I don't think we should do it.

**Comment by tibetsprague** [comment]
@EzraWeller we could always copy those comments over from Disqus to 3box :)

**Comment by dkent600** [comment]
STEPS:

1. start not connected
1. go to Gustatory Engineering
1. connect
1. click in new comment input field and notice you can see your account's name
1. enter a comment
1. wait
1. see your new comment appear (along with others, which is another bug report)
1. go to Genesis Alpha
1. click in new comment input field

RESULT:
Notice you cannot see your account's name, only the address, even though nothing has changed with respect to the login.

**Comment by dkent600** [comment]
STEPS:

1. start not connected
2. go to Gustatory Engineering

RESULT:  you cannot see your comments.  

3. connect

RESULT:  you still cannot see your comments.  Your won't be able to see any comments unless you try to enter a new one.

**Comment by dkent600** [comment]
Now there is a problem compiling 3Box@1.21.0:  https://github.com/3box/3box-js/issues/889

**Comment by dkent600** [comment]
We are going to start from scratch using 3Box threads.

**Comment by dkent600** [comment]
blocked by: https://github.com/3box/3box-js/issues/891

**Comment by Theylon** [comment]
This feature should be added to arc 1
