### ISSUE TITLE
Error when resuming a DAOcreator session`Cannot read property 'returnValues' of undefined`

### ISSUE THREAD

**Issue by EzraWeller** [daostack/alchemy#1560]
To produce this, I starting creating a DAO (on xDai), added myself as a member, removed myself, then reloaded the page. A modal pops up asking if you want to resume with saved data. I clicked yes, finished the process, started deploying, and got this error:

<img width="800" alt="DAOcreator error" src="https://user-images.githubusercontent.com/5414803/78293170-246b2580-74f6-11ea-8a73-53bc5fc4ffae.png">

Edit: got the same error without restarting, in a fresh sessions. Might just be that DAOcreator doesn't work on xDAI.

**Comment by dOrgJelli** [comment]
Hey @EzraWeller, yes this is because DAOcreator doesn't work on xDAI. How importance is this currently? How should we prioritize this in your opinion?

**Comment by EzraWeller** [comment]
Not important, I don't think, wouldn't prioritize. I'm not aware of any current plans to use POA Alchemy on anything upcoming.
