### ISSUE TITLE
Confusing instruction: ">0 GEN on Pass to boost"

### ISSUE THREAD

**Issue by EzraWeller** [daostack/alchemy#1563]
This is confusing -- not sure what the ideal fix is. Maybe just display the threshold + 1 GEN (so this example would say ">1")? I know that's not technically correct, but that way the number we display is also the first integer that will boost the proposal.

<img width="1185" alt="Confusing predicting instruction" src="https://user-images.githubusercontent.com/5414803/78307441-e5e46380-7513-11ea-853f-9deabe166610.png">

**Comment by tibetsprague** [comment]
Well it could be 1+ (one or more). but actually .5 GEN would also boost it

**Comment by dkent600** [comment]
Logically, what is given is correct.  Any value > 0 will boost, including fractions between 0 and 1.  If there is a suggestion of a better wording, @EzraWeller feel free to reopen.
