### ISSUE TITLE
Alchemy UX patches

### ISSUE THREAD

**Issue by arsena21** [daostack/alchemy#1568]
See designs: https://www.figma.com/file/Pbaz3VRyAwvGRlrm0sIEdd/Alchemy-UX-Patches

**Comment by dkent600** [comment]
@arsena21 @EzraWeller this should be broken up into separate tickets, once for each desired bug fix/new feature, each containing a clear description of what is desired.  Thanks!

**Comment by EzraWeller** [comment]
Closing this so it can be split into separate issues.
