### ISSUE TITLE
Arc tests should be running against the latest version of Arc

### ISSUE THREAD

**Issue by dkent600** [daostack/alchemy#1572]
but they aren't, by a long shot, and it is not possible, possibly because of an issue with the migration test data.

See:  https://github.com/daostack/migration/issues/307

**Comment by dkent600** [comment]
Apparently fixed by:  https://github.com/daostack/migration/pull/308

**Comment by ben-kaufman** [comment]
Do you need a new subgraph release using the new migration?

**Comment by dkent600** [comment]
> Do you need a new subgraph release using the new migration?

Yes, thanks

**Comment by ben-kaufman** [comment]
Released `v39_2` of the subgraph.
