### ISSUE TITLE
Figure out why alchemy disconnects from subgraph after some amount of time

### ISSUE THREAD

**Issue by tibetsprague** [daostack/alchemy#1576]
@jellegerbrandy is there anything you can contribute to this, thanks?

According to @tibetsprague:

- it just happens after like 24 hours
- maybe the socket connection has a lifetime
- so that the server doesnt have to deal with a million sockets kept open in background tabs
- just leave the window open overnight

**Comment by roienatan** [comment]
Closing since subscriptions in Alchemy are deprecated and polling is used instead.
