### ISSUE TITLE
Member DAOs First on Alchemy Home Page

### ISSUE THREAD

**Issue by EzraWeller** [daostack/alchemy#1581]
Eric, Eylon, and I view this as a high priority for April. We are seeking feedback from the implementation team on the following plan:
## Summary
We think the main user story right now and in the near future that is relevant for Alchemy’s home page is a user coming to Alchemy to visit a specific DAO. Right now, they must sift through the feed and the searchable DAO list to find this DAO. Instead, we should just show them links to DAOs they are a member of directly.
## Product Design
Move the feed to its own tab or remove it completely (I am agnostic about this and open to feedback, but happy to make a call if no one has a strong opinion).

Create a new DAO list showing any DAOs the logged in user holds reputation in. Label this “Your DAOs.” This list should go above the current full, searchable list of DAOs (“All DAOs”).

**Comment by tibetsprague** [comment]
so im hearing two things here. make the All DAOS page the home page with member/following DAOs first. I think we can still keep the feed on its own page

**Comment by EzraWeller** [comment]
Yep. The All DAOs section is already on the current home page, right? Just want to make sure we're referring to the same page.

**Comment by tibetsprague** [comment]
only if you have never logged in. once logged in once then everytime you come back the feed is the home page and you have to click on All DAOs to see them

**Comment by EzraWeller** [comment]
I see. Yes, it seems easiest to just make the All DAOs page the home page with a new list of "Your DAOs" coming at the top, in that case.
