### ISSUE TITLE
Mocked Add/Edit Plugin Buttons

### ISSUE THREAD

**Issue by EzraWeller** [daostack/alchemy#1582]
Eric, Eylon, and I view this as a high priority for April. We are seeking feedback from the implementation team on the following plan:
## Summary
The Scheme Registrar / Plugin Editor’s abilities to Add or Edit plugins are effectively unusable right now, since they expect users to do many steps outside of Alchemy, steps which are not clearly explained.

First, we suggest changing the UI for a new Scheme Manager proposal so that the “Add plugin” and “Edit plugin” options suggest users should contact us for help.

Second, we suggest adding some mock “Add a Plugin” and “Edit Plugin” buttons on the All Plugins page and the Information page of each plugin. These buttons bring up the Scheme Manager new proposal modal, navigated to the appropriate tab. 

Implementing this will mean we need to field these requests for adding or editing plugins from users.
## User Stories
This change affects any user that needs to add or edit a plugin. The existing flows have recently caused confusion or hold ups for 1up DAO, dxDAO, and the CO2ken DAO, for example. This flow would clarify that the path for DAOs to add or edit plugins is really just to coordinate with us: clarifying that should improve the experience greatly for users.
## Product Design
See mocks here: https://www.figma.com/file/Pbaz3VRyAwvGRlrm0sIEdd/Alchemy-UX-Patches?node-id=0%3A1
## Functional Spec
“Scheme Manager” should be renamed to “Plugin Manager.”

The new proposal modal for the Plugin Manager, “Add Plugin” tab, should be replaced with a design similar to the mock, with this copy:
> “You’ll soon be able to add plugins from this interface. Stay tuned!

> For now, please contact us at email@email.com to get one of the following plugins added to your DAO, or to add a new custom plugin of your own creation.

> Available Plugins
> Funding and Voting Power - explanation
> Plugin Manager - explanation
> ...

> [Show proposal form button]” (Button should be a toggle to show the existing proposal form below)

The new proposal modal for the Plugin Manager, “Edit Plugin” tab, should be replaced with a design similar to the mock, with this copy:
> “You’ll soon be able to edit plugins from this interface. Stay tuned!

> For now, please contact us at email@email.com to get help editing the parameters of this plugin.

> [Show proposal form button]” (Button should be a toggle to show the existing proposal form below)

The “All Plugins” page on each DAO should have an “Add a Plugin” button. This button brings up the new proposal modal at the “Add Plugin” tab (outlined above).

The “Information” tab on each DAO should its new proposal button replaced by an “Edit Plugin” button. This button brings up the new proposal modal at the “Edit Plugin” tab (outlined above).

## Needs
Someone who can field requests to add or edit plugins for DAOs and an email to reach them at.

A list of all the plugins we are okay adding to DAOs, so I can write descriptions for each of them.

**Comment by orenyodfat** [comment]
> Someone who can field requests to add or edit plugins for DAOs and an email to reach them at.

can be an issue in alchemy repo labeled "NEW PLUGIN".

**Comment by tibetsprague** [comment]
@EzraWeller @orenyodfat should i work on this one next? more important than the 3box comments?

**Comment by EzraWeller** [comment]
I think this is more important than 3box comments.

**Comment by tibetsprague** [comment]
i think the [Show proposal form button] button should say something like "Add a custom plugin yourself", or "Advanced: add a custom plugin"

**Comment by tibetsprague** [comment]
also "You’ll soon be able to add plugins from this interface. Stay tuned!" is not quite right since you can in theory add one yourself. maybe "We are working to make the process of adding plugins much easier to do yourself. For now it is best to contact us..." thoughts?

**Comment by EzraWeller** [comment]
Yes to both of those!

**Comment by tibetsprague** [comment]
i assume we only want to show the Add a Plugin button if the DAO has a PluginManager? Otherwise it would make no sense

**Comment by arsena21** [comment]
@EzraWeller @tibetsprague I think we need more plugin information to be displayed. here is my list: https://docs.google.com/spreadsheets/d/1MpKMqOoCFYz9rNJWCY0w3lkEcrhfVGy4seclZnpI09Y/edit#gid=0

**Comment by EzraWeller** [comment]
@tibetsprague This mock should be up to date now: https://www.figma.com/file/Pbaz3VRyAwvGRlrm0sIEdd/Alchemy-UX-Patches?node-id=0%3A1
Let me know if something is still missing.

Re: this question
> i assume we only want to show the Add a Plugin button if the DAO has a PluginManager? And an active one at that. Otherwise it would make no sense
If a DAO has no plugin manager, is it possible to edit or change the plugins? If so, I think we can still display the button. If not, then, yeah, we shouldn't show it.

Can we also commit to changing scheme --> plugin everywhere in the UI? It seems like we're using both right now.
