### ISSUE TITLE
does indexing 3box profile data might be helpful for alchemy ?

### ISSUE THREAD

**Issue by orenyodfat** [daostack/alchemy#1583]
3Box has become a popular solution for integrating user profiles into dApps. Starting with latest graph release , it is possible to fetch profile data for Ethereum addresses and DIDs.

**Comment by tibetsprague** [comment]
That would be so great! Then we don’t have to make a million calls to the 3box API. I’ll think about exactly what we need

**Comment by orenyodfat** [comment]
I think we can index the profile for each dao member .
the 3box profile is a json.
we can index the json profile as is ..at first phase..
so alchemy can parse it according to its need ..
(e.g profile.name ..) .
- we can get the profile from address or from DID (which I still do not know how to get that in the subgraph).

**Comment by tibetsprague** [comment]
that sounds ideal, each ReputationHolder could include its 3box profile with it. this should speed things up significantly in terms of loading the profiles

**Comment by dkent600** [comment]
Cannot be done yet in subgraph.  Closing for now.
