### ISSUE TITLE
does using full text search on daos via subgraph will improve alchemy search dao feature ? 

### ISSUE THREAD

**Issue by orenyodfat** [daostack/alchemy#1584]
see new full text search feature at  https://github.com/graphprotocol/graph-node/releases/tag/v0.18.0

**Comment by tibetsprague** [comment]
not sure. right now i am using name_contains to do the search. do we want the search to work across other DAO fields? @EzraWeller ?

**Comment by EzraWeller** [comment]
Don't think this needs to be a high priority.
