### ISSUE TITLE
Genesis Alpha is duplicated in DAO search

### ISSUE THREAD

**Issue by dkent600** [daostack/alchemy#1585]
Searching for Genesis Alpha. Once you search for it it never goes away. And if you search twice it always shows up twice. Three times... four....

**Comment by EzraWeller** [comment]
Still seeing this on rinkeby and mainnet. It seems to only effect the "Other DAOs" list and not "My DAOs"?

<img width="1009" alt="Duplications" src="https://user-images.githubusercontent.com/5414803/80136221-6a546000-856f-11ea-99e6-7f0dcf9976d6.png">
<img width="1023" alt="Duplications 2" src="https://user-images.githubusercontent.com/5414803/80136225-6aecf680-856f-11ea-9012-e165ff325bef.png">

**Comment by orenyodfat** [comment]
maybe clean your browsing cache.

**Comment by tibetsprague** [comment]
i do see it happen sometimes locally though too
