### ISSUE TITLE
Numbers off in redeem tooltip/modal

### ISSUE THREAD

**Issue by EzraWeller** [daostack/alchemy#1588]
I created a rinkeby proposal to give myself 10 Rep and 20 DAO tokens. Once passed, I see the following confusing numbers in the redeem tooltip:
<img width="392" alt="Numbers off in redeem tooltip" src="https://user-images.githubusercontent.com/5414803/79069779-f2e51d80-7c9e-11ea-9be9-f82627088dd1.png">

Here's another example on mainnet. The rep percentages don't match. It's possible these are separate issues--we can split this up if so:
<img width="328" alt="Percentages for rep don't match" src="https://user-images.githubusercontent.com/5414803/79069860-89b1da00-7c9f-11ea-9c3a-749f93a1c127.png">

**Comment by dkent600** [comment]
@EzraWeller can you please provide links to the pages?

**Comment by dkent600** [comment]
@EzraWeller Can you please precise which numbers are wrong and how?

**Comment by dkent600** [comment]
@EzraWeller  ?
