### ISSUE TITLE
out of memory building review app

### ISSUE THREAD

**Issue by dkent600** [daostack/alchemy#1591]
This has returned:

> FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory

This is happening in the current dev branch, thus we have no staging builds, and merging dev into any other branch will likely break their review apps too.  Like this one:

https://github.com/daostack/alchemy/tree/fixTorusDoubleClick

**Comment by orenyodfat** [comment]
this is  due to #1578 
please revert it back @dkent600

**Comment by dkent600** [comment]
@orenyodfat can you please report here what you did here with heroku to workaround this? thanks

**Comment by dkent600** [comment]
I got the slug size back down to 391M without seeing the out-of-memory error by playing with the app config variables:

> NODE_ENV staging
> NPM_CONFIG_PRODUCTION true

These are set for all 4 staging sites plus all review sites

**Comment by dkent600** [comment]
This continues to happen when we don't use the cheap-module-source-map

**Comment by roienatan** [comment]
Closing, looks like this problem was solved.
