### ISSUE TITLE
Handling generic ERC20 tokens in Alchemy

### ISSUE THREAD

**Issue by dtbx** [daostack/alchemy#1599]
**Handling generic or specific ERC20 tokens in Alchemy**

1. How can I enable a generic or otherwise a specific ERC20 owned by the DAO display the balance on Alchemy's front end?
Case in discussion is the CENNZ ERC20 tokens owned by CENNZnet Grants DAO (https://alchemy.daostack.io/dao/0xee7fa430a7e513d3df962ed0c0e285bc6f87fc24/scheme/0x797fa7c6259f1629ca0f1079849c6472359eb0b430c4155e77adb91a6f774b14/), you can view the token balance on Etherscan but not on Alchemy

2. Follow up Q, when a DAO owns generic ERC20 (in this case CENNZ), how can we enable rewards drop down menu to include this token?

Cheers @orenyodfat

**Comment by orenyodfat** [comment]
you are referring to CENNZ @ https://etherscan.io/token/0x1122b6a0e00dce0563082b6e2953f3a943855c1f . right ?

**Comment by dtbx** [comment]
Indeed

**Comment by tibetsprague** [comment]
@dtbx for now we can add this token to alchemy manually for you, we are working on a way for DAOs or individual users to display the tokens they care about

**Comment by dtbx** [comment]
That's great, thanks for helping out @tibetsprague

**Comment by tibetsprague** [comment]
@dtbx does this token exist on rinkeby too? im not finding it
