### ISSUE TITLE
Web3Provide HTTPS or WSS

### ISSUE THREAD

**Issue by orenyodfat** [daostack/alchemy#1604]
https://github.com/daostack/alchemy/blob/dev/src/settings.ts#L212 should it be https ? 
why it is wss ? does alchemy listen to web socket on infura ?

Does this is the reason ? : 
Http should not be used, when you don’t want the connection to be opened for a long time, whereas WebSocket can be used in that case. 

why on xdai it is http https://github.com/daostack/alchemy/blob/dev/src/settings.ts#L202 ?

**Comment by tibetsprague** [comment]
Line 211 is `graphqlSubscribeToQueries: false`, which line are you talking about?

**Comment by orenyodfat** [comment]
212

**Comment by dkent600** [comment]
wss is correct, I'm checking with @jellegerbrandy as to why xdai is different.

**Comment by dkent600** [comment]
@jellegerbrandy doesn't recall why the xdai settings are not consistent.  Seems to me they should both be wss.

**Comment by dkent600** [comment]
According to this, wss should work:  https://nodesmith.io/docs/#/overview/wssQuickstart
