### ISSUE TITLE
Cosmetic issues on landing page

### ISSUE THREAD

**Issue by EzraWeller** [daostack/alchemy#1623]
#1617 

A few cosmetic issues with the latest landing page:

<img width="1326" alt="Home page" src="https://user-images.githubusercontent.com/5414803/80134478-d08bb380-856c-11ea-8954-c42dbd3a8802.png">

**Comment by tibetsprague** [comment]
@EzraWeller I made the text big on purpose so its obvious, why do you think it should be smaller?
The Create a DAO button lining up with edge of DAO list is slightly tricky... I will try
