### ISSUE TITLE
persist DAO search filter value

### ISSUE THREAD

**Issue by dkent600** [daostack/alchemy#1624]
Would be great if we would persist the DAO search filter value. Currently I can click on a DAO, then click the back button and I have to start all over filter the DAOs list.  Same if I close the browser and come back, or refresh the page.

Would like to see this persisted in localStorage across sessions.

**Comment by tibetsprague** [comment]
That seems like a weird feature. Why would you want that? Where else have you seen that? One thing we could do is open the DAOs in a new tab, but that also seems weird.

**Comment by tibetsprague** [comment]
I would call that a filter, not a search. We could add ways to permanently filter the list. But again, I dont really understand a use case for that

**Comment by dkent600** [comment]
I gave use cases in the description.  One has to constantly redo one's DAO search (filter, whatever) when it is likely one will use the same search value every time.

**Comment by tibetsprague** [comment]
that is not a use case to me. when and why would you want to search for a dao, click on it, then go back and see the same search still present? most often I believe people would want the search cleared.

**Comment by tibetsprague** [comment]
you can follow a DAO if you want it to always appear at the top
