### ISSUE TITLE
Login should have a "loading" status and/or notification

### ISSUE THREAD

**Issue by EzraWeller** [daostack/alchemy#1627]
When you login with Torus and another external services (also found this with Portis & Fortmatic), it often takes a few second for your account to show up in the top right.

It can be confusing when you clicked login but now you're back looking at Alchemy without any change: I suggest that there should be something in the display to show that we are waiting for the connection (maybe a repeating notification?), and then a notification when the connection is finished (i.e. when the account appears in the top right).

**Comment by dkent600** [comment]
Indeed.  Tor.us is a particular example.
