### ISSUE TITLE
Voting percentages in History tab

### ISSUE THREAD

**Issue by EzraWeller** [daostack/alchemy#1628]
on #1617

Small visual bug here:

<img width="1078" alt="History" src="https://user-images.githubusercontent.com/5414803/80146872-8d3b4000-8580-11ea-8941-3c6ce4a41dd8.png">

**Comment by dkent600** [comment]
@EzraWeller I assume you are talking about the 0.00% text being doubled?

**Comment by dkent600** [comment]
@EzraWeller Could use a link to this page.  It is not happening where I'm looking.

**Comment by dkent600** [comment]
closing until I have a way to reproduce.  @EzraWeller

**Comment by dkent600** [comment]
reopening, found a repro case, though I'm still not sure of the required steps.

**Comment by dkent600** [comment]
OK, bingo, the repro case is anytime a proposal passes with 100% of the vote.  Should look like this:

![image](https://user-images.githubusercontent.com/1821666/83274464-dbed8280-a19b-11ea-9c1f-1a4e9da17ddf.png)
