### ISSUE TITLE
Visual bug for GEN in staking modal

### ISSUE THREAD

**Issue by EzraWeller** [daostack/alchemy#1629]
on #1617

GEN display box slightly broken (mainnet, 0.10.5 release):

<img width="1074" alt="Staking" src="https://user-images.githubusercontent.com/5414803/80147587-b6a89b80-8581-11ea-8219-34fb9498d39a.png">

**Comment by orenyodfat** [comment]
this issue is not fixed 

<img width="559" alt="Screen Shot 2020-06-03 at 8 39 56" src="https://user-images.githubusercontent.com/5994398/83599944-1e390a00-a576-11ea-955d-f826ba62f993.png">

**Comment by dkent600** [comment]
@orenyodfat Can you please provide a URL where this can be reproduced?  Works fine for me.

Also:  What browser are you using?

**Comment by EzraWeller** [comment]
Sounds like Oren is using Brave.

I'm seeing this in Chrome, but it's not the original issue:
<img width="1154" alt="Screen Shot 2020-06-03 at 12 19 36 PM" src="https://user-images.githubusercontent.com/5414803/83663181-826bc600-a596-11ea-9ea4-6f0232b98e01.png">

**Comment by orenyodfat** [comment]
I am using brave

**Comment by dkent600** [comment]
created a new ticket to represent the new behaviors and work flow to address them.

**Comment by dkent600** [comment]
@EzraWeller In you insufficient GEN error message bug, I am unable to reproduce the state of the "But GEN" text being wrapped underneath the input field.  Can you please give steps to repro?  Thanks.
