### ISSUE TITLE
Issues on mobile with "All DAOS" layouts and search box

### ISSUE THREAD

**Issue by arsena21** [daostack/alchemy#1640]
See images 

![8E53CC11-64E6-4C37-BE3E-79695619B815](https://user-images.githubusercontent.com/2105072/80433282-52e8e000-88ab-11ea-931d-bddd6fc9cb5a.png)
![7E8C9FBE-2D6A-4470-8858-066FAE823379](https://user-images.githubusercontent.com/2105072/80433286-54b2a380-88ab-11ea-82af-09111ce63514.png)

**Comment by arsena21** [comment]
In first drawing, search box is cut off when page loads.

Second is pic of dropdown...the breadcrumbs is layered in top

**Comment by dkent600** [comment]
Closely related:  https://github.com/daostack/alchemy/issues/1726
