### ISSUE TITLE
Expired proposals not getting cleared

### ISSUE THREAD

**Issue by EzraWeller** [daostack/alchemy#1642]
As of the submission of this ticket, there are 4 expired proposals in the dxDAO's "EthRegistrar" plugin that are not getting resolved: https://alchemy.daostack.io/dao/0x519b70055af55a007110b4ff99b0ea33071c720a/scheme/0x4665fbf4dbe10c598e21c41aaaf8eafddf2813c24390cac44d61edf07fa45153

**Comment by dkent600** [comment]
Whenever I've seen this it has been because the bot isn't working.

**Comment by orenyodfat** [comment]
was Bot issue .already been resolved
