### ISSUE TITLE
check  getCurrentBlock return value validity 

### ISSUE THREAD

**Issue by orenyodfat** [daostack/alchemy#1648]
[getCurrentBlock](https://github.com/daostack/alchemy/blob/dev/src/arc.ts#L54) might return null in some cases.
while using it there is a need to check for its return value.

especially [here](https://github.com/daostack/alchemy/blob/dev/src/lib/subgraphHelpers.ts#L84) 
if the return value is null , a special care must be taken . 
(This is the current case with Biconomy pr) .

**Comment by tibetsprague** [comment]
when you say a special care, do you mean we should still show the notification or not? it looks to me like there is a real error preventing access to the subgraph with Biconomy, in that case I think we want to know that and report that to the user

**Comment by dkent600** [comment]
An inability to use `getBlock` does not mean we can't access the subgraph.

**Comment by tibetsprague** [comment]
should we just remove the block check then in the subgraph warning code? or only use it if we get a block number
