### ISSUE TITLE
REP shouldn't be the same

### ISSUE THREAD

**Issue by perlmutterlabs** [daostack/alchemy#1653]
I suppose this is a pretty tricky bug, as the votes occurred in the same block, so REP is the same, but one should be lower by X%. From [this DAO](https://alchemy.daostack.io/dao/0x44d55a8492a90640dc6af013657eaf1ac5bc9548/scheme/0x06b3a64bdacf6fee2f8226a2c09340fb523a71ab960029232d3a05da5012c74b).
<img width="1164" alt="bugdaostack" src="https://user-images.githubusercontent.com/6537735/80925941-1b3ed400-8d94-11ea-9aba-852510ee182d.png">

**Comment by dkent600** [comment]
It is not feasible for us to distinguish voting times at any greater precision than the block creation time. Thus two votes in the same block are considered simultaneous.
