### ISSUE TITLE
view all 8 > ?? 

### ISSUE THREAD

**Issue by orenyodfat** [daostack/alchemy#1655]
<img width="1019" alt="Screen Shot 2020-05-04 at 17 59 17" src="https://user-images.githubusercontent.com/5994398/80980215-09f7d500-8e31-11ea-9c0d-bd3331720daa.png">

**Comment by dkent600** [comment]
@orenyodfat can you please provide a link to where this can be reproduced?  Thanks

**Comment by EzraWeller** [comment]
I'm still seeing this issue, unless I'm misunderstanding it:
<img width="513" alt="Screen Shot 2020-05-13 at 7 18 38 AM" src="https://user-images.githubusercontent.com/5414803/81806153-1394d300-94ea-11ea-8c07-7f059256e57c.png">

**Comment by dkent600** [comment]
@EzraWeller Since 15 === 3+4+8, this looks correct
