### ISSUE TITLE
After you clear cache, if you accept cookies... it asks you to exit page

### ISSUE THREAD

**Issue by arsena21** [daostack/alchemy#1659]
Pretty weird, after I clear my cache, I get the cookies notification. When I click it, it asks me if I am sure I want to leave the page:

![after clear cache](https://user-images.githubusercontent.com/2105072/81033376-497deb80-8e48-11ea-978a-ffb7d869f2ed.png)

![after click accept](https://user-images.githubusercontent.com/2105072/81033380-4edb3600-8e48-11ea-8243-c85e9f706c2b.png)

**Comment by arsena21** [comment]
Note, this was when I was trying to deploy a dao, but worth checking on other pages

**Comment by dkent600** [comment]
This is a dOrg issue, which I have created here:  https://github.com/dOrgTech/DAOcreator/issues/502
