### ISSUE TITLE
Resolve Heroku slug problem, upgrade 3Box

### ISSUE THREAD

**Issue by dkent600** [daostack/alchemy#1668]

**Comment by dkent600** [comment]
IPFS continues to be the big whale.

Relevant tickets:

3box:
https://github.com/3box/3box-js/issues/762

Orbit-Db:
https://github.com/orbitdb/orbit-db/pull/767

IPFS:
https://github.com/ipfs/js-ipfs/issues/2986

**Comment by orenyodfat** [comment]
I think figure out how to use NPM_CONFIG_PRODUCTION is the key for the slug size issue.

**Comment by dkent600** [comment]
orbitdb has a new release:  https://github.com/orbitdb/orbit-db/releases/tag/0.24.1

so we're now waiting for 3box

**Comment by dkent600** [comment]
Looks like this may be fixed!  https://github.com/3box/3box-js/issues/762#issuecomment-644887249

**Comment by dkent600** [comment]
fixed for 2.0
