### ISSUE TITLE
All proposals with recipients should auto-fill the current provider address

### ISSUE THREAD

**Issue by EzraWeller** [daostack/alchemy#1675]
When submitting a proposal, the `recipient` field should default to the address the current user is logged in with.

The fact that it doesn't do this now is slightly annoying and also makes it hard to prefill proposals using URL params (something that is quite useful for a number of use-cases). 

Any reason not to do this?

**Comment by dkent600** [comment]
Reason not to do this:  It is error prone, with potentially significant ramifications.  The user may believe they've completed the form when in fact they haven't, in the case where the beneficiary is meant to be someone other than themselves.

As an alternative, what I have always wanted:  a simple button next to the text field that when pressed copies the user's account into the text field.

I don't understand why we don't already prefill with whatever is the given beneficiary address.  But I don't really know about that feature at all.

**Comment by EzraWeller** [comment]
Ah, actually, I don't think this helps the thing I was imagining that much either, because to auto-fill it from a URL, you would the person to be logged in somehow anyway... closing.
