### ISSUE TITLE
Competition proposal modal display #0.10.6

### ISSUE THREAD

**Issue by EzraWeller** [daostack/alchemy#1676]
Needed for #1663 

I think something has gone wrong with the "new competition proposal" modal:
<img width="810" alt="Screen Shot 2020-05-06 at 4 00 37 PM" src="https://user-images.githubusercontent.com/5414803/81222765-d0e76e00-8fb2-11ea-83bd-2ccc7fcdedd4.png">
(Chrome, Mac)
This is a blocking issue and should be fixed before release, I think.

**Comment by dkent600** [comment]
This was broken by https://github.com/daostack/alchemy/pull/1598

**Comment by orenyodfat** [comment]
whats the fix ?

**Comment by dkent600** [comment]
Wouldn't be surprised  if it has broken the ReputationFromToken popup too.

**Comment by dkent600** [comment]
closed by #1677
