### ISSUE TITLE
Torus login requires doing the process twice

### ISSUE THREAD

**Issue by Theylon** [daostack/alchemy#1680]
Theres a bug forcing the user to do this process twice in order to be logged in to the account, easily 
Login -> Tor.us -> choose provider -> login with the provider.

Can check it out here: https://alchemy-staging-xdai.herokuapp.com/

**Comment by dkent600** [comment]
@Theylon I haven't been able to reproduce this.  Can you give more precise steps to reproduce and describe what is happening?

**Comment by EzraWeller** [comment]
I don't know about twice, but the issue I am still getting with Torus is that after I login, the Torus pop up does not disappear, it just stays on the screen until I find the nearly invisible "X" to close the pop up, which "feels" wrong.

**Comment by dkent600** [comment]
I can't reproduce this.  @EzraWeller
