### ISSUE TITLE
Create proposal TX failed with torus on xDAI staging

### ISSUE THREAD

**Issue by Theylon** [daostack/alchemy#1692]
Related to this PR https://github.com/daostack/alchemy/pull/1690

Getting an error code when trying to submit a proposal using Tor.us on xDAI staging (Regular xDAI deployment does doesn't have the tor.us deployment yet) 
https://alchemy-staging-xdai.herokuapp.com/dao/0x804dbac130778ec5b769115dc6bea9ff85237a07/scheme/0xd8f1f57bbc83b88cef92e19fd16b97606376c13813caeaa4c56a7194355ea9b4

instrument.ts:129 Create proposal: transaction failed :-( - Error: Chain with ID 100 not supported

**Comment by orenyodfat** [comment]
looks like torus issue https://github.com/torusresearch/torus-website/pull/1077

**Comment by Theylon** [comment]
This has been resolved: https://github.com/torusresearch/torus-website/pull/1077
