### ISSUE TITLE
Update DAO Home page for Avatar: 0xfaf05fedf06cac499b899d6a2052f23ae239b29d

### ISSUE THREAD

**Issue by Theylon** [daostack/alchemy#1693]
Welcome to the Builder Collective digital co-op
Our first event is the [SoS Hackathon](https://soshackathon.com/): Fund your ideas and solutions to heal the world in crisis.

- Register for the hackathon [here](https://bit.ly/GlobalSOSRegistration)
- Create an onboarding proposal for the cooperative [here](https://alchemy-staging-xdai.herokuapp.com/dao/0xfaf05fedf06cac499b899d6a2052f23ae239b29d/scheme/0xd4b6ee901566c88f942c2a04803f65cb7a554d8bc9a8f4fb5ded5cd012ca0897/proposals/create/?beneficiary=&description=This]https://alchemy-staging-xdai.herokuapp.com/dao/0xfaf05fedf06cac499b899d6a2052f23ae239b29d/scheme/0xd4b6ee901566c88f942c2a04803f65cb7a554d8bc9a8f4fb5ded5cd012ca0897/proposals/create/?beneficiary=&description=This is an introduction proposal to join the builder collective and SoS hackathon. Please fill out your name, Social Verification (link to twitter, github, etc), your skills, and what are you excited about:&ethReward=0&externalTokenAddress=0x543ff227f64aa17ea132bf9886cab5db55dcaddf&externalTokenReward=0&nativeTokenReward=0&reputationReward=50&title=Onboarding : <YOUR NAME>&url=&tags=[]).
- Join our Discord community for further discussions [https://discord.gg/rUr3rp7](https://discord.gg/rUr3rp7)

**Comment by orenyodfat** [comment]
@Theylon what this issue is about?
are you asking for a specific dao home page for a specific dao ?

**Comment by Theylon** [comment]
Yes this is for a specific DAO on xDAI
Avatar: 0xfaf05fedf06cac499b899d6a2052f23ae239b29d

After this is done, can I update it with a PR?

**Comment by dkent600** [comment]
@Theylon 

> After this is done, can I update it with a PR?

Don't understand, can you specify what you want?

**Comment by Theylon** [comment]
Hey @dkent600
This is the first iteration of this DAOs front page, I'm asking if I'd be able to update this copy later on with a PR.

**Comment by dkent600** [comment]
Ah, like submit your own PR, sure you can do that  :-)
