### ISSUE TITLE
DAO Home Page Discussion is showing the last discussion looked at instead of DAO Wall

### ISSUE THREAD

**Issue by EzraWeller** [daostack/alchemy#1701]
How to produce the bug:

Visit a proposal page with comments: https://alchemy.daostack.io/dao/0xe56b4d8d42b1c9ea7dda8a6950e3699755943de7/proposal/0x09a27194d2c153b10c31fcb0d7a6e1d3c66ae11a3823d0261a9569f56d4aab93

Visit the DAO home page of the same DAO: 
https://alchemy.daostack.io/dao/0xe56b4d8d42b1c9ea7dda8a6950e3699755943de7 (this should now show identical comments to the above)

Visit a proposal page with no comments in the same DAO:
https://alchemy.daostack.io/dao/0xe56b4d8d42b1c9ea7dda8a6950e3699755943de7/proposal/0xa42686fa8199265cf93fc57c0e9df82aeff4db7d94eef1ebe7aeffabd13a36a0 (should have no comments)

Visit the home page again:
https://alchemy.daostack.io/dao/0xe56b4d8d42b1c9ea7dda8a6950e3699755943de7 (should now show no comments)

The home page should instead show just one independent discussion (what used to be the DAO Wall).

**Comment by dkent600** [comment]
It's even worse.  If you go to another DAO != necDAO you still see the necDAO proposal comments.

**Comment by dkent600** [comment]
Problem is, I haven't been able to reproduce yet on staging.
