### ISSUE TITLE
Importing of JSON for DAO Creator is not working

### ISSUE THREAD

**Issue by arsena21** [daostack/alchemy#1703]
@orishim @dOrgJelli 

When you try to import a JSON via drag and drop, it opens the JSON, without importing it. If you try to use the button "import JSON file", nothing happens.... :S

**Comment by dOrgJelli** [comment]
Strange, can you send the JSON file that causes this to happen please @arsena21 ?

**Comment by dkent600** [comment]
Create a ticket in dorgTech: https://github.com/dOrgTech/DAOcreator/issues/500

**Comment by cbrzn** [comment]
@arsena21 can you please send the JSON that it's failing? I tried to replicate and it worked
