### ISSUE TITLE
Walletconnect broken in Ubuntu

### ISSUE THREAD

**Issue by EzraWeller** [daostack/alchemy#1710]
We received a support ticket claiming wallectconnect is broken in any browser in Ubuntu. I haven't tested this myself.

Ticket came from @cmagan

**Comment by cmagan** [comment]
It is pretty weird..
I was trying to use walltconnect on ubuntu without any success for the last two months (brave, chrome, firefox, opera). attaching a screenshot with the error notification in the bottom left.
Just now it suddenly worked on Ubuntu Brave but still the same issue on chrome. 
I really don't know what to make out of it but would love to supply more details if needed.
![image](https://user-images.githubusercontent.com/6940448/82095999-db1f1000-9708-11ea-9442-5c27be2a81e6.png)
