### ISSUE TITLE
Showing a redeem for author of an expired proposal?

### ISSUE THREAD

**Issue by EzraWeller** [daostack/alchemy#1711]
From a zendesk ticket:
```
1. Alchemy shows me I have REP to redeem (red dot on the star).
2. I click it.
3. It shows me one thing to redeem.
4. I redeem it, via metamask, and get the confirmation.
5. The star still has the red dot and still says it's there to redeem.

Here are 2 instances of me redeeming the same thing:

https://etherscan.io/tx/0x2f34eb33ea04311a7e497192803f9760f8ded5206b51915e39286f9f28f26809

https://etherscan.io/tx/0x71e10a4175d3d6f23bf3507db4006d3b321df5765d343a458811fcf316251073

Why does it still think I need to redeem? Have I actually redeemed that REP?
```
<img width="375" alt="Screen Shot 2020-05-15 at 10 20 55 AM" src="https://user-images.githubusercontent.com/5414803/82060792-d705da80-9695-11ea-9655-8987f0700f07.png">
<img width="1059" alt="Screen Shot 2020-05-15 at 10 21 11 AM" src="https://user-images.githubusercontent.com/5414803/82060800-da996180-9695-11ea-988c-63a3acaf03b1.png">

**Comment by dkent600** [comment]
I wonder if something like this may have been happening with hover:

![image](https://user-images.githubusercontent.com/1821666/82612349-abe92280-9b90-11ea-8a36-313b9c032f63.png)

**Comment by dkent600** [comment]
A probably work-around would be to refresh the page to refresh the GUI.
