### ISSUE TITLE
Plugin Manager - proposal params hash should show the whole params hash

### ISSUE THREAD

**Issue by orenyodfat** [daostack/alchemy#1715]
Currently it show part of that.
It will be nice to enable a button to copy paste it.

<img width="726" alt="Screen Shot 2020-05-17 at 8 22 46" src="https://user-images.githubusercontent.com/5994398/82136538-bebdc900-9817-11ea-83fc-c27b9be29e09.png">

**Comment by dkent600** [comment]
It already has a copy button:  
![image](https://user-images.githubusercontent.com/1821666/82143526-91bae780-9812-11ea-877b-446f1155b60d.png)

**Comment by dkent600** [comment]
@orenyodfat Can you please paste a URL where this can be seen?

**Comment by orenyodfat** [comment]
> @orenyodfat Can you please paste a URL where this can be seen?

https://alchemy.daostack.io/dao/0xe56b4d8d42b1c9ea7dda8a6950e3699755943de7/proposal/0x607610b44d26a31765618b8baf17b5fa529fd849400470bf8f7dddf60a5b5ca3

**Comment by dkent600** [comment]
Seems there is a bug in the copy buttons that is preventing them from working

**Comment by dkent600** [comment]
@orenyodfat So the code is explicitly clipping to 44 characters, for some reason that was don't very intentionally, probably to improve the appearance.  Are you sure it isn't good enough here to keep the clipping and make the copy buttons work?

**Comment by orenyodfat** [comment]
Make the copy button works

**Comment by orenyodfat** [comment]
Make the copy button works . To copy all params hash
