### ISSUE TITLE
Plugin manager -Edit - wrong permission set for edit plugin manager .

### ISSUE THREAD

**Issue by orenyodfat** [daostack/alchemy#1716]

**Comment by dkent600** [comment]
@orenyodfat Can you please indicate what it *is* showing and a link where we can see it reproduced?

**Comment by orenyodfat** [comment]
> @orenyodfat Can you please indicate what it _is_ showing, what it _should_ be showing, and a link where we can see it reproduced?

- When Edit "Plugin Manager" (via "PlugIn manager") wrong permissions are set . this can be view in the proposal screen it self.
