### ISSUE TITLE
Remove "New Proposal" button for none supporting schemes.

### ISSUE THREAD

**Issue by orenyodfat** [daostack/alchemy#1720]

**Comment by dkent600** [comment]
@orenyodfat Can you please describe the motivation for this change?

**Comment by dkent600** [comment]
@orenyodfat I am assuming what you are asking for is that for schemes like these:

![image](https://user-images.githubusercontent.com/1821666/82243637-f149ed80-990d-11ea-8e7f-27f15304891b.png)

That when we click on one of those schemes to see the scheme details, that we eliminate this button:

![image](https://user-images.githubusercontent.com/1821666/82243764-20f8f580-990e-11ea-98b2-7d951f28ff64.png)
