### ISSUE TITLE
Torus login popup showing up in the background in test deployment

### ISSUE THREAD

**Issue by EzraWeller** [daostack/alchemy#1725]
Steps to recreate:

 - on this deployment: https://alchemy-staging-rinkeby.herokuapp.com/

 - Click login

 - Choose Torus

 - See something like this:
<img width="1349" alt="Screen Shot 2020-05-18 at 3 43 02 PM" src="https://user-images.githubusercontent.com/5414803/82254632-2f9cd800-9921-11ea-8147-420ae1656c1b.png">
<img width="1353" alt="Screen Shot 2020-05-18 at 4 02 55 PM" src="https://user-images.githubusercontent.com/5414803/82254637-30356e80-9921-11ea-99ef-6748ebe77aba.png">

**Comment by orenyodfat** [comment]
it can be reproduced at https://alchemy-staging-rinkeby.herokuapp.com/dao/0x3cdb39c1ca57c19a316dd2f5acf900705220c713/schemes/
