### ISSUE TITLE
Show "value" propose along with any generic scheme proposal.

### ISSUE THREAD

**Issue by orenyodfat** [daostack/alchemy#1732]
From @orenyodfat :

> when proposing to generic scheme you can also add value param to the proposal. this value eventualy send ether from the avatar along with the generic call
> we need to show this value .,.and maybe alert if this value is not 0, i mean color that in red

**Comment by dkent600** [comment]
@orenyodfat Need more precision about what you want here

**Comment by dkent600** [comment]
**Notes**

According to the code, when creating the proposals, for what it is worth:

1. with known schemes, `value` cannot be set by the user
2. with unknown schemes `value` **can** be set by the user

When displaying the proposal details, which I think is the more relevant thing here:

3. arc.js is not supplying the value of `value`.  It does appear, however, to be available from the subgraph.  Created this ticker on arc.js:  https://github.com/daostack/arc.js/issues/476

**Comment by dkent600** [comment]
**Notes**

According to the code, when creating the proposals, for what it is worth:

1. with known schemes, `value` cannot be set by the user
2. with unknown schemes `value` **can** be set by the user

When displaying the proposal details, which I think is the more relevant thing here:

3. arc.js is not supplying the value of `value`.  It does appear, however, to be available from the subgraph.  Created this ticker on arc.js:  https://github.com/daostack/arc.js/issues/476

**Comment by orenyodfat** [comment]
https://github.com/daostack/arc.js/releases/tag/0.2.69

**Comment by orenyodfat** [comment]
here is a gs scheme with value = 1 . https://alchemy.daostack.io/dao/0x519b70055af55a007110b4ff99b0ea33071c720a/proposal/0x4d28e845a25f9b335aed4942067adb9ddffdb29364da04982233f538610c226a
