### ISSUE TITLE
scroll bar does not appears by default on proposal voters .

### ISSUE THREAD

**Issue by orenyodfat** [daostack/alchemy#1736]
does not show more than 10 voters
<img width="634" alt="Screen Shot 2020-05-21 at 12 10 25" src="https://user-images.githubusercontent.com/5994398/82543380-1f247180-9b5c-11ea-847e-d2f5401fc72c.png">

https://alchemy.daostack.io/dao/0x519b70055af55a007110b4ff99b0ea33071c720a/proposal/0x885f55a10766b364038ef41b49de17f2b1b8e7328e723cc6dbfd2dfb0d3fbb14

**Comment by dkent600** [comment]
Hmmm, it looks fine to me.  What browser are you using @orenyodfat 

![image](https://user-images.githubusercontent.com/1821666/82552856-ede27c00-9b30-11ea-930a-231af89270ff.png)

**Comment by orenyodfat** [comment]
Chrome and Safari

**Comment by orenyodfat** [comment]
ok. the issue is that the scroll bar does not appears by default.
you need to scroll it a bit to know that there is a scroll bar

**Comment by dkent600** [comment]
yeah, and only on your machine :-)  the scrollbar appears immediately for me.  Same for chrome and edge chromium.

**Comment by roienatan** [comment]
It's not about the browser, it's about the operating system. Windows shows the scroll bar by default while Macintosh hides the scroll bar if not scrolling.
