### ISSUE TITLE
genericScheme proposal value 

### ISSUE THREAD

**Issue by orenyodfat** [daostack/alchemy#1737]
re genericScheme proposal -- send eth  : when value is 0 it should also be mentioned in the card.
see the upper one.
https://alchemy-release-mainnet.herokuapp.com/dao/0x519b70055af55a007110b4ff99b0ea33071c720a/scheme/0xe61d663c6c64ef3177da998f2739c1c59f5bed63e3afdeeb12182a8920e4da76
<img width="484" alt="Screen Shot 2020-05-21 at 8 15 25" src="https://user-images.githubusercontent.com/5994398/82525908-46b71200-9b3b-11ea-9c89-9b3fe99b7195.png">

same is the proposal page : 
https://alchemy-release-mainnet.herokuapp.com/dao/0x519b70055af55a007110b4ff99b0ea33071c720a/proposal/0xd48831c3e9734642ef6f7bf211322c53b69066553ce6b960246f5acfac894f58

**Comment by dkent600** [comment]
Dup of https://github.com/daostack/alchemy/issues/1738
