### ISSUE TITLE
on proposal card, show `value` on GenericScheme proposals even when 0

### ISSUE THREAD

**Issue by dkent600** [daostack/alchemy#1738]

**Comment by dkent600** [comment]
@orenyodfat You gave as motivation for this:  "so the user will know what the proposal is about".
However, if we were to use the same reasoning for ContributionReward proposals, we would display all possible rewards, even when they are zero.

The point of this section of the proposal card is to display what _is_ happening, not to list things that are _not_ happening but could be.

cc: @EzraWeller

**Comment by orenyodfat** [comment]
> @orenyodfat You gave as motivation for this: "so the user will know what the proposal is about".
> However, if we were to use the same reasoning for ContributionReward proposals, we would display all possible rewards, even when they are zero.
> 
> The point of this section of the proposal card is to display what _is_ happening, not to list things that are _not_ happening but could be.
> 
> cc: @EzraWeller

we should do that for CR proposal as well

**Comment by dkent600** [comment]
To me that is going to add a whole lot of clutter to the page, at a time when we're trying to simplify things for users.  We need a motivation for this.

**Comment by dkent600** [comment]
Decided not to work this.  Not needed.
