### ISSUE TITLE
proposal plugins screen should show the 3 most advanced in time proposals.

### ISSUE THREAD

**Issue by orenyodfat** [daostack/alchemy#1739]
<img width="509" alt="Screen Shot 2020-05-21 at 14 42 44" src="https://user-images.githubusercontent.com/5994398/82556065-af20e600-9b71-11ea-82a8-8c6d3b2085e3.png">

https://alchemy.daostack.io/dao/0x519b70055af55a007110b4ff99b0ea33071c720a/schemes/
should be sorted according to boostedAt time value

**Comment by dkent600** [comment]
@orenyodfat we are currently displaying the first 3 proposals that are either boosted or in quiet ending period.  We are using the default sort order used by the subgraph when querying proposals on a given dao.id.
