### ISSUE TITLE
AlchemyExperimental - PluginManager (schemeFactory)

### ISSUE THREAD

**Issue by orenyodfat** [daostack/alchemy#1750]
- [x] GenericScheme : we should enable user to choose custom target address , even though there is no custom UI for that.

- [x] Competition : The proposal should say it is a competition (not CRExt ) 
<img width="620" alt="Screen Shot 2020-05-26 at 10 31 57" src="https://user-images.githubusercontent.com/5994398/82872794-325c8600-9f3c-11ea-8559-a3b5623b50af.png">

- [x] It will be nice to show the users the parameters the contract will be init with (not just the callData).

- [x] replace plugin : Why DAO factory appears on the list of plugins ?

**Comment by dOrgJelli** [comment]
- [ ] Add Plugin - missing parameters (for competition)

**Comment by dOrgJelli** [comment]
- [ ] ContributionRewardExt can have null rewarder (_daoFactory, _packageVersion, _rewarderName)

**Comment by dOrgJelli** [comment]
> Competition : The proposal should say it is a competition (not CRExt )

@orenyodfat, for this task, it requires decoding the initialize calldata. I've added it to the issue here: https://github.com/daostack/alchemy/issues/1770

**Comment by dOrgJelli** [comment]
> ContributionRewardExt can have null rewarder (_daoFactory, _packageVersion, _rewarderName)

@orenyodfat since this requires changes in arc.js, I've created an issue here for this: https://github.com/daostack/arc.js/issues/493

**Comment by orenyodfat** [comment]
> > ContributionRewardExt can have null rewarder (_daoFactory, _packageVersion, _rewarderName)
> 
> @orenyodfat since this requires changes in arc.js, I've created an issue here for this: [daostack/arc.js#493](https://github.com/daostack/arc.js/issues/493)

how it related to arc.js ? the rewarder is part of the schemeData which is passed to schemeFactory,..no ? https://github.com/daostack/arc/blob/arc-factory/contracts/schemes/SchemeFactory.sol#L112

**Comment by dOrgJelli** [comment]
> > > ContributionRewardExt can have null rewarder (_daoFactory, _packageVersion, _rewarderName)
> > 
> > 
> > @orenyodfat since this requires changes in arc.js, I've created an issue here for this: [daostack/arc.js#493](https://github.com/daostack/arc.js/issues/493)
> 
> how it related to arc.js ? the rewarder is part of the schemeData which is passed to schemeFactory,..no ? https://github.com/daostack/arc/blob/arc-factory/contracts/schemes/SchemeFactory.sol#L112

This interface will need to change, and the `initializeParamsMap` will need to change as well:
https://github.com/daostack/arc.js/blob/651c298c46df6edcbc0d2148244700ad15652d0c/src/plugins/contributionRewardExt/plugin.ts#L40

**Comment by orenyodfat** [comment]
> > > > ContributionRewardExt can have null rewarder (_daoFactory, _packageVersion, _rewarderName)
> > > 
> > > 
> > > @orenyodfat since this requires changes in arc.js, I've created an issue here for this: [daostack/arc.js#493](https://github.com/daostack/arc.js/issues/493)
> > 
> > 
> > how it related to arc.js ? the rewarder is part of the schemeData which is passed to schemeFactory,..no ? https://github.com/daostack/arc/blob/arc-factory/contracts/schemes/SchemeFactory.sol#L112
> 
> This interface will need to change, and the `initializeParamsMap` will need to change as well:
> https://github.com/daostack/arc.js/blob/651c298c46df6edcbc0d2148244700ad15652d0c/src/plugins/contributionRewardExt/plugin.ts#L40

does passing a rewarded as 0x0000000000000000000000000000000000000000000000000000000000000000 will not work as is ?
@dOrgJelli
