### ISSUE TITLE
AlchemyExp :DAOCreator

### ISSUE THREAD

**Issue by orenyodfat** [daostack/alchemy#1751]
- [ ] creating a dao lead to
<img width="635" alt="Screen Shot 2020-05-26 at 10 47 42" src="https://user-images.githubusercontent.com/5994398/82874271-5ae57f80-9f3e-11ea-9e6e-1bf2999c87bf.png">

This is because the link (alchemy url) from the daocreator is wrong. 
 https://alchemy-staging-rinkeby.herokuapp.com/dao/0xF2A851Fc98Fb678C6a24b37E3468aEB8cA1eBAaC

it should be the same link as the current alchemy 
https://alchemy-alchemy-experim-xsdzlc.herokuapp.com/dao/0xf2a851fc98fb678c6a24b37e3468aeb8ca1ebaac/plugins/

**Comment by dkent600** [comment]
Should this ticket be created in dOrgTech?    https://github.com/dOrgTech/DAOcreator
