### ISSUE TITLE
GenericSchemeRegistry : support different plugin names(aliases) for different target contracts using the same ui components. 

### ISSUE THREAD

**Issue by orenyodfat** [daostack/alchemy#1766]
The situation currently that a DAO might have multiple genericSchemes using the same UI , which might confuse the user. 
see for example ENSPublicResolver at https://alchemy.daostack.io/dao/0x519b70055af55a007110b4ff99b0ea33071c720a/schemes/ 

To make this a generic solution , there are 2 options : 
1. map an optional "alias" for each address. This `alias` if exist will be used as the Plugin name in the UI.
something like adding "aliases" entity to the generic scheme registry json.
for example : 
`
 {
  "name": "EnsPublicResolver",
  "addresses": {
    "main": [
      "0x4976fb03c32e5b8cfe2b6ccb31c09ba78ebaba41",
      "0x1da022710df5002339274aadee8d58218e9d6ab5",
      "0x226159d592e2b063810a10ebf6dcbada94ed68b8"
    ],
 },`
`"aliases":{
  {"0x4976fb03c32e5b8cfe2b6ccb31c09ba78ebaba41","NewENSPublicResolver"},
  {"0x226159d592e2b063810a10ebf6dcbada94ed68b8","OldENSPublicResolver"}
},
...
`
2. Fetch the alias name of the plugin from the subgraph in real time. this is indexed at the contractInfo . https://github.com/daostack/subgraph/blob/master/daos/mainnet/dxdao.json#L40  

I feel that option 2 is preferable as this is the original intention of the "alias" in the contractInfo subgraph, it is already there.. and it will make alchemy more generic. 
@dkent600 , thoughts ?

**Comment by dkent600** [comment]
Yeah, option 2 makes sense except for the fact that I still don't understand why the subgraph is maintaining a list of registered contracts per DAO in the first place.

**Comment by dkent600** [comment]
Awaiting arc.js PR:  https://github.com/daostack/arc.js/pull/492
