### ISSUE TITLE
Support button should be smaller on mobile

### ISSUE THREAD

**Issue by dkent600** [daostack/alchemy#1774]
![image](https://user-images.githubusercontent.com/1821666/83256231-11847280-a180-11ea-94ae-1ea0a947d315.png)

**Comment by dkent600** [comment]
The button appears to be initialized here:  https://github.com/daostack/alchemy/blob/cce03d75d9f1abc0c4d6e0f39ce14f8c8c15f128/src/index.html#L46

but the button styles appear to be coming from the zendesk server.

**Comment by roienatan** [comment]
> The button appears to be initialized here:
> 
> https://github.com/daostack/alchemy/blob/cce03d75d9f1abc0c4d6e0f39ce14f8c8c15f128/src/index.html#L46
> 
> but the button styles appear to be coming from the zendesk server to which I have no access.

Looks like the settings in the zedesk server are very limited. You can see here the right way to customize the button:
https://developer.zendesk.com/embeddables/docs/widget/settings
But I think there is no option there to change the size of the button. I'm trying to customize the button for this issue https://github.com/daostack/alchemy/issues/1940. My conclusion until now is that the best would be to create our "Support" button in the sidebar and just trigger the opening of the popup. With that way we can control the button as much as we like. I'm trying to figure out if it's possible.
