### ISSUE TITLE
Cannot see proposal 

### ISSUE THREAD

**Issue by orenyodfat** [daostack/alchemy#1795]
http://alchemy.daostack.io/dao/0x519b70055af55a007110b4ff99b0ea33071c720a/proposal/0x439d54386a46c13b828d896def2124f524c59129a6ac633990ee4e4fd55873df

**Comment by dkent600** [comment]
Workaround, you can see it if you zoom out far enough:

![image](https://user-images.githubusercontent.com/1821666/83734203-aeca2580-a61c-11ea-927a-8b0a894fc082.png)

**Comment by orenyodfat** [comment]
lets fix that.
limit the value length to 64 chars and enable "copy to clipboard" on that .
