### ISSUE TITLE
account profile popup should always be fully visible

### ISSUE THREAD

**Issue by dkent600** [daostack/alchemy#1805]
On Scheme Proposal cards in the left column:

![image](https://user-images.githubusercontent.com/1821666/83900076-7cf1b580-a727-11ea-829f-892ff45958c7.png)

Should look something more like this:

![image](https://user-images.githubusercontent.com/1821666/83900145-98f55700-a727-11ea-9cf8-d03caeae7489.png)

The problem is even worse on mobile.

![image](https://user-images.githubusercontent.com/1821666/83900203-b6c2bc00-a727-11ea-9724-7515e8b8e486.png)

On the proposal details page:

![image](https://user-images.githubusercontent.com/1821666/83901140-45cfd400-a728-11ea-99a1-6e965ba19aa2.png)

This is not an exhaustive search... dev can possibly find more...

**Comment by roienatan** [comment]
Solved in https://github.com/daostack/alchemy/pull/2340
