### ISSUE TITLE
Side bar menu cutoff on DAO pages

### ISSUE THREAD

**Issue by EzraWeller** [daostack/alchemy#1819]
In chrome, release 0.10.10, I am getting the bottom left sidebar cutoff on most DAO pages (it's unscrollable):

<img width="276" alt="Screen Shot 2020-06-12 at 7 05 21 AM" src="https://user-images.githubusercontent.com/5414803/84496623-4235d300-ac7b-11ea-84c9-e7844d5b6b2b.png">

Let's fix this for the next release.

**Comment by dkent600** [comment]
> In chrome, release 0.10.10, I am getting the bottom left sidebar 

@EzraWeller I am not seeing that.  Can you please give more details?  Which DAO, which website, size of the browser window, exactly what page you are on, any other repro steps?  Thanks

**Comment by EzraWeller** [comment]
I am seeing it mainnet and rinkey, in every DAO I've checked, in windowed Chrome only, browser window taking up almost entirety of screen. Not sure what Ctrl-F5 is supposed to do, but I don't see it doing anything. Hope that helps some.

**Comment by dkent600** [comment]
What is your zoom level?

**Comment by dkent600** [comment]
Can you please also send a screenshot of Chrome Help => About Google Chrome, like this:

![image](https://user-images.githubusercontent.com/1821666/84500069-d0ad5300-ac81-11ea-94f6-43ea5ec1783c.png)
