### ISSUE TITLE
Strange behavior in redeem drop down w/ only 1 redeem

### ISSUE THREAD

**Issue by EzraWeller** [daostack/alchemy#1820]
On rinkeby, release 0.10.10, this is what I get clicking the redeem drop down:

<img width="322" alt="Screen Shot 2020-06-12 at 7 10 51 AM" src="https://user-images.githubusercontent.com/5414803/84497067-17984a00-ac7c-11ea-86cf-f4cf380ff91b.png">

(this is a redeem for 1 Rep, which is why it's rounding to 0.00%)

1. There's no redeem button
2. When I hover over my account, it gets cutoff where the redeem box ends.
3. Lots of extra space, probably shouldn't be there.

**Comment by dkent600** [comment]
@EzraWeller I am not seeing this.  I'm afraid I'm going to need more specifics on how to reproduce.

**Comment by EzraWeller** [comment]
Hmm, it's an old proposal I made on rinkeby, where the only reward was giving myself 1 rep. It's also the only current active redemption on rinkey, so that could be part of it. The proposal was in Genesis Alpha. In Chrome on a mac. Anything else I can add?

**Comment by dkent600** [comment]
Is this the only case where you see the problem?  What about other accounts?  What happens if in this account you create and pass another proposal, to make two of them?

**Comment by dkent600** [comment]
BTW, there are plenty of other redemptions in other accounts:

![image](https://user-images.githubusercontent.com/1821666/84499180-09e4c380-ac80-11ea-953f-3a4ecdc94e1f.png)

**Comment by EzraWeller** [comment]
Not seeing the problem on another account (Torus):
<img width="372" alt="Screen Shot 2020-06-12 at 8 24 10 AM" src="https://user-images.githubusercontent.com/5414803/84502345-27b52700-ac86-11ea-9c27-0de52ee5835c.png">
So I'm really not sure what's going on here... the problem account is a metamask account, but I'm not seeing the redeem button disappear on any other account yet.

One thing is it seems I am only seeing redeems for the account I am logged in with -- is that intended?

**Comment by dkent600** [comment]
> One thing is it seems I am only seeing redeems for the account I am logged in with

I've been wondering about that too.  I'll investigate next week.
