### ISSUE TITLE
Activation Time should be UTC or local time?

### ISSUE THREAD

**Issue by roienatan** [daostack/alchemy#1831]
The question is related to the new PluginManger proposal UI in related to the activationTime the user should enter.

**Comment by orenyodfat** [comment]
@EzraWeller ?

**Comment by dkent600** [comment]
I assume you're talking about in the UI such as the Plugin Information tab.

The way this always gets settled is that we show the local date and time including the timezone and GMT offset.  We have this function for doing that:

https://github.com/daostack/alchemy/blob/4b298408938cff5998873e24b4644269337fd907/src/lib/util.ts#L505

**Comment by orenyodfat** [comment]
> I assume you're talking about in the UI such as the Plugin Information tab.
> 
> The way this always gets settled is that we show the local date and time including the timezone and GMT offset. We have this function for doing that:
> 
> https://github.com/daostack/alchemy/blob/4b298408938cff5998873e24b4644269337fd907/src/lib/util.ts#L505

Your assumption is wrong .
The question is related to the new PluginManger proposal UI in related to the activationTime the user should enter. I updated the description .

**Comment by dkent600** [comment]
@orenyodfat Can you please provide in this PR description the link to this "new PluginManger proposal"?

So suggest do this the same way, and using the same code, as we do when entering datetimes for Competition proposals, where we ask the user to supply the datetime in their local timezone.  This is users' easiest option.

See for example:  https://github.com/daostack/alchemy/blob/8b93faaad89b660b21b9bc69871d5be188845eec/src/components/Scheme/ContributionRewardExtRewarders/Competition/CreateProposal.tsx#L574
