### ISSUE TITLE
Alchemy Exp : Visula bug in GEN staking model

### ISSUE THREAD

**Issue by orenyodfat** [daostack/alchemy#1832]
see also https://github.com/daostack/alchemy/issues/1794

**Comment by dkent600** [comment]
Why are you creating a ticket here when this fix will be pulled in by merging from dev?  I think this should be fixed by doing that merge, and that we should strive to keep up with those merges.

**Comment by orenyodfat** [comment]
> Why are you creating a ticket here when this fix will be pulled in by merging from dev? I think this should be fixed by doing that merge, and that we should strive to keep up with those merges.

because it might be hard work to merge from dev .

**Comment by dkent600** [comment]
It *will* be hard work, and harder every week we wait.  And there are issues trying to duplicate code fixes individually, risky and redundant work.

**Comment by orenyodfat** [comment]
all good.
