### ISSUE TITLE
Add Competition(s) tab to the left sidebar 

### ISSUE THREAD

**Issue by Theylon** [daostack/alchemy#1855]
Add the competitions url (scheme/0x0xxxx/crx/) to the left sidebar, below the Home/proposals/members/history list

Competition (#numberOfLiveCompetitions (open, open for submissions, voting period))

Right now it's very difficult to understand where the live competitions are. 
This has been echoed repetitively from both within the DAOstack team and from external Alchemy users. The UX journey is simply too long and complex. 

I just got feedback after explaining someone how to get there in a video call. With 12h they asked me how to again, saying that is extremely counterintuitive.

We can use this icon 
https://upload.wikimedia.org/wikipedia/commons/8/82/SVG_Trophy_Star.svg

(++ I'm working on a concept for a full sidebar and less screens)

**Comment by dkent600** [comment]
The DAO sidebar can be cramped for vertical space when there are a lot of DAO tokens.  An alternative could be to put this link, with the benefit of including more explanatory information, in the DAO landing page.

**Comment by Theylon** [comment]
Hey guys, following up on this one. 

The logic would be, if the DAO has the competition scheme, the left sidebar would show the "live" competitions tab /crx. 
For now, if the DAO has a lot of tokens and sidebar is cramped, I see a scrollbar is added. 

The next step would be to remove much of what is going on on the bottom of the sidebar, mainly outdated linked.

**Comment by dkent600** [comment]
> For now, if the DAO has a lot of tokens and sidebar is cramped, I see a scrollbar is added.

What is the point of that observation?

> The next step would be to remove much of what is going on on the bottom of the sidebar, mainly outdated linked.

Can you please specify?

**Comment by dkent600** [comment]
> The DAO sidebar can be cramped for vertical space when there are a lot of DAO tokens. An alternative could be to put this link, with the benefit of including more explanatory information, in the DAO landing page. @Theylon can you please comment? Thanks

Any thoughts on this suggestions @Theylon?    Note we don't have to assume it is mutually-exclusive with the sidebar suggestion.

**Comment by Theylon** [comment]
This is not a good solution, the DAO landing page is not being used by any DAO. If it was populated with information it will probably not be the schemes of the DAO, but rather general information and how to get started. 

A recurring user of a specific DAO would like to have the shortest path to the relevant plugin, in the DXdao for example, most members bookmark the /schemes page and are a click away from all plugins. 

The intention is to do the same with the competition, the plugins page will show "competition proposals" and the sidebar will show "active / approved" competitions

**Comment by dkent600** [comment]
> the DAO landing page is not being used by any DAO.

Can you elaborate?  The truth is that every DAO has a landing page.  It is where you automatically go when you click on a DAO in the DAOs list page.

**Comment by dkent600** [comment]
> The intention is to do the same with the competition, the plugins page will show "competition proposals" and the sidebar will show "active / approved" competitions

> the plugins page will show "competition proposals" and the sidebar will show "active / approved" competitions

These are new details.  Can you please be specific about that you are describing here?

1) it

**Comment by Theylon** [comment]
> > the plugins page will show "competition proposals" and the sidebar will show "active / approved" competitions
> 
> These are new details. Can you please be specific about that you are describing here?

This is describing the original issue I opened:
Add the competitions url (scheme/0x0xxxx/crx/) to the left sidebar, below the Home/proposals/members/history list

**Comment by Theylon** [comment]
> > the DAO landing page is not being used by any DAO.
> 
> Can you elaborate? The truth is that every DAO has a landing page. It is where you automatically go when you click on a DAO in the DAOs list page. You can't see a DAO sidebar until you are in a DAO.

Why are you assuming users go to the DAO from alchemy.daostack.io? 
Like I said, virtually all DAOs (DXdao, NecDAO, dOrg) have the DAO proposals tab (0x...../schemes) bookmarked and that's how they get to it. 

The DAO homepage is simply not being used.

**Comment by dkent600** [comment]
> The DAO homepage is simply not being used.

Could be interesting to check our google analytics on this, where the actual stats are being recorded.

**Comment by Theylon** [comment]
@EzraWeller 

This is a low hanging fruit which i think should do asap -- competition is getting traction, both NecDAO and DXdao and the UX is impossible to understand at the moment
