### ISSUE TITLE
Zendesk request for DAO homepage change

### ISSUE THREAD

**Issue by EzraWeller** [daostack/alchemy#1858]
From zendesk:
```
Hi,

I would like to change the default description on the homepage of my DAO on Alchemy (on Rinkeby).
DAO - https://alchemy-staging-rinkeby.herokuapp.com/dao/0x9003196E314e03daE65f0bF26788befC714D68a1

Could you please modify the description to:
~~~~~
Welcome to The Venus Project DAO, a decentralized organization built on DAOstack.
This is a DAO for the purpose of exploring new governance models and platforms for www.thevenusproject.com
Visit the Proposals page to make a proposal to the DAO or vote on existing proposals.
~~~~~

Thanks
```

**Comment by orenyodfat** [comment]
We still do not have a generic solution for setting dao description. the DAO's header feature is still WIP. 
Till we will have a generic workable solution  , lets have an hard coded registry which map daos addresses to its description text. if such mapping does not exist , the "default" description will be used. lets start with this one.

**Comment by dkent600** [comment]
@EzraWeller Do you think they really want to display "www.thevenusproject.com", or rather "The Venus Project"?  (either way is easily presumed to be a link)
