### ISSUE TITLE
3Box issue with Ledger + Metamask [Zendesk]

### ISSUE THREAD

**Issue by EzraWeller** [daostack/alchemy#1859]
**Describe the bug**
>and second of all i cant change my profile i am using metamask and ledger and i get the following error
`FAILURE: Saving profile to 3box failed: An error occurred while publishing link:`

**To Reproduce**
(unknown and not high priority, but something we should look out for)

**Expected behavior**
New profile data is saved to 3box.

**Screenshots**
https://daostack.zendesk.com/attachments/token/At7gwzhNn7nd9JzJuHU91WOdV/?name=Unbenannt-1.png

**Comment by dkent600** [comment]
I just tried updating my profile in one account and it hung.  Tried from another account and it worked fine.  3Box is reporting "infrastructure" problems.
