### ISSUE TITLE
Can't Enable Predictions on xDAI

### ISSUE THREAD

**Issue by arsena21** [daostack/alchemy#1875]
**Describe the bug**
I am currently not able to enable predictions for this DAO: https://alchemy-xdai.daostack.io/dao/0xfff2b9bb869c7886a07c3105c7ed75fa48c4ff75

**To Reproduce**
From Eylon:
"There seems to be some inconsistency here, I’ve tried several times and I can’t reproduce the entire issue, but sometimes it allows me to stake and sometimes it doesn’t. After 5-6 refreshes, Hard reload, and different browsers I managed to get to the screen where I could stake on the proposal, but this is definitely broken somewhere"

**Expected behavior**

**Screenshots**
![image (34)](https://user-images.githubusercontent.com/2105072/85420972-be0c0700-b528-11ea-8330-cb6577ffaf65.png)
![image (33)](https://user-images.githubusercontent.com/2105072/85420986-bfd5ca80-b528-11ea-95fb-8c19531eea65.png)
![image (32)](https://user-images.githubusercontent.com/2105072/85420996-c2382480-b528-11ea-9bb2-0321688cd768.png)

**Optional: please provide the following if you find it relevant:**
I tried it on Chrome + Chrome incognito mode. It looks like Eylon tried on different browsers.

**Comment by dkent600** [comment]
@Theylon Can you specify on this "sometimes it allows me to stake and sometimes it doesn’t"?  What is actually happening?  Are there any console.log errors?

**Comment by dkent600** [comment]
This is not working because of this bug in arc.js:  https://github.com/daostack/arc.js/issues/499

I honestly don't know how anyone was able to get it to work unless somehow staking was able to work against the GEN token instead of xGEN.
