### ISSUE TITLE
Stalling transactions on xDai

### ISSUE THREAD

**Issue by EzraWeller** [daostack/alchemy#1896]
**Describe the bug**
When trying to submit proposals in a DAO on xDai, the transactions stall for as long as I was willing to wait. Metamask also seems to get "clogged up" and its entire UI slows down if too many stalled transactions are waiting in it, requiring you to "reset" your account (clear transaction history).

**To Reproduce**
1. Go to https://alchemy-staging-xdai.herokuapp.com/dao/0x2b0f5e7de201068d9fb917ab86dc1c731c274411/scheme/0xf6763096dc9fb62774db8c3de369320dd890388a8a060a28f7dadaa83624ae7a
2. Connect Metamask to xDai/POA network
3. Create and submit a new proposal
4. You should get a "confirmation pending" forever in metamask.

**Expected behavior**
The transaction should be confirmed within a second or two instead.

**Screenshots**
<img width="819" alt="Screen Shot 2020-06-26 at 8 02 08 AM" src="https://user-images.githubusercontent.com/5414803/85855034-8c42ac80-b783-11ea-94e0-48d98f5f9200.png">

**Optional: please provide the following if you find it relevant:**
 - OS: Mac OS 10.13.4
 - Browser Chrome 83.0.4103.116
 - Version 0.10.11 on xdai staging

**Comment by EzraWeller** [comment]
It looks like this might be what's happening here: 
```
Seems we are not the first to see this:  https://github.com/openethereum/openethereum/issues/9795 (edited) 

Ezra Weller:spiral_calendar_pad:  1 minute ago
Sounds like we should set a minimum in case it returns 0

dragonfly  < 1 minute ago
makes sense
```

**Comment by dkent600** [comment]
According to https://blockscout.com/poa/xdai txs are going for free right now.  It is as yet a mystery why we can't.

**Comment by dkent600** [comment]
Guess:  Maybe these freeloaders are using a different node than we are, a node that enables these free transactions?  Whereas POA, that we are using, is not enabling them?  And MetaMask computes the gas price regardless, just looking at the most recent blocks.

**Comment by orenyodfat** [comment]
Nodesmith as a company is closed since December.  ... lets use other endpoint.

**Comment by orenyodfat** [comment]
cannot reproduce
