### ISSUE TITLE
Mobile friendliness

### ISSUE THREAD

**Issue by tsuberim** [daostack/alchemy#19]
currently the app doesn't behave well on small screens:

![screenshot from 2018-03-07 13-05-27](https://user-images.githubusercontent.com/33967618/37089162-528a8246-2208-11e8-8694-21d8e4361ea0.png)
![screenshot from 2018-03-07 12-58-22](https://user-images.githubusercontent.com/33967618/37088987-c4d0a5e8-2207-11e8-9506-8a0afc21739f.png)
![screenshot from 2018-03-07 13-03-19](https://user-images.githubusercontent.com/33967618/37089084-16b8566c-2208-11e8-9adf-3efbf9df6a30.png)

**Comment by tibetsprague** [comment]
yes we know, not a priority right now. remember that people will have to use cipher browser to have access to web3

**Comment by dev-matan-tsuberi** [comment]
of course, just putting it here for the future.

**Comment by tibetsprague** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Mobile support](https://trello.com/c/E6nRWr6A/126-mobile-support)

**Comment by jellegerbrandy** [comment]
closing this for its yearly anniversary
