### ISSUE TITLE
Show correct crypto wallet balances in xDAI

### ISSUE THREAD

**Issue by arsena21** [daostack/alchemy#1901]
Right now, the crypto held by a DAO doesn't show up on xDAI DAOs...

For example: https://alchemy-xdai.daostack.io/dao/0xfff2b9bb869c7886a07c3105c7ed75fa48c4ff75

This DAO has funds, as can be seen here: https://blockscout.com/poa/xdai/address/0xFff2B9bb869C7886A07c3105c7eD75FA48c4FF75/transactions

**Comment by dkent600** [comment]
Is also not showing an xDAI balance for my account, even though I have 1 xDAI.

**Comment by dkent600** [comment]
@arsena21 @EzraWeller @EzraWeller To your recollection, did this EVER work?

**Comment by arsena21** [comment]
No, I do not think it did, but I guess we probably need to start showing
balances if DAOs are starting to use xDAI

**Comment by orenyodfat** [comment]
replace replace https://github.com/daostack/alchemy/blob/dev/src/settings.ts#L203 with https://dai.poa.network

**Comment by dkent600** [comment]
> replace replace https://github.com/daostack/alchemy/blob/dev/src/settings.ts#L203 with https://dai.poa.network

That URL does not entirely work, and it doesn't work with websockets which we need to enable subscriptions.

There is a lot of bad documentation out there on this.  I finally found one that works:

"wss://poa.api.nodesmith.io/v1/dai/jsonrpc/ws?apiKey=[AIPKEY]"
