### ISSUE TITLE
Take users to blockscout, not etherscan for xDAI DAOs

### ISSUE THREAD

**Issue by arsena21** [daostack/alchemy#1904]
Right now, if you click on DAO Holdings, you go to etherscan, which isn't the right place to see the balance.

**Comment by EzraWeller** [comment]
@dkent600 I'm still seeing links to etherscan on xDai in every DAO I visit (https://alchemy-staging-xdai.herokuapp.com/, Chrome, mac). Am I missing something?

**Comment by dkent600** [comment]
@EzraWeller It works for me where are you looking?  Like here, works for me:  https://alchemy-staging-xdai.herokuapp.com/dao/0xe248a76a4a84667c859eb51b9af6dea29e52f139/scheme/0x8fc4cefd354efba4884cd5110f4b335ff32b631c2102b516b1f13d92e0feab3f/info/

Maybe I am missing a use case here?

**Comment by dkent600** [comment]
oh, shoot, this is about that "DAO Holdings" icon.  Of all things, I didn't look at that.  Indeed it doesn't work.

**Comment by EzraWeller** [comment]
Yep, that was actually the only one I checked since that was what was mentioned in the first post here.
