### ISSUE TITLE
Remove email signup button on xDAI network

### ISSUE THREAD

**Issue by arsena21** [daostack/alchemy#1905]
Emails don't work on the xDAI network so we should remove the email signup icon.

**Comment by orenyodfat** [comment]
Or make it work on xdai

**Comment by orenyodfat** [comment]
@arsena21 can you please ask that from BuidlHub ?

**Comment by dkent600** [comment]
@arsena21 ?

**Comment by dkent600** [comment]
I'm going to go ahead and remove the button.  If we want BuidlHub to help support email, it can be in a separate PR.  @arsena21 @orenyodfat
