### ISSUE TITLE
Add function to decode data by plugin name in arc.js

### ISSUE THREAD

**Issue by roienatan** [daostack/alchemy#1910]
With this function we don't need to decode plugin data in Alchemy.
This issue is required to solve https://github.com/daostack/alchemy/issues/1893

**Comment by dkent600** [comment]
Was this meant to be created in arc.js?

**Comment by roienatan** [comment]
> Was this meant to be created in arc.js?

Yes. Until now we decoded the plugin data in Alchemy using web3. We agreed that the right place to decode is in arc.js.
