### ISSUE TITLE
2.0 cosmetics

### ISSUE THREAD

**Issue by orenyodfat** [daostack/alchemy#1930]
- [x] round corners on Proposal Plugins elements

**Comment by roienatan** [comment]
Cosmetics in progress: 
- [ ] Equal margin between Proposal Plugins elements
- [ ] Follow button font family to match whole Alchemy
- [ ] Added create proposal modal bottom margin 
- [ ] Plugin manager information tab - elements are now have round borders and margin was added between each element

**Comment by dkent600** [comment]
Please don't start this until the merge from 1.0  is complete

**Comment by roienatan** [comment]
> Please don't start this until the merge from 1.0 is complete

No worries it's for now all the changes are local.

**Comment by dkent600** [comment]
> > Please don't start this until the merge from 1.0 is complete
> 
> No worries, for now all the changes are local.

That's good, but still, unless you are careful in choosing what to work on, there is a non-zero probability you will be fixing something that is already fixed or whose code has significantly changed.

**Comment by roienatan** [comment]
> > > Please don't start this until the merge from 1.0 is complete
> > 
> > 
> > No worries, for now all the changes are local.
> 
> That's good, but still, unless you are careful in choosing what to work on, there is a non-zero probability you will be fixing something that is already fixed or whose code has significantly changed.

I understand, I wasn't sure how many scss changes there are in the merge.
