### ISSUE TITLE
Can't submit a proposal on xDAI

### ISSUE THREAD

**Issue by arsena21** [daostack/alchemy#1935]
This seems to be a new issue as I was able to submit a proposal earlier today. 

When I go to submit a proposal: I get the metamask transaction approval popup, and the transaction seems to go through, but nothing shows up in Alchemy.

**Comment by dkent600** [comment]
1) make sure you don't have any hung or other pending transactions.  If you do then the only way to clear this that I know of is to reset your metamask account

2) make sure you have a gas price > 0 (1 should suffice on xDAI)

After I have confirmed both of these conditions, creating a proposal works fine for me.
