### ISSUE TITLE
Load time optimization [discussion issue; will spin of actionable issues]

### ISSUE THREAD

**Issue by jellegerbrandy** [daostack/alchemy#194]
[this is a discussion issue, to identify potential issues about performance. Once we have actionable items, we can make separate issues]

The problem: the app takes a long time to  render.

These :arrow_down: give an idea: 20secs to download the data, 40 secs or more to render it (on chrome/debian with superfast internet):

![image](https://user-images.githubusercontent.com/1306173/47798311-6ce24a80-dd28-11e8-9fc0-a737041963f6.png)
![image](https://user-images.githubusercontent.com/1306173/47798387-900cfa00-dd28-11e8-8cac-515eb56e37a3.png)
![image](https://user-images.githubusercontent.com/1306173/47798570-f003a080-dd28-11e8-8ee9-c1ae230c4df8.png)

I think to work well on this we'd need some automated tools that tell us the loading time for each build, But we can go for low-hanging fruit first.

Here are some possible things to look at:

* **most of the time is spent on rendering**. The console.log suggests that there is some unnecessary stuff happing (now way we need to load "Avatar" a 1000 times to render the page):
![image](https://user-images.githubusercontent.com/1306173/47797451-a3b76100-dd26-11e8-8842-832e2820a57b.png). I think here there is most to gain. 

* the initial state file is almost 1M. It can be zipped, which will bring it from 1M to 96K. 

* the bundle is 1M, which seems a bit big as well. 

* we also should look at optimizing the server for the bundle download: it takes a consistent 20s to download that file on my machine, which is way too much. 

* now the initial state file is only download AFTER the bundle; this can e done in parallel (i.e. download it in the index.ts or whatever it is called)

**Comment by tibetsprague** [comment]
Yup, so much low hanging fruit! Want to take some of it on @jellegerbrandy :)

**Comment by dkent600** [comment]
You can see here how I specified just the contract json files I need in DX:  https://github.com/daostack/dutchx-bootstrapper-ui/blob/b6b809c7dd37eaa404600c5994ba70d39951fc88/webpack.config.js#L193

**Comment by dkent600** [comment]
We need to discuss getting a newer version of Arc.js....

**Comment by jellegerbrandy** [comment]
One other thing that could improve the user experience is this: now, the "view alchemy" ubtton on the landing page reloads the entire application; it would probably be somewhat faster to just replace the element.

**Comment by jellegerbrandy** [comment]
On the `performance` branch start the app with `npm run start-dev-profiling`, which starts the server locally but tries to mimick production settings as much as possible (specifically, downloads the initial json file from aws, and interacts with main chain). Main difference with production is that we are working with the local 45M bundle instead of the minified 1M bundle on production.

Performance depends very much on conditions not completely under our control: download speed on the network, cpu, amount of actions to sync from the change since the last state snapshot). 

So we have to work with very rough stats. What I'm doing is
- go to http://127.0.0.1:3000/dao/0xa3f5411cfc9eee0dd108bf0d07433b6dd99037f1
- open devtoos, network
- reload the page ("F5")
- wait until the proposals are visible

Sometimes the page does not seem to load at all
Here are results from commit #c58b0c42aea5c46a98b509071ac6a421ec150c2d
![image](https://user-images.githubusercontent.com/1306173/47966386-058f0800-e052-11e8-897c-e52f78daa1e2.png)
![image](https://user-images.githubusercontent.com/1306173/47966420-6ae2f900-e052-11e8-83a2-6c6386788f47.png)

![image](https://user-images.githubusercontent.com/1306173/47966444-b09fc180-e052-11e8-9dd3-f14e4a60cc7d.png)


And these are results after commit 9407b79291b26003685cb9dd273a8e8d2248d64f 
![image](https://user-images.githubusercontent.com/1306173/47966256-d5933500-e050-11e8-988e-196eaaf99049.png)
![image](https://user-images.githubusercontent.com/1306173/47966319-518d7d00-e051-11e8-8c79-ddec9fcff41a.png)
![image](https://user-images.githubusercontent.com/1306173/47966327-74b82c80-e051-11e8-894f-4deb3c22269b.png)
![image](https://user-images.githubusercontent.com/1306173/47966464-f3fa3000-e052-11e8-82fe-2d64cdc2ea2a.png)

**Comment by jellegerbrandy** [comment]
more lowhaning fruit:  this line https://github.com/daostack/alchemy/blob/dev/src/index.tsx#L18 halts execution until arcjs is initialized. This can take some time, bc the init process also waits for establishing a websocket connection (whcih we are not using), which can take some time. 

Solutions here are (a) do not `await` the initilization (which takes some tricky refactoring) and (b) make the initialization ligher (or the websocket optional) (I don't know about the latter, bc I have not looked yet at what the initilization actually is supposed to do)

**Comment by tsuberim** [comment]
@jellegerbrandy https://github.com/daostack/alchemy/blob/dev/src/actions/arcActions.ts#L69 Loads DAOs in a sequential order instead of in parallel.

**Comment by tibetsprague** [comment]
Adding the filter to Initialize ArcJS is super low hanging fruit, would be curious to see how much that improves load time. I believe the only contracts we actually need are DAOToken, DaoCreator, ContributionReward, GenesisProtocol, Redeemer, StandardToken, maybe SchemeRegistrar. Not sure if we also need Avatar, UniversalController... Some testing needed

**Comment by tibetsprague** [comment]
@tsuberim but we only use getDAOs in the caching script when starting from scratch and locally when using ganache so shouldn't effect production at all

**Comment by dkent600** [comment]
I doubt you need SchemeRegistrar

**Comment by jellegerbrandy** [comment]
I spinned of some new issues so our discussion does not get too fragmented:

* #198: zip the initial state file
* #199: initialization of arc.js
* #200: parallelize! (good call @tsuberim :heart:)

**Comment by jellegerbrandy** [comment]
I've added some timers in a41431011ec776ea6cf90b32d33133ede52a841b to see where our time is spent:

![image](https://user-images.githubusercontent.com/1306173/47994482-ac2ae580-e0f2-11e8-9a36-4256026f532f.png)

![image](https://user-images.githubusercontent.com/1306173/47994571-f8762580-e0f2-11e8-87ff-37c826bb6740.png)
![image](https://user-images.githubusercontent.com/1306173/47994617-222f4c80-e0f3-11e8-99c7-9ec29fc91e5a.png)
