### ISSUE TITLE
Wrong URL on xDAI deployment

### ISSUE THREAD

**Issue by arsena21** [daostack/alchemy#1948]
Right now, when you use the DAO creator on xDAI, after deployment, the links below go to the website: 

https://alchemy-staging-xdai.herokuapp.com/dao/....

It should be going to https://alchemy-xdai.daostack.io/dao/... instead

This is the case for both of these links: http://prntscr.com/tfis10

**Comment by dkent600** [comment]
On which website did you do this?

**Comment by arsena21** [comment]
This was on: https://alchemy-xdai.daostack.io

**Comment by cbrzn** [comment]
@dkent600 I think this can be closed sir
