### ISSUE TITLE
2.0: 'boost' and 'execute' proposal buttons does not work .

### ISSUE THREAD

**Issue by orenyodfat** [daostack/alchemy#1967]
see https://alchemy-2-kovan.herokuapp.com/dao/0x790e3ed4b75b357f882cb595b2d233da799a1207/plugin/0x3b17658b687be9d70069119402037caf584448aa37d72a2f098d7914ffd41f85 .

**Comment by dkent600** [comment]
For one the url suggests it's meant for kovan, but allows me to connect on rinkeby (edited) 

I don't see boost and execute buttons, so can't reproduce

**Comment by dkent600** [comment]
@orenyodfat Is best when bug reports include the steps to reproduce, a description of what happened, and what you expected to happen

**Comment by orenyodfat** [comment]
> For one the url suggests it's meant for kovan, but allows me to connect on rinkeby (edited)
> 
> I don't see boost and execute buttons, so can't reproduce. I guess one has to create a new proposal and see what happens.

https://alchemy-2-kovan.herokuapp.com/dao/0x790e3ed4b75b357f882cb595b2d233da799a1207/plugin/0x3b17658b687be9d70069119402037caf584448aa37d72a2f098d7914ffd41f85 cannot press "boost" button

**Comment by dkent600** [comment]
To clarify:  There is boost button in the proposal card's dropdown menu, but when clicking on it, nothing happens.

**Comment by orenyodfat** [comment]
> To clarify: There is boost button in the proposal card's dropdown menu, but when clicking on it, nothing happens.

right

**Comment by dkent600** [comment]
On this line:  https://github.com/daostack/alchemy/blob/96b8f14c9d4125baa864b0990cfc700fdce8552e/src/actions/arcActions.ts#L78

The proposal.name is "SchemeFactory" which is not handled in the following switch statement, or to be more clear, it is handled, but results in a no-op with no feedback to the user.

I remember in the PR that introduced arc.js 2.0 I complained about this function being very fragile.  But it was not altered.

But it is odd to me that this function is being invoked at all when boosting, but the apparent intent is to simultaneously execute and redeem, but it is failing in this case to do either.
