### ISSUE TITLE
cannot redeem staking  on proposal.

### ISSUE THREAD

**Issue by orenyodfat** [daostack/alchemy#1969]
<img width="413" alt="Screen Shot 2020-07-16 at 7 19 45" src="https://user-images.githubusercontent.com/5994398/87626327-c4ab2a00-c734-11ea-8039-f155ec7e70cd.png">

it say that the dao does not have funds for the bounty (true) though the genesis protocol can pay back the staking regardless of that.
@dkent600 does 1.0 behave the same in this case ?

**Comment by dkent600** [comment]
I think the bug is likely on this line, and it is in both 1.0 and 2.0:

https://github.com/daostack/alchemy/blob/96b8f14c9d4125baa864b0990cfc700fdce8552e/src/lib/util.ts#L393

**Comment by dkent600** [comment]
@orenyodfat Should we label this to be fixed in 1.0?

**Comment by orenyodfat** [comment]
> @orenyodfat Should we label this to be fixed in 1.0?

yes.both 1.0 and 2.0 .

**Comment by dkent600** [comment]
On this line:  https://github.com/daostack/alchemy/blob/96b8f14c9d4125baa864b0990cfc700fdce8552e/src/actions/arcActions.ts#L78

The proposal.name is "SchemeFactory" which is not handled in the following switch statement

**Comment by orenyodfat** [comment]
> On this line:
> 
> https://github.com/daostack/alchemy/blob/96b8f14c9d4125baa864b0990cfc700fdce8552e/src/actions/arcActions.ts#L78
> 
> The proposal.name is "SchemeFactory" which is not handled in the following switch statement, or to be more clear, it is handled, but results in a no-op with no feedback to the user.
> 
> I remember in the PR that introduced arc.js 2.0 I complained about this function being very fragile. But it was not altered.

please handle that with @dkent600 @roienatan

**Comment by dkent600** [comment]
@orenyodfat Can we assume that GenesisProtocol will always have sufficient funds to reward everyone it needs to?
