### ISSUE TITLE
Competition proposal on rinkeby has really ugly alias

### ISSUE THREAD

**Issue by dkent600** [daostack/alchemy#1985]
See this competition proposal, here:

https://alchemy-2-https://alchemy-2-rinkeby.herokuapp.com/dao/0xba09811d02631d1b03c21d1369cfcba42348738e/proposal/0xdeee878236f25214e8b2e899f38d711f7db8bcc6d20cad449f20e5b8115c89c5

Note the screwed-up Competition link at the top, which looks that way because of the ugly alias being given to it ("Competition0x0a6c1dee36a6cbd69d7cb9dbb0d1e2429f3f0d01").  

![image](https://user-images.githubusercontent.com/1821666/87935205-a5770a00-ca5e-11ea-9512-de08b6d03dbf.png)

Does this alias represent a bug in migration or test-env?  @orenyodfat   (it is not a problem with Alchemy)

**Comment by orenyodfat** [comment]
fixed #2249
