### ISSUE TITLE
2.0: Cannot redeem !

### ISSUE THREAD

**Issue by orenyodfat** [daostack/alchemy#1993]
see https://github.com/daostack/alchemy/pull/1975#pullrequestreview-451040891

- maybe only for none contributionReward proposal. (maybe not)

**Comment by roienatan** [comment]
There are two unrelated problems to solve this issue:
- Analytics fails.Need to check that `contributionRewards` defined.
- There is no redemption function in arc.js for SchemeFactory and SchemeRegistrar.

This issue depends on this https://github.com/daostack/arc.js/issues/516
