### ISSUE TITLE
Old proposals still showing up on proposals page (Rinkeby)

### ISSUE THREAD

**Issue by arsena21** [daostack/alchemy#1999]
See for example: https://alchemy-staging-rinkeby.herokuapp.com/dao/0xf7876285fd257175ac24e28b976a6c127855463c/scheme/0xab1741ee9d4870e08d33e6871128235a60765fe924de70c150c2216fc1b91e77/

**Comment by dkent600** [comment]
Can't seem to keep the rinkeby expiry bot running.  @ben-kaufman

**Comment by ben-kaufman** [comment]
Yes it was down for some reason, I ran it back now.
