### ISSUE TITLE
Better form validation

### ISSUE THREAD

**Issue by dev-matan-tsuberi** [daostack/alchemy#20]
- Validate forms as the user types/on lost focus (maybe using [react-validation](https://www.npmjs.com/package/react-validation) or [react-validate-form](https://github.com/lonelyplanet/react-validate-form)) and display errors.
- Have pending states when waiting for metamask/network.

**Comment by tibetsprague** [comment]
pending states is done

**Comment by tibetsprague** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Consistent form validation](https://trello.com/c/QoFi2IHg/125-consistent-form-validation)

**Comment by tibetsprague** [comment]
Using Formik now
