### ISSUE TITLE
add genericcall callData raw data to the proposal view 

### ISSUE THREAD

**Issue by orenyodfat** [daostack/alchemy#2021]

**Comment by dkent600** [comment]
@orenyodfat Where?  Choices:

- [ ] KnownGeneric
- [ ] CO2ken
- [ ] DutchX
- [ ] NFTManager
- [ ] StandardBounties

**Comment by dkent600** [comment]
@orenyodfat Is this what you want:  

![image](https://user-images.githubusercontent.com/1821666/88833928-11fdb180-d1a1-11ea-880c-eca951fa9e61.png)

**Comment by orenyodfat** [comment]
> @orenyodfat Where? Choices:
> 
> * [x]  KnownGeneric
> * [x]  CO2ken
> * [x]  DutchX
> * [x]  NFTManager
> * [x]  StandardBounties

all genericSchemes proposals

**Comment by dkent600** [comment]
@orenyodfat says this ^^^ looks OK.

**Comment by dkent600** [comment]
Done in 1.0.  Still needs to be done in 2.0.

**Comment by roienatan** [comment]
Done in 2.0 here https://github.com/daostack/alchemy/pull/2208.
Closing...
