### ISSUE TITLE
DAO Creator bug

### ISSUE THREAD

**Issue by arsena21** [daostack/alchemy#2024]
Getting an error when deploying on mainnet... see below:

![image](https://user-images.githubusercontent.com/2105072/88821017-f1b8fd00-d176-11ea-892b-d6c3abf6c9ee.png)

**Comment by orenyodfat** [comment]
is that already fixed on dev ?

**Comment by dkent600** [comment]
@arsena21 You seem to have reported this very close to when it is claimed that we released a fix for this problem.  Can you please check whether the problem is still happening?   Thanks!

**Comment by dkent600** [comment]
@cbrzn Might you be able to confirm whether this has been fixed in current Alchemy production?  Thanks!

**Comment by dkent600** [comment]
@arsena21 @cbrzn Turns out this wasn't included in the latest release.  So we're working on a new release now.  If you want you can confirm whether it is working here, which is the staging (representative of our dev branch) pointing at mainnet:  https://alchemy-staging-mainnet.herokuapp.com/

**Comment by cbrzn** [comment]
@dkent600 looks like its working on the staging app
