### ISSUE TITLE
Disable "+ New Proposal" button when a plugin is not active yet

### ISSUE THREAD

**Issue by roienatan** [daostack/alchemy#2044]
Currently when a plugin is not active nothing happens when clicking on "+ New Proposal" button. This is a bad UX - should disable the button and/or give a message: "The plugin is not active yet".

**Comment by dkent600** [comment]
My preference in these situations is to give the message.  Or second, if disabled, provide a tooltip explaining why.

**Comment by roienatan** [comment]
> My preference in these situations is to give the message. Or second, if disabled, provide a tooltip explaining why.

That's what I thought :)
