### ISSUE TITLE
proposal history votes display should not be screwed up

### ISSUE THREAD

**Issue by dkent600** [daostack/alchemy#2047]
This was [fixed in 1.0 here](https://github.com/daostack/alchemy/pull/1780).  Happens I believe when both up and down votes are zero.

![image](https://user-images.githubusercontent.com/1821666/89805174-3fcce980-db03-11ea-852e-dd3f7f2a381f.png)

**Comment by roienatan** [comment]
It happens also when the votes are not necessarily both zero, for example here:
![Screen Shot 2020-08-15 at 14 35 18](https://user-images.githubusercontent.com/34843014/90311606-50b39b80-df05-11ea-8f3c-d27f4a74f1b9.png)

And after the UI fix:
![Screen Shot 2020-08-15 at 14 35 25](https://user-images.githubusercontent.com/34843014/90311612-5c9f5d80-df05-11ea-8290-538ad6e70a58.png)

**Comment by dkent600** [comment]
the up/down % numbers need to align left-justified
