### ISSUE TITLE
Proposal count is not updated

### ISSUE THREAD

**Issue by dkent600** [daostack/alchemy#2049]
Rinkeby, when the last pending proposal leaves the pending queue, this often happens:.  The count should be zero and the fetching message should not be showing:

![image](https://user-images.githubusercontent.com/1821666/89811720-0e591b80-db0d-11ea-9bf9-2d9f836fe493.png)

**Comment by roienatan** [comment]
Same issue happens when creating a proposal, you can see it on the UI but the number is updated only after a refresh. After an investigation I realise that `pluginState` prop is not updated automatically hence the component does not re-render and this is causing those issues.
