### ISSUE TITLE
Add timestamps of proposal creation, passed.

### ISSUE THREAD

**Issue by Theylon** [daostack/alchemy#2053]
"Another UI improvement I would ask for Alchemy is to display the timestamps of when a proposal was created, passed, etc."

This is a request from the DXdao, I think this is a great feature which again, is a low hanging fruit. 
IIRC this is a parameter that's accessible directly from the graph.

**Comment by orenyodfat** [comment]
lets start with 1.0 .

**Comment by dkent600** [comment]
@Theylon  @orenyodfat 

1. In addition to the block time, do you also want to display the execution _reason_:

  QueueBarCrossed, QueueTimeOut, PreBoostedBarCrossed, BoostedTimeOut, BoostedBarCrossed

2. Just noting again that in arc.js the proposal creation and execution date properties are inconsistent in how they are typed, see https://github.com/daostack/arc.js/issues/518.  But I can work around that.

3. Besides creation and execution, there are potentially other events we can include.  Do you want any of these:

- [ ] ExpirationCallBounty
- [ ] Redeem
- [ ] RedeemReputation
- [ ] RedeemDaoBounty
- [ ] ConfidenceLevelChange
- [ ] StateChange
- [ ] Vote
- [ ] Stake

**Comment by Theylon** [comment]
Hey sorry, this is an issue requested by John from DXdao, 
I would say a timestamp of proposal created and last timestamp of last event, boosted, passed, redeemed

**Comment by dkent600** [comment]
@Theylon Can you please see [the PR](https://github.com/daostack/alchemy/pull/2064) and reply whether that is good enough?  Thanks.

**Comment by Theylon** [comment]
Hey @dkent600 sorry I was away, yes that looks good 👍
