### ISSUE TITLE
work PRs that need to be pulled from 1.0

### ISSUE THREAD

**Issue by dkent600** [daostack/alchemy#2054]
Create a list of all PRs that are candidates to be pulled from 1.0 into 2.0.

**Comment by dkent600** [comment]
Looks like tickets for this list will start with release 0.10.13.

**Comment by dkent600** [comment]
Candidates:

https://github.com/daostack/alchemy/pull/1892
https://github.com/daostack/alchemy/pull/1953
https://github.com/daostack/alchemy/pull/1889
https://github.com/daostack/alchemy/pull/1976
https://github.com/daostack/alchemy/pull/1780
https://github.com/daostack/alchemy/pull/2036
https://github.com/daostack/alchemy/pull/1988
https://github.com/daostack/alchemy/pull/1892

**Comment by orenyodfat** [comment]
- [x] https://github.com/daostack/alchemy/pull/1892
- [x] https://github.com/daostack/alchemy/pull/1889
- [x] https://github.com/daostack/alchemy/pull/1976
- [x] https://github.com/daostack/alchemy/pull/2036
- [x] https://github.com/daostack/alchemy/pull/2064
- [x] https://github.com/daostack/alchemy/pull/2138
- [x] https://github.com/daostack/alchemy/pull/2137
