### ISSUE TITLE
should better handle unexpected change of account

### ISSUE THREAD

**Issue by dkent600** [daostack/alchemy#2059]
There is a challenge in Alchemy where the following happens:

1. you are using MetaMask
1. you are running Alchemy and the current account 0x1 is taken from the localStorage cache, and your account is not yet connected (readonly mode)
1. account 0x2 is currently selected in MetaMask
1. you attempt any operation that will require signing in MetaMask
1. the operation automatically tries to connect your account
1. you are successfully connected and the Alchemy current account automatically switches to 0x2

At this point the operation you attempted in step 4 will be attempted on one account or the other, 0x1 or 0x2.  Which account depends on asynchronous timing, but it can easily happen that an error will occur and the UI may not handle it well.  Or the operation originally attempted by 0x1 may be performed on behalf of 0x2 instead, and succeed, which would not feel like a success from the user's point of view.

I think the best approach to this is to require a connection earlier in the workflow.

Second is to detect when the account changes in this scenario and abort with an appropriate notification message.

One place where this is an issue is when (un)following a DAO or proposal.

**Comment by orenyodfat** [comment]
at 2.0 or 1.0 ?

**Comment by dkent600** [comment]
Both

**Comment by dkent600** [comment]
> at 2.0 or 1.0 ?

Both

**Comment by orenyodfat** [comment]
> > at 2.0 or 1.0 ?
> 
> Both

so lets start fix that on 1.0
