### ISSUE TITLE
no symbol of DXD at Funding and Voting Power proposal

### ISSUE THREAD

**Issue by orenyodfat** [daostack/alchemy#2065]
https://alchemy.daostack.io/dao/0x519b70055af55a007110b4ff99b0ea33071c720a/proposal/0x92b57aff2571091eefd616ca185f2136232060bf15fefb29611290127eb7bc93

<img width="783" alt="Screen Shot 2020-08-14 at 13 59 14" src="https://user-images.githubusercontent.com/5994398/90242824-60b07a00-de36-11ea-94b3-3b7f9726b6a5.png">

there is a `?` instead of DXD

**Comment by dkent600** [comment]
Not repro.  I see the proposal:

![image](https://user-images.githubusercontent.com/1821666/90243328-b5370380-ddfc-11ea-8faf-6b7a0c1e5404.png)

**Comment by orenyodfat** [comment]
" could we fix this and additionall add a hover on the Symbol that displays the token address on external token requests? "

**Comment by dkent600** [comment]
fixed by #2068
