### ISSUE TITLE
Support Join proposal - at least readonly 

### ISSUE THREAD

**Issue by orenyodfat** [daostack/alchemy#2086]
**Describe the bug**
A clear and concise description of the bug.

**To Reproduce**

**Expected behavior**

**Alchemy Version Number**
You may obtain the Alchemy version number as follows:

1. Hover your mouse over the Alchemy logo image in the upper left corner of any page in Alchemy. Below the icon a tooltip will appear which will contain the Alchemy version number.
2. In the tooltip, select the version number, copy it to your clipboard and paste it into this bug report.

**Screenshots**

**Optional: please provide the following if you find it relevant:**

**Additional context**

**Comment by roienatan** [comment]
For now, there is no existing Join proposal (v8_11) - can't test if able to read only.
