### ISSUE TITLE
Kovan Alchemy Reward: transaction failed

### ISSUE THREAD

**Issue by anthonymq** [daostack/alchemy#2090]
When I try to redeem my tokens after a successful proposal, I encounter this error:
Reward: transaction failed :-( - No Redeemer contract could be found (search for versions 0.0.1-rc.37,0.0.1-rc.36)

https://alchemy-staging-kovan.herokuapp.com/dao/0x3c74e21ded47706c5df451f34acfa4d41a487f6c/proposal/0x19e3cdfd1ae906383edf56e41a336778d1c8f6502ba77f83f9bae362ebab32cb

Thanks

**Comment by orenyodfat** [comment]
https://github.com/daostack/migration/issues/353
