### ISSUE TITLE
Stacked notifications

### ISSUE THREAD

**Issue by dev-matan-tsuberi** [daostack/alchemy#21]
Currently there can only be one notification appearing at a time, and it disappears upon any action.

Support stacked notification that show transactions status and disappear when the operation is complete, as seen here:

![Stacked notifications](https://d3vv6lp55qjaqc.cloudfront.net/items/0U013Q1V2x10170O123B/Screen%20Shot%202018-03-06%20at%201.35.23%20PM.png)

**Comment by dkent600** [comment]
Material design standards call for only one snack (as they are called) at a time.  Consider the behavior on limited mobile device space.

Important snack should not automatically disappear, they should be dismissible by click.

One can color-code the message according to its importance.

(All this is how Vanille works.)

See https://material.io/guidelines/components/snackbars-toasts.html

**Comment by dev-matan-tsuberi** [comment]
Alchemy does not follow Material Design, it follows the design above and so we should support it.
Stacked notifications are indeed problematic on mobile, I imagine they can be displayed with a Bottom sheet (to use Material Design speak), or display one notification with the option of flipping them back and forth with arrows/swipe.

**Comment by tibetsprague** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Move all notifications to pills at the bottom of the screen](https://trello.com/c/dyGkNW61/124-move-all-notifications-to-pills-at-the-bottom-of-the-screen)
