### ISSUE TITLE
Wrong percentage in vote summery proposal

### ISSUE THREAD

**Issue by roienatan** [daostack/alchemy#2106]
Below is an example from NFT proposal, should be 100%.
![Screen Shot 2020-09-06 at 11 17 53](https://user-images.githubusercontent.com/34843014/92321477-fa80d680-f032-11ea-953e-dd65bea92fc3.png)

**UPDATE:** looks like it's a subgraph issue

**Comment by dkent600** [comment]
I wonder what is the vote _count_ (number of votes)?

**Comment by roienatan** [comment]
> I wonder what is the vote _count_ (number of votes)?

It's shows 2 and after refresh it shows 1. We know what the problem is already, you opened an issue regarding this in graph node, and I wonder why their PR still not merged.

**Comment by orenyodfat** [comment]
solved in v8_12_exp
