### ISSUE TITLE
Plugin Manager create proposal / add Plugin Registrar should not display duplicate input parameters

### ISSUE THREAD

**Issue by dkent600** [daostack/alchemy#2122]
STEPS:

1. go to a DAO having the Plugin Manager plugin
1. click Create Proposal
1. select in the "Plugin to add" dropdown Plugin Registrar

RESULT:
Note that all of the input fields below the dropdown are duplicated

EXPECT:
No duplicates

**Comment by roienatan** [comment]
In arc.js (`src/plugins/pluginRegistrar/plugin.ts`) you can see that it's expecting both `voteRemoveParams` and `voteRegisterParams`. If it's correct then it makes sense that they are duplicated. Maybe need to mention this in the form itself for the user.
