### ISSUE TITLE
Subgraph subscriptions in general do not appear to be working in either 1.0 or 2.0

### ISSUE THREAD

**Issue by dkent600** [daostack/alchemy#2126]
Subgraph subscriptions in general do not appear to be working in either 1.0 or 2.0.  Voting, staking, changes in reputation, new proposals...nothing is updating.

Important point:  The subscriptions work in ganache, but not in rinkeby or kovan or mainnet.

Watching the websocket messages in the browser debugger indicates that the messages are simply not arriving when they should in rinkeby, but are arriving perfectly in ganache.  This suggests that the problem is not with the code in Alchemy, but something wrong with the subgraph or the connection we are using with subgraph.

**Comment by dkent600** [comment]
@orenyodfat Need your input on this

**Comment by roienatan** [comment]
As discussed with Jannis from The Graph, they having issues with the subscriptions. Using polling instead is recommended  until further notice.
https://github.com/daostack/arc.js/issues/543 is required.

**Comment by roienatan** [comment]
Done for 2.0, Open to 1.0
