### ISSUE TITLE
Competition tab crashes Alchemy

### ISSUE THREAD

**Issue by roienatan** [daostack/alchemy#2168]
1. Go to https://alchemy-2-rinkeby.herokuapp.com/dao/0xaec973dbde8d726277974c39e16ac4629be416c4/plugin/0x54fb5c1e249372904e72fa94f0bbd013d4917227aaa0e9df8bebfbe6bb9c2074/proposals/

2. Click on the Competition tab

3. Alchemy crashes with message `Invariant Violation: 15 (see https://github.com/apollographql/invariant-packages)`

**Comment by orenyodfat** [comment]
also Competition name is wrong
