### ISSUE TITLE
sidebar should be neither cramped at the top nor clipped at the bottom

### ISSUE THREAD

**Issue by dkent600** [daostack/alchemy#2191]
This is at 100% zoom.  The problem gets worse as you zoom in.  However, it should not matter what is the zoom, the UI should be responsive.  The first image is on 1.0.  The second on 2.0.  You will note that on 2.0 the top looks ok, but the bottom is clipped on both Alchemy versions.

## v1.0
![image](https://user-images.githubusercontent.com/1821666/96092219-94406c80-0e98-11eb-8726-fbb62350b152.png)

## v2.0
![image](https://user-images.githubusercontent.com/1821666/96092635-247eb180-0e99-11eb-8be0-86f311a5add6.png)

**Comment by roienatan** [comment]
https://github.com/daostack/alchemy/pull/2180/files This is the fix I done in 2.0 for the top (DAO name)

**Comment by roienatan** [comment]
Most is solved, this issue https://github.com/daostack/alchemy/issues/2379 is left.
