### ISSUE TITLE
Add xGEN / GEN bridge to Alchemy

### ISSUE THREAD

**Issue by Theylon** [daostack/alchemy#2214]
Add support for the xGEN / GEN bridge in Alchemy? 

1. Add a link to "GEN / xGEN bridge" in the footer in the bottom left.
2. Create the GEN / xGEN bridge in the Alchemy UI/ (xdaibridge.DAOStack.io)

https://xgen.daostack.io/

**Comment by orenyodfat** [comment]
xGEN -> GEN would also be nice

**Comment by Theylon** [comment]
Add it to this section in Alchemy with this text:

[GEN <-> xGEN bridge]

![image](https://user-images.githubusercontent.com/27952472/99182962-227e6b80-2741-11eb-8f9c-a04c59700c7b.png)
