### ISSUE TITLE
Showing Proposal Redemption Status on History page

### ISSUE THREAD

**Issue by arsena21** [daostack/alchemy#2227]
I think it would be great to show the redemption status of all proposals on the history page:

![image](https://user-images.githubusercontent.com/2105072/97599961-cb993800-19c5-11eb-9e13-4434791ba1bf.png)

Right now, you need to click on all proposals to find information on this, which is a pain

**Comment by EzraWeller** [comment]
Closing because we are planning to get rid of the history page and combine it with the new proposals page.
