### ISSUE TITLE
Support an array of decimals in genericSchemeRegistry

### ISSUE THREAD

**Issue by roienatan** [daostack/alchemy#2247]

**Comment by dkent600** [comment]
CurveLabs needs this ASAP (as in, Nov 30).  Any status @roienatan ?

**Comment by dkent600** [comment]
To clarify:  we want to be ale to specify "decimals", like `"decimals": 18` to be able to convert each number value in the array to WEI.

**Comment by roienatan** [comment]
> CurveLabs/PrimeDAO need this ASAP (as in, Nov 30).  Any status @roienatan ?

Yes sorry I'm busy with more issues lately, I’ll try to see how to prioritize this.

**Comment by dkent600** [comment]
@roienatan I'm going to have a go at this.
