### ISSUE TITLE
Support method arrays params in generic multi-call

### ISSUE THREAD

**Issue by roienatan** [daostack/alchemy#2255]
Also: 
- updated webpacks with Etherscan API key
- bool type is text input and not checkbox
- better handling and validation with all types of ABI params

**Comment by orenyodfat** [comment]
no governance information ..at https://alchemy-multi-call-supp-r1d85u.herokuapp.com/dao/0x95f74bce31c67865d75c9038d6b23671ad5a0bda/scheme/0x26333cf21051f3c1cd1151f7da9c251a29662f88ceb1a52e47cd1b454debb665/info/

**Comment by roienatan** [comment]
> no governance information ..at https://alchemy-multi-call-supp-r1d85u.herokuapp.com/dao/0x95f74bce31c67865d75c9038d6b23671ad5a0bda/scheme/0x26333cf21051f3c1cd1151f7da9c251a29662f88ceb1a52e47cd1b454debb665/info/

Done.
