### ISSUE TITLE
[UX] Behavior of alchemy when there is no metamask connection

### ISSUE THREAD

**Issue by jellegerbrandy** [daostack/alchemy#226]
Alchemy should behave well also when there is no metamask connection. (I.e without information about current account or eth connection provided from metamask)

It could work like this:
1. no metamask, or metamask is locked
    - show information from main chain
    - each user action that requires metamask to be unlocked: onclick = show a message describing problem and solution 
1. metamask is present and unlocked. 
    - Use (if we can) the network (and account) provided by metamask
1. when user changes metamask connection or acount, the app should update
1. When user locks metamask, revert to first case

**Comment by dkent600** [comment]
Note arc.js has support for detecting 1) when the network changes, and 2) when the default account changes.

The dxDAO UI has logic for handling all these cases (though is perhaps not as clean as it could be).

**Comment by jellegerbrandy** [comment]
I've made a new issue #235  that replaces this one
