### ISSUE TITLE
[UX] Handle connection errors more gracefully

### ISSUE THREAD

**Issue by jellegerbrandy** [daostack/alchemy#227]
(For example) At the moment, if alchemy-server is not responding correctly,  the profile page remains on ...loading forever, leaving the user in the dark about the cause.

We'd like something like this:
* if the connection breaks, show thsi immediately
* if the service does not respond, we should show, arfter a reasonable timeout (~5 secs?) an error message: "we could not connect to Alchemy Server, so we cannot get your personal information. You can still use ..."
* in both cases, other, independent, functionality shoudl not break

**Comment by tibetsprague** [comment]
@A-Zak it would still be great to have designs for all the different cases
