### ISSUE TITLE
Improve project loading UX

### ISSUE THREAD

**Issue by Razzwan** [daostack/alchemy#2277]
**Is your feature request related to a problem? Please describe.**
Right now first loading of the project taking too long time. We have to reduce this time in order to allow user see the data ASAP

**Describe the solution you'd like**
1. We can use indexed DB for storing cashe and show this cashe immediately with red loading indicator, to shouw the user, that data still loading. 
2. We can show empty blocks to the user until all actual data will be loaded instead loader. Because empty blocks is better then long loading process

**Describe alternatives you've considered**
Alternatively we can just reduce the loading time to improve the system from logical prospective. Just load the data wich is required.

**Additional context**
Looks like we defenetely can improve it from logical prospective just getting required data.

**Comment by dkent600** [comment]
Another option:  Fetch and display each bit of data individually. Until each bit of data is fetched, display something like "--" or a little animated icon, instead of the value of the data.  So the UI gradually populates as the data arrives.
