### ISSUE TITLE
List of Bugs from ETHcc latest Version

### ISSUE THREAD

**Issue by kleinroberto** [daostack/alchemy#23]
Bugs:
1. No visible Version identification
2. When making a new proposal, in both fields of "GEN Reward" and "Reputation Reward" the 0 cannot be deleted without adding another digit.
3. Screen does not get updated if another member votes/makes new proposal unless manual refresh is made.

Requested Features:
1. An indication for un-boosted proposals of how much staking is needed for the threshold of getting boosted
2. Consider a mechanism by which earning from staking is proportional to how early the staking was made (to avoid risk less profit being made by placing a large stake when the casting vote is detected and not yet mined)

**Comment by dev-matan-tsuberi** [comment]
Please break it up into multiple issues. You can use labels to indicate if it's a `bug` or a `feature request`.

**Comment by dev-matan-tsuberi** [comment]
Broke this up to multiple issues:
#24 #25 #26 #27 #28
