### ISSUE TITLE
The height of the proposal form is different for Funding and Voting Power than other proposal types right now.

### ISSUE THREAD

**Issue by Razzwan** [daostack/alchemy#2347]
**Describe the bug**
The height of the proposal form is different for Funding and Voting Power than other proposal types right now. Can we make all the proposals forms stay the same height? (we can let width change when the sidebar is needed as it is now)

**Comment by roienatan** [comment]
Closing.
Currently the hight of the proposal forms is dynamic and set by the content. That's a reasonable behaviour unless we want something else. If we give fixed / minimum hight to all forms we might see white void for small forms and that's not elegant.
