### ISSUE TITLE
Alchemy state and Ethereum connection

### ISSUE THREAD

**Issue by jellegerbrandy** [daostack/alchemy#235]
The App has two states:

1. No ethereum connection and account info available (i.e. Metamask is not installed, or locked, or not connected)
1. Ethereum connection available and account is known (i.e. MM is unlocked and connected)

## State 1: no eth connection :cry: 

   - Which data to show depends on the URL:
      - localhost:3000 (and variants) will connect to ganche and alchemy-server and subgraph on localhost
      - production URL will connect to production. Etc.
   - All transaction functionality is disabled (not sure what that means, but one way could be that if you click on, say, the "vote" button, you see a Modal with instructions to connect to MM)
   - The user profile cannot be shown (bc we do not know which it is) - isntead, we show "plz connect to MM" instructions similar to the transaction warning.

## State 2: Metamask is present :fireworks: 

- check if MM is connected to the correct network. If not (perhaps?) issue a warning. (the warning can also be shown later, when initiating  atransaction)
- if MM is present but no account is enabled: 
   - check for cookie with previous account. if present, use that account
   - if no cookie is present, we ask the user to enable MM **this requires the user clicking on an MM popup**. If the user refuses, we go to state 1.
-  if MM is present and enabled, get the active account from MM. Save this address in a cookie.

- enable all transaction functionality

## App lifetime

1. On first load, we are in state 1. (This will make it possible to show the app quickly without the need to wait for metamask, as we do now). 
2. Meanwhile, async, in the background, we try to access metamask.  
   * If metamask is not available, we stay in state 1.
   * If MM is available and account  is enabled or we found an account cookie:  to state 2
    * If Mm is aviabile, but there is no cookie and no enabled account: ask the user to enable an account.

3. We update UI from state 1 to state 2 soon as MM does become available (and go back to state1 is MM goes away)

**Comment by leviadam** [comment]
I think this plan is good. But I think the focus on MM bad for intuition. We should consider general web3 connections, and also I think we should support Portis. That way if there is no web3 connected we have a fallback to offer Portis.

**Comment by A-Zak** [comment]
@jellegerbrandy it looks excellent!
I would make a few suggestions for small adjustments:
1. When we initially load the app, if no wallet is available, I think it'd be good to remind the users to connect one, with the option to dismiss the reminder and continue the "read-only" state.

The integration with Portis is a good idea, but we should address it in its own ticket :)

**Comment by A-Zak** [comment]
#291

**Comment by jellegerbrandy** [comment]
I don't see the point of such a warning. I am not even sure what danger or problem there is to "warn" against. 

For new (or returning) users that just want to have a look, it is just annoying or confusing or scary (depending on what they know). For users that want to and know how to send transactions, it is annoying as well and I see no added value.  (For a use case:  you want to check for new proposals to see whethere there is something you want to vote on. Why do you need a warning to tell you you have not unlocked metamask?)

**Comment by A-Zak** [comment]
I see what you're saying...
I thought it would be important so we'd know who the user is (so we could show her the actions she took), but I've just read your explanation on discord about keeping the user's account in a cookie, so I guess it is more redundant / annoying than helpful.

**Comment by A-Zak** [comment]
I see it's also written here, I must've missed it on the first read...

**Comment by leviadam** [comment]
Not sure about this part:
```
If Mm is aviabile, but there is no cookie and no enabled account: ask the user to enable an account
```

Why stop the flow and bother the user? Isn't it better to do so only when an action is needed?

Another small thing. Isn't it better to set determine the network from env variable rather than url?

**Comment by jellegerbrandy** [comment]
Remember we need access to the account not just to sign transactions, but also to show peronalised info (balance, profile, rewards for you to be claimed)

So this is the case where you are logged in to metamask, and you have selected an account, but our app does not have access to that accoun because metamask is in "privacy mode" 

It is a bit of a judgment call what to do here. My reasoning here is htat the user will expect to see her personal information - i.e. it will look "wrong" in anonymous mode. Mu other reasoning is that there is no other point where can can ask the user to enable her MM account (but one could very well imagine an "enable MM" butto in the place of the profile link on the top right... 

About the .env variable: yes, the code is comppiled for a certain backend on the basis of environment vars, indeed, but for the user (which is what we are describing here), it will look as if the url determines it.

**Comment by jellegerbrandy** [comment]
closing this in favor of the more specific  #370 and #358
