### ISSUE TITLE
urls should not be case sensitive

### ISSUE THREAD

**Issue by orenyodfat** [daostack/alchemy#2363]
for example this is not working  https://alchemy-release-rinkeby.herokuapp.com/dao/0x35625E9e995F03eA83b0aF56030246eAa8106B5f and this https://alchemy-release-rinkeby.herokuapp.com/dao/0x35625e9e995f03ea83b0af56030246eaa8106b5f works

**Comment by roienatan** [comment]
Usually URLs should be case-sensitive. This issue first raised because the DAO creator generates upper-case links so they were broken in Alchemy. This might fix the issue: https://github.com/dOrgTech/DAOcreator/pull/532

**Comment by roienatan** [comment]
Closing due to https://github.com/daostack/alchemy/pull/2392
