### ISSUE TITLE
Make it so that Alchemy is handles the "unit of account" of eth and tokens consistently

### ISSUE THREAD

**Issue by jellegerbrandy** [daostack/alchemy#238]
Alchemy should *always* represent the amounts internally in "wei" (i.e. in the base units of the tokens); and only convert those to a more readable user format when the component is rendered

**Comment by A-Zak** [comment]
@jellegerbrandy should this still be open? I think we already fixed this...

**Comment by leviadam** [comment]
@jellegerbrandy ?

**Comment by tibetsprague** [comment]
yes this is fixed
