### ISSUE TITLE
DAOcreator broken on xDai?

### ISSUE THREAD

**Issue by EzraWeller** [daostack/alchemy#2389]
**Describe the bug**
When using the DAOcreator on xDai, the "Add Your Wallet" button gives `Error: Please connect your wallet provider to main`. Edit: Same problem when clicking "Install Organization."

**To Reproduce**
1. Connect to xDai and go to https://alchemy-release-mainnet.herokuapp.com/daos/create
2. Get to the "Add Members" section
3. Click "Add Your Wallet"

or
2. Fill everything out.
3. Click "Install Organization."

**Expected behavior**
I expect clicking "Add Your Wallet" to add my current connected address to the member list.
I expect clicking "Install Organization" to send me the first DAO deployment web3 transaction.

**Alchemy Version**
1.0.5

**Comment by dysbulic** [comment]
I was able to go through most of the steps on xDAI, but it hangs on `Signing Create Org Tx`:
![Screenshot from 2021-01-19 21-03-29](https://user-images.githubusercontent.com/181523/105117098-edbcc680-5a99-11eb-9f4f-4bb66de4849c.png)

I got a warning in Metamask that the deprecated `window.web3` is used and may cause errors.
