### ISSUE TITLE
plugin manager proposal issue

### ISSUE THREAD

**Issue by orenyodfat** [daostack/alchemy#2397]
<img width="772" alt="Screen Shot 2021-01-24 at 0 12 55" src="https://user-images.githubusercontent.com/5994398/105615411-11a14480-5dd9-11eb-81d8-450ba0d3120a.png">

**Comment by orenyodfat** [comment]
https://reactjs.org/docs/error-decoder.html/?invariant=31&args[]=object%20with%20keys%20%7Bcode%2C%20message%7D&args[]=

**Comment by roienatan** [comment]
Please provide steps to reproduce.

**Comment by jellegerbrandy** [comment]
not reproducible
