### ISSUE TITLE
Breadcrumbs in the header

### ISSUE THREAD

**Issue by tibetsprague** [daostack/alchemy#240]
Add breadcrumbs to track where you are in the app and make it easy to go back. 

![image](https://user-images.githubusercontent.com/3741/51699960-db9b1100-1fc2-11e9-8a45-acdbd0151984.png)

**Comment by tibetsprague** [comment]
Are the breadcrumbs supposed to show the actual path that the use took to get to the current page, so a history, or should it show the parent -> child relationships of the current page up to the home page? I think the latter, also that is easier to implement since that is hard coded per page :)

**Comment by jellegerbrandy** [comment]
re-opening this. I am on the rewards page and do not see that in the breadcrumbs: 
![image](https://user-images.githubusercontent.com/1306173/54208016-7d2ae300-44db-11e9-84e0-0460247036d6.png)

**Comment by A-Zak** [comment]
Just checked alchemy in production - looks good to me :)
