### ISSUE TITLE
Allow for more custom reward types when creating a proposal

### ISSUE THREAD

**Issue by tibetsprague** [daostack/alchemy#241]
![image](https://user-images.githubusercontent.com/3741/51700119-2f0d5f00-1fc3-11e9-96fc-e620f214daec.png)

This card needs a redesign. We can only have one beneficiary, and only four specific reward types.

**Comment by tibetsprague** [comment]
I'm not sure this is the best UX since Contribution Rewards can only have 4 rewards: 1 for reputation, 1 for ETH, 1 for a native token for the DAO (not yet implemented/supported) and one custom external token. Might be better to just always show three reward rows: Reputation, ETH, and External Token which could be selected from a default list or customized with a token address

**Comment by A-Zak** [comment]
Why only one custom external token? I was under the impression that you can reward any token in possession by the avatar.

**Comment by tibetsprague** [comment]
So do we go back to the interface where we can see all the three available reward types from the beginning? instead of adding one row at a time?

**Comment by tibetsprague** [comment]
@A-Zak add design here when decided. dropdown of curated list checking what exists in the DAOs wallet?

**Comment by A-Zak** [comment]
this is the new design on Zeplin - https://zpl.io/adpmo0R

**Comment by A-Zak** [comment]
@tibetsprague - you said that in order to get the balance of the tokens the dao has - you need a whitelist of tokens to check their balance... right? 
Did I get you one of those, or not yet?

@jellegerbrandy would you rather do it in the client lib?

**Comment by tibetsprague** [comment]
@A-Zak I don't remember getting a whitelist of tokens

**Comment by A-Zak** [comment]
Ok, I will make sure we get it asap!

**Comment by tibetsprague** [comment]
@A-Zak seems like we should mention the word reward somewhere, either as a header above all the token fields, or in each label, like "ETH reward"

**Comment by tibetsprague** [comment]
@A-Zak when you put together the token list would you mind including the token address on mainnet and on rinkeby for each one? thanks!

**Comment by A-Zak** [comment]
@tibetsprague this is the list of token we'd like to start with... We'll probably add more in the future, but it might take a while...

I tried to find the address on rinkeby as well but had little luck... Can we start only with GEN, for staging? I think it's unlikely we would use anything else on a daily basis... :D

Mainnet
=======

GEN		0x543ff227f64aa17ea132bf9886cab5db55dcaddf
DAI		0x89d24a6b4ccb1b6faa2625fe562bdd9a23260359
GUSD	0x056fd409e1d7a124bd7017459dfea2f387b6d5cd
PAX		0x8e870d67f660d95d5be530380d0ec0bd388289e1
USDC	0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48
USDT	0xdac17f958d2ee523a2206206994597c13d831ec7
TUSD	0x0000000000085d4780B73119b644AE5ecd22b376

**Comment by tibetsprague** [comment]
great

**Comment by A-Zak** [comment]
@tibetsprague 
I just saw this on staging and it looks great :D
Is this already using the balance api Jelle wrote? I think it would be good to filter out tokens the dao doesn't hold)

Also, I could not create a proposal with only gen reward (ui forced me to have at least eth or rep filled out)

**Comment by tibetsprague** [comment]
@A-Zak no not using new balance stuff, can you file a new issue for filtering out tokens that the DAO doesn't have a balance in? but wait actually they might have a balance of those tokens in the future, so not sure that's a good idea...

the other issue us a bug, that I just created a PR to fix!
