### ISSUE TITLE
Remove Duplicate DAOs from the subgraph / indexing

### ISSUE THREAD

**Issue by Theylon** [daostack/alchemy#2416]
Edit the registered DAOs in Alchemy. 

The follow feature / DAOs you are a member drop down is causing UX issues in the following scenario: 

We have deployed several DAOs on xDAI for testing, and since they are all duplicates with the same members it makes it impossible to distinguish them in the dropdown menu (see screenshot)

![image](https://user-images.githubusercontent.com/27952472/107142905-9e501480-693a-11eb-8d4e-6e3456ba9946.png)

**Comment by EzraWeller** [comment]
I think this is done, or at least I don't see the copies of xDXdao anymore. @Theylon
