### ISSUE TITLE
Watch for new votes and stakes and live update the UI when they happen

### ISSUE THREAD

**Issue by dev-matan-tsuberi** [daostack/alchemy#25]

**Comment by tibetsprague** [comment]
new proposals made by someone else should be appearing, i will double check. watching for votes is not in place yet

**Comment by tibetsprague** [comment]
https://trello.com/c/CJKrethi

**Comment by tibetsprague** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Watch for any and all new stakes and votes on the blockchain and update UI accordingly](https://trello.com/c/CJKrethi/85-watch-for-any-and-all-new-stakes-and-votes-on-the-blockchain-and-update-ui-accordingly)

**Comment by tibetsprague** [comment]
Confirmed that new proposals do appear in real time. so changing the title of this bug
