### ISSUE TITLE
New proposal - contribution reward

### ISSUE THREAD

**Issue by A-Zak** [daostack/alchemy#253]
Since there will rarely be a situation where you'd need to utilize all four types of rewards, we've thought it be good to only show with the first reward, and let the user add more types as she needs.
@tibetsprague 

We need to make sure to not allow to select two rewards of the same type...

### Zeplin: 
initial - https://zpl.io/bPXy17l
when more rewards - https://zpl.io/beoMrdY

*Missing the design of the dropdown
*Missing metamask info

**Comment by tibetsprague** [comment]
Right now we have a second popup that comes up after the create proposal one, before MetaMask comes up, explaining what is going on, what the transaction will do, etc. Do we still want that? Or can we integrate it into the create proposal modal somehow?

**Comment by A-Zak** [comment]
@tibetsprague yes, we should definitely integrate metamask information into the modal... :)
