### ISSUE TITLE
History view

### ISSUE THREAD

**Issue by A-Zak** [daostack/alchemy#255]
The history view lists all the past proposals of the DAO.
in the future, we'll want to allow the user to sort them by some of the fields, but for now, let's sort them by their ending date.

### Zeplin
https://zpl.io/agPqJyA

**Comment by jellegerbrandy** [comment]
closing this. The page is there, and this issue does not specify any further specific action to be taken.

**Comment by tibetsprague** [comment]
We left open until @brodeur had finished styling
