### ISSUE TITLE
Proposal countdown + progress bar (proposal card & details page)

### ISSUE THREAD

**Issue by A-Zak** [daostack/alchemy#259]
zeplin: https://zpl.io/VOKyBWj

there is a bug in the timer bar: https://github.com/daostack/alchemy/issues/373

**Comment by tibetsprague** [comment]
@A-Zak i assume the blue bar is supposed to show percentage complete from proposal creation date to proposal closing time.

**Comment by A-Zak** [comment]
- colon colours should be the same as the text (#689bd6).
- timer location should be closer to the corner (more to the top and to the left).
- Timer format should change according to how much time is left.
  - > 1day - 3d : 04h
  - < 1day - 04h : 02h : 01m
  - < 1hour - 04m : 02m : 01s

**Comment by jellegerbrandy** [comment]
we have this
