### ISSUE TITLE
Hide/show extra info pane in pre action popups - final touches

### ISSUE THREAD

**Issue by tibetsprague** [daostack/alchemy#260]
The extra info pane is there to explain the "rules of the game". It's designed to provide the necessary information for newcomers and to be out of the way for experienced users, but still be there for them as a reference if needed.

The extra info pane should be open by default whenever a user opens an action popup. checking the don't show this next time checkbox should disable this default for this action only.

Clicking the "got it" button should simply dismiss the pane.

Zeplin: zpl.io/VDqky7O

**Comment by A-Zak** [comment]
@brodeur like we discussed:
• switch the 'x' and the '?'.
• pane should be open by default.
• for now, let's not implement the "don't show this next time" checkbox.
