### ISSUE TITLE
Style Redemptions page

### ISSUE THREAD

**Issue by A-Zak** [daostack/alchemy#261]
The redemptions page (I'm going to try to get approval to change it to "my proposals") shows all the proposal that I have earned something by somehow participating in them.

The proposals are shown in card view, with each card featuring a "redeem" button.

Since there should usually not be too many proposals here, I thought it would be ok to leave the buttons always open, rather than have them open up on hover. not a priority though... :)

### Zeplin
https://zpl.io/aRWg4Me

**Comment by brodeur** [comment]
@tibetsprague Can you point me to the variable that shows the rewards for each redemption?

**Comment by brodeur** [comment]
That's basically the last thing needed for this release.

**Comment by tibetsprague** [comment]
@brodeur you need a string showing the full set of rewards?

**Comment by A-Zak** [comment]
@brodeur the redemptions page looks pretty good! :)
is there any more work you plan on doing here, or can we close this ticket?
