### ISSUE TITLE
Error deploying to Heroku

### ISSUE THREAD

**Issue by tibetsprague** [daostack/alchemy#264]
When auto-deploying a pull request to a Heroku review app it dies with the following error

```
 Building dependencies
       Installing node modules (package.json + package-lock)
       npm ERR! code ENOLOCAL
       npm ERR! Could not install from "node_modules/eth-tx-summary/node_modules/eth-block-tracker/async-eventemitter@github:ahultgren/async-eventemitter#fa06e39e56786ba541c180061dbf2c0a5bbf951c" as it does not contain a package.json file.
```

**Comment by tibetsprague** [comment]
So @jellegerbrandy i dont think this is worth trying to fix since it seems to make more sense to deploy the docker image: https://devcenter.heroku.com/articles/container-registry-and-runtime
Maybe, I'm not sure yet

**Comment by tibetsprague** [comment]
If we do want to fix then looks like we can use https://help.heroku.com/IYRYW6VB/how-do-i-install-additional-software-packages-that-my-application-requires to install libsecret01

**Comment by jellegerbrandy** [comment]
I'd be for deploying the docker image....

**Comment by jellegerbrandy** [comment]
Ok, talked here and there, the plan is:

- short term plan: fix the heroku deployment
- long term plan: "everything on docker" (docker Swarm, kubernetics, something like that)
