### ISSUE TITLE
Error loading proposals from client library

### ISSUE THREAD

**Issue by tibetsprague** [daostack/alchemy#269]
`Network error: Response not successful: Received status code 400`

Relevant stack trace:
```
Arc._getObservableObject | @ | arc.ts?1646:153
Proposal | @ | proposal.ts?36d1:199
Arc.proposal | @ | arc.ts?1646:68
```
Line 199 in proposal.ts: 
```
this.state = context._getObservableObject(query, 'proposal', itemMap) as Observable<IProposalState>
```

**Comment by jellegerbrandy** [comment]
Which branch? We should first merge #256, which has the latest client branch (with slighltly better error handling which may help) then see if the error still occurs

**Comment by tibetsprague** [comment]
my beneficiary_search branch, which I've been keeping up to date. sure yeah lets merge that in

**Comment by tibetsprague** [comment]
Looks like this may have been fixed by https://github.com/daostack/alchemy/pull/267!

Will keep open until im sure
