### ISSUE TITLE
An indication for un-boosted proposals of how much staking is needed for the threshold of getting boosted

### ISSUE THREAD

**Issue by dev-matan-tsuberi** [daostack/alchemy#27]

**Comment by tibetsprague** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Indicate on a proposal how much staking would get the proposal boosted](https://trello.com/c/eqS8bRD5/122-indicate-on-a-proposal-how-much-staking-would-get-the-proposal-boosted)
