### ISSUE TITLE
Vote percentage graph

### ISSUE THREAD

**Issue by tibetsprague** [daostack/alchemy#279]
These are the green and red circle showing vote percentages.

We actually need two types of vote percentage graphs - one for a relative majority vote and one for an absolute majority.

**relative majority**
[In this example](https://zpl.io/VqKRP17), you see the graph for the relative majority vote. 
Here the graph always fills up completely, with each side taking up the relative part of a total comprised of both votings rep.

**absolute majority**

For the absolute majority, we'll need a rather similar graph, with the difference that each side takes up a relative part compared to the total reputation in the DAO, leaving an empty part in the middle.
zeplin: https://zpl.io/V4Q4q3N

**Comment by tibetsprague** [comment]
https://medium.com/@pppped/how-to-code-a-responsive-circular-percentage-chart-with-svg-and-css-3632f8cd7705

or 

http://circle.firchow.net

**Comment by A-Zak** [comment]
Added designs for the absolute majority

**Comment by A-Zak** [comment]
<img width="581" alt="Screenshot 2019-03-12 at 0 20 27" src="https://user-images.githubusercontent.com/302774/54162089-ed465400-445c-11e9-963d-c4a902269297.png">

* colours are a little off, please use: #00be90, #f65050, #e5ebf2 & #ffffff.
* Please add white "spacers" between the each part of the grap

**Comment by tibetsprague** [comment]
@brodeur looks like we still need to add white "spacers" between parts of the graph?

**Comment by brodeur** [comment]
Not quite sure, have tried to do this  -- can you take a look?
