### ISSUE TITLE
Redeem rewards & execute popups

### ISSUE THREAD

**Issue by tibetsprague** [daostack/alchemy#282]
We need a new designs for the modal that comes up when you click the button to Redeem rewards. We also need one for the execute button (which appears for proposals that have not yet been executed and that you don't have any rewards to redeem for.)

**Comment by tibetsprague** [comment]
we may not need them but it would be more consistent to always have a confirmation dialog popup, especially for newer users who haven't used MetaMask much. also its a good place for a bit of documentation of exactly what will happen when they execute the proposal or redeem their rewards... but I don't think we need them

**Comment by A-Zak** [comment]
Let's review it again in the future, closing for now
