### ISSUE TITLE
Move proposals to IPFS

### ISSUE THREAD

**Issue by A-Zak** [daostack/alchemy#284]
In order to become a bit more decentralised, it would be much better if all the proposal details would be saved on IPFS.

@jellegerbrandy these are the details I think we need to save, what do you think?
* Title
* Description
* Attachment hash (on IPFS)
* Proposal details version (so we could update this structure in the future)

### IPFS and caching
Since the caching is not able to handle the IPFS at the moment, we will have work around that.
From all the solutions I heard, I think that having alchemy server as the IPFS cache is preferable. it will allow us to maintain a relatively speedy UI while only requiring a small additional number of requests.

@jellegerbrandy @tibetsprague What do you think? Do you agree? Is there an easier solution?

**Comment by jellegerbrandy** [comment]
This issue from the client lib addresses the same issues and has  a link to the "specs" whch are much like yours: https://github.com/daostack/client/issues/52

**Comment by jellegerbrandy** [comment]
The plan is:
- wait for a subgraph fix for issue https://github.com/daostack/subgraph/issues/42 
- if that does not happen, read the data directly from ipfs using: https://github.com/daostack/client/issues/83
