### ISSUE TITLE
Can't get the current boosting threshold for a DAO

### ISSUE THREAD

**Issue by tibetsprague** [daostack/alchemy#285]
Looks like the threshold is not yet available from the subgraph? is there an issue for this already?

**Comment by jellegerbrandy** [comment]
there is this: https://github.com/daostack/alchemy/issues/224 which links to the following subgrpah issue: https://github.com/daostack/subgraph/issues/43 - please read @orenyodfat 'c comment there.

So just be clear: we are tlaking about "the amount of GEN needed to stake for YES to reach the preboosted stage"

For a specific proposal, this value can be caluclated using orenś  formula, and I'd do it client side. 

However, if we need to order (as described in #224), this value needs to be implemented in the subgraph, and I'll re-open that issue over there.

What is your use case exactly?

**Comment by tibetsprague** [comment]
gotcha, do we need to sort by threshold to boost @A-Zak ? I was just trying to calculate GEN to boost which we can do on the client if we know the constant

**Comment by jellegerbrandy** [comment]
thresholdconst: get it from the client once we have https://github.com/daostack/client/issues/87
