### ISSUE TITLE
User account balance should automatically update as it changes

### ISSUE THREAD

**Issue by dkent600** [daostack/alchemy#29]
User account balance should automatically update as it changes.  My account just received 5 ETH but the balance shown below did not reflect it until I refreshed the browser page.

![image](https://user-images.githubusercontent.com/1821666/37281015-ed32e516-25c5-11e8-82db-c25abe8480de.png)

**Comment by tibetsprague** [comment]
how would we know it would be updated? you mean just constantly poll the balance?

**Comment by dev-matan-tsuberi** [comment]
you can subscribe to `Transfer` events on the token and look for transfer to and from the user's account.

**Comment by tibetsprague** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Update user balances in real time as they change](https://trello.com/c/dtpcDNSM/121-update-user-balances-in-real-time-as-they-change)
