### ISSUE TITLE
Integrate with Portis 

### ISSUE THREAD

**Issue by A-Zak** [daostack/alchemy#291]

**Comment by jellegerbrandy** [comment]
there's an older PR from the portis people (I think) regarding that: https://github.com/daostack/alchemy/pull/188

**Comment by A-Zak** [comment]
Very nice! :)

**Comment by tibetsprague** [comment]
I dont see how that old PR does anything at all, seems to be missing some code

**Comment by jellegerbrandy** [comment]
done
