### ISSUE TITLE
Balances are wrong

### ISSUE THREAD

**Issue by tibetsprague** [daostack/alchemy#292]
Looks to me like the account balances are off, both the number of GEN and the reputation amounts, are they in WEI? Are they supposed to be that big? In general all the numbers throughout the app seem too big, lets make sure they are being converted to and from WEI appropriately, and the client library should probably handle most of that

**Comment by tibetsprague** [comment]
@jellegerbrandy i could use some help with this, im confused about how the account balances are being read

**Comment by jellegerbrandy** [comment]
All the balances returns by the client are in the base unit, i.e "WEI". I thikn we should only convert them at the last moment (i.e. when rendering the widget); and all internal representation so numbers should be in wei.
