### ISSUE TITLE
fix linting rules

### ISSUE THREAD

**Issue by jellegerbrandy** [daostack/alchemy#295]
Now many useful linter rules are disabled, which leads to a bit ugly code. Here is my opinion.

* I  strongly insist, , on re-enabling the "no-empty", "no-unused-expression", "no-shadowed-variable" (<- this one catches real bugs), "no-console", "no-undefined-variable" (if possible), "triple-equals". These rules can avoid real bugs. 

* double vs single quotes: I vote for single quotes, becase they look cleaner. But if you want double quotes, that is fine too, you decide :-) (but lets decide).
* The other big layoutty seting is the semicolon at the end of a line. I don't like it, again bc it looks cleaner without, but again, I'm not going to fight a war about it :-)
* other rules: I don't know what each of them is doing, but let's try nto to disable them but instead choose for consistent behavior.

**Comment by dkent600** [comment]
I vote for double quotes because every language I've ever used, besides javascript, uses double-quotes for strings and single quotes for single chars.  I've always considered javascript sloppy in that regard. Using double-quotes makes me feel less sloppy and maintains consistency with all these other languages.  But I won't fight a war over that either  :-)

**Comment by dkent600** [comment]
Similarly with semi-colons.

**Comment by A-Zak** [comment]
@jellegerbrandy can we close this? has there been a decision? :)

My two cents:
I always hated semicolons. in old languages, you had to have them, so there was nothing to do about it. But in js, you don't, so why the fuck would anyone force them!?

**Comment by jellegerbrandy** [comment]
I agree with you, alex, but it is a religious question, not a rational
argument. There are some rules we shoudl enforce (no unused variables, no
unused imports, check for object equality, stuff like that), some we should
but it is not worth the trouble of refacor (like no-shadowed-vars).
