### ISSUE TITLE
eth balance is not reported in profile popup

### ISSUE THREAD

**Issue by jellegerbrandy** [daostack/alchemy#302]
In the small profile popup top right, it shows "0 ETH", but metamask reports a much higher vaue

**Comment by tibetsprague** [comment]
Hmm, so we are wanting to use redux still for this part? I guess we need to because the current account may not be a member of the DAO. But much of that stuff was stripped out, I guess ill add it back

**Comment by jellegerbrandy** [comment]
So due to limitations in the graph-node software, we cannot index the eth balances there.

The client library exploses a watcher of eth balaces on `arc.getBalance(..)` that returns an observable for the eth balance. (Perhaps it needs a less ambiguous name, I realize now); makes sense to use that. Not sure if we need redux for that, you judge :-)
