### ISSUE TITLE
balances of ETH and GEN are not reported on profile page

### ISSUE THREAD

**Issue by jellegerbrandy** [daostack/alchemy#303]
Actually, the spec here https://app.zeplin.io/project/5c4de2851386a637a927c270/screen/5c6189c35c6a52757dd32460 only shows the amount of reputation, so I suppose we could just remove the ETH and GEN header here.

![image](https://user-images.githubusercontent.com/1306173/52948542-f79f9180-3379-11e9-82fc-fcade84308a4.png)

**Comment by tibetsprague** [comment]
Well we need that from the client: https://github.com/daostack/client/issues/105

**Comment by jellegerbrandy** [comment]
Use: 
`arc.GENToken().balanceOf(address)`
and

`arc.getBalance(address)` for the ETH balance (I'll rename this to ethBalance, to avoid ambiguity)
