### ISSUE TITLE
Make entire proposal card clickable

### ISSUE THREAD

**Issue by jellegerbrandy** [daostack/alchemy#304]
and so the proposal details page is not reachable

**Comment by tibetsprague** [comment]
you can click on the title, do we want to be able to click on the whole card? @A-Zak

**Comment by jellegerbrandy** [comment]
I vote yes. I could not find the link!

**Comment by tibetsprague** [comment]
@A-Zak want a decision here

**Comment by tibetsprague** [comment]
@brodeur says lets not do this because there are many controls people want to click on and if they miss it would be annoying to go to the proposal page

**Comment by A-Zak** [comment]
@tibetsprague @brodeur @jellegerbrandy 
Let's make the entire card clickable.
I agree that they might accidentally tap the wrong thing once or twice, but it's better than not being able to find how to open the proposal... /:

**Comment by tibetsprague** [comment]
i would just add this icon next to the title https://www.iconfinder.com/icons/1585225/exit_external_leave_link_open_website_window_icon

**Comment by A-Zak** [comment]
We will postpone this until after the refactor :)
