### ISSUE TITLE
Style history page

### ISSUE THREAD

**Issue by tibetsprague** [daostack/alchemy#307]

**Comment by tibetsprague** [comment]
@A-Zak need to think about design here, do we tell users why a proposal passed or failed?

**Comment by tibetsprague** [comment]
Options are: Failed by timeout (or expiration), passed by vote, failed by vote. We could also have separate options for passed by relative vote, passed by absolute vote, failed by relative vote, failed by absolute vote... if we want

**Comment by A-Zak** [comment]
This is great! :)
We've update the history page to accommodate just that :)
Check it out - https://zpl.io/agPqJyA

**Comment by A-Zak** [comment]
#365 also related

**Comment by brodeur** [comment]
Make 100% width
Headings styled
Spacing of elements

**Comment by brodeur** [comment]
Please take a look and let me know what you think especially of spacing of elements.

**Comment by A-Zak** [comment]
good enough for now :)
