### ISSUE TITLE
We need a clean DAO for use when running the tests.

### ISSUE THREAD

**Issue by tibetsprague** [daostack/alchemy#310]
The tests are impacted by other changes made during development in the test DAO, which makes it hard to ensure that they will continue to pass. Perhaps we need a DAO that is only used for running the tests, or to create a new one every time we run the tests?

**Comment by tibetsprague** [comment]
@jellegerbrandy I'd love your thoughts on how to best do this

**Comment by jellegerbrandy** [comment]
First of all, I think it is best to do the test setup very close to the tests theselves - i..e. in code that lives in the alchemy `tests` directory. So the dao we test against should not be created all the way down in the migration repo. If we do that, the questio of haivng a new dao for each tests or re-use the same one will just be a matter of optimization (new dao = slower), and so a relatively easy question.

that said,  I'd choose speed here, and would say: let's try to run all tests against a single DAO. That means paying  a bit of attention when writing tests, i.e. not write:

```
createAPropoosal()
expect(numberofproposals).toEqual(1)
 ```
but instead write:
```
numberOfProposalsBefore = countProposals()
createAProposal()
numberOfPropsAfter = countPrposals()
expect(numberOfPropsAfter - NumerOfPropsBefore).toEqual(1)
```
The second is uglier but much much more robust.

**Comment by jellegerbrandy** [comment]
closing this as it seems to be the migration is offering a nice DAO (and we can make issues there if we need changes)
