### ISSUE TITLE
remove dependency on ethereumjs-util and eth-sig-util

### ISSUE THREAD

**Issue by jellegerbrandy** [daostack/alchemy#313]
Deps to check and if possible remove: 

- ethereumjs-util 
- eth-sig-util
- promisify
- path

We inlcude this wholw package just for this one single usage `AccountProfilecontinaer` which does nothing but convert o Hex: 

` const msg = ethUtil.bufferToHex(Buffer.from(text, "utf8"));`

**Comment by jellegerbrandy** [comment]
While eth-sig-util is imported for a function that is alaready preseentin web3: 

`    const recoveredAddress = sigUtil.recoverPersonalSignature({ data: msg, sig: signature });`

**Comment by tibetsprague** [comment]
removing ethereumjs-util & eth-sig-util. promisify still being used
