### ISSUE TITLE
Get transaction notifications working again (now without arc.js)

### ISSUE THREAD

**Issue by tibetsprague** [daostack/alchemy#317]

**Comment by jellegerbrandy** [comment]
hey @tibetsprague I understand you started on this but do not know where... (also, i have opinions on this :-))

**Comment by tibetsprague** [comment]
@jellegerbrandy I started pondering and poking around but really didn't make significant enough process to share. Would love to hear your thoughts :)

**Comment by dkent600** [comment]
@tibetsprague  The arc.js TransactionService docs page is a good reference for how it has been meant to be used:

https://daostack.github.io/arc.js/Transactions/

**Comment by jellegerbrandy** [comment]
Ok, well, while the arc.js system is very impressive and versatile, I'd like to do something more lightweight for alchemy. And that means starting with a description of what we actually want to see there. I suppose two things:

1. transaction state updates (i.e. "sent", "mined", "confirmed", "twice confirmed"...)
2. [maybe] have a list of pending transactions that is persistent over reload

Now, for 1. the client library has provides an observable of a stream of udpates, i.e. if `vote()` is the action,  you can do something like:

```
vote().subscribe((txUpdate) => {
   if (txUpdate.state === 'sent' ) { notify("your transaction has been sent, waitin'for it to be mnied") }
   if (txUpdate.state === 'mined'} {
           notify("your transaction has been mined! It was confirmed ${txUpdate.confirmations} times"}
           // and we also ahve the txUpdate.receipt and the txUpdate.result to do stuff with
    }

}}
```

**Comment by jellegerbrandy** [comment]
@tibetsprague , I started implementing this in #439

**Comment by jellegerbrandy** [comment]
We had a short discussion on discord about how many confirmations to show. 

We could sow:  1 confirmation = three notifications: "transaction sent", "transaction mined", "transaction confirmed".

@A-Zak  what do you say?
