### ISSUE TITLE
Deployment 

### ISSUE THREAD

**Issue by jellegerbrandy** [daostack/alchemy#320]
These services need to be running 

## subgraph

requirments:

- needs to expose websocket as well als http connection
- need staging and production environments, and preferably some way of seeting what version has been deployed
- the subgraph needs access to the ipfs node below (where we save our data)

**status**  currently deploying in aws.

## alchemy-server

Deployed on  https://daostack-alchemy-server-stage.herokuapp.com/api/

(production is on: - https://daostack-alchemy.herokuapp.com/api/)

**status** seems ok. 

## ipfs 

requirements:
- need to be able to pin files

Probably going to use infura, `ipfs.infura.io`.

## ethereum

Using infura for staging (kovan) and production (mainnet)

## alchemy

**status** deployment on heroku is broken, cf. https://github.com/daostack/alchemy/issues/264

# Questions

- we are developing and testing in docker - it makes sense to also deploy alchemy and alchemy-server as docekr containers, and maybe also spin of an ipfs node. In that case, I (jelle) probably would move away from heroku and use docker swarm of kubernetics. (It also makes sense to deploy the whole docker-compose stack, including a local ethereum node, in the cloud, as a kind of "pre-staging" stage)

- We need to coordinate the versions of contracts, graph-node and client/alchemy. Deploying these services manually and separately will ineveitably lead to "why the @#$@# is this not working, which version is it, let's ask X, o he's not online, etc". This needs a plan. 

- does infura ipfs support pinning files?

**Comment by A-Zak** [comment]
found this for ipfs - https://medium.freecodecamp.org/hands-on-get-started-with-infura-and-ipfs-on-ethereum-b63635142af0

**Comment by tibetsprague** [comment]
I will work on getting Alchemy on heroku to start

**Comment by jellegerbrandy** [comment]
Closing this issue, we can make more spefic actionable issues later
