### ISSUE TITLE
Make sure account address is always passed around lower case

### ISSUE THREAD

**Issue by tibetsprague** [daostack/alchemy#323]

**Comment by jellegerbrandy** [comment]
Why? I'd prefer the checksummed address (i.e. with the mixed case), and consider the fact that the subgraph is not using those a bit of a bug.

**Comment by jellegerbrandy** [comment]
The new version (0.0.35) of the client shoudl not care about the case of the addresses, so that is good :-)

**Comment by A-Zak** [comment]
@jellegerbrandy @tibetsprague so can we close this?
