### ISSUE TITLE
Better handle not connected users

### ISSUE THREAD

**Issue by jellegerbrandy** [daostack/alchemy#325]
When we have no metamask connection we should not show the account avatar on the top right.

**Comment by tibetsprague** [comment]
@A-Zak what shall we show while we wait for the account to load, or if MetaMask is not enabled? Nothing? Maybe a button to connect to MetaMask?

**Comment by jellegerbrandy** [comment]
A button like "please log in"?

**Comment by jellegerbrandy** [comment]
Ok I implemented this in #350  - it needs a design @A-Zak  and styling @brodeur

**Comment by jellegerbrandy** [comment]
And with "implement this" I mean there is now a text that says "please log in". It should probably be a link to metamask or something?

**Comment by A-Zak** [comment]
I think please log in is good :)

**Comment by jellegerbrandy** [comment]
I choose to write "please log in"  because i thought that it was obvious that that was not good :-) (what are you "logging in" to?)  And we cannot prompt metamask to popup, because one of the possible cases is that metamask is not installed.

What we need is some clear explanation that we can use in all the parts of the app where this is relevant, and soem way to show that explanation. Here are some situations where we shoudl inform the user to "log in" 

- the "please log in" 
- on the rewards page 
- when initiating a transaction
- "you cannot vote right now"
- [maybe others]

the text is probably smoething of the form "If you do not have metamsk, please intall it, create an account, and get yourself some GEN/REP (???); if instead you do have metamask, please open it and select your account". We can (I think) detect is metamask is installed in the browser, so this text can be dynamic, depending on the situation. 

I'm not sure if this should be a separate page or a popup. We need specs @A-Zak  :heart:

**Comment by A-Zak** [comment]
Ok, now I get what you meant, I'll put it on my list then
