### ISSUE TITLE
Correctly handle expired preboosted proposals that are not over confidence threshold

### ISSUE THREAD

**Issue by tibetsprague** [daostack/alchemy#329]
https://docs.google.com/document/d/1cYSX9Z6RmjSlJLPVKm6fwi4nnk2xrB0-NqXngVv61TY/edit?ts=5c6adf84#

On time ending (i.e. when preBoostedAt + preBoostedVotePeriodLimit > now()): 
if (proposal.confidence) > confidenceThreshold (the confidenceThreshold of value the scheme at the current point in time) (and the amount of boosted proposals < MAX_BOOSTED_PROPOSALS (=4096)):  show button to Boost 
If the confidence level is below the dao threshold: what do we do? - show the boosting button, but keep it disabled with a tooltip saying “confidence below scheme threshold, up-stake to boost”, and also show the “X gen to boost” msg below the staking widget.
if up-staked above scheme threshold, the proposal will get GP stage of boosted.
If down-staked below proposal.confidenceThreshold proposal will get GP queued stage.

**Comment by tibetsprague** [comment]
We need a normal threshold constant to be able to test this

**Comment by jellegerbrandy** [comment]
ie. this is blocked by https://github.com/daostack/migration/issues/70

**Comment by A-Zak** [comment]
@tibetsprague We are now showing an "unboost" button, right?
if so can we close this issue? :)

**Comment by tibetsprague** [comment]
yes, but that should be on you to test and decide if we can close :)

**Comment by A-Zak** [comment]
Verified 💪
