### ISSUE TITLE
number values are not strings or BN on staging (but it's ok in dev)

### ISSUE THREAD

**Issue by jellegerbrandy** [daostack/alchemy#330]
In the console on https://daostack-alchemy-staging.herokuapp.com/dao/0x46d6cdc1dc33a3bf63bb2e654e5622173365ed6a

![image](https://user-images.githubusercontent.com/1306173/53529447-e9c1dd00-3aec-11e9-8e4d-273dc630ac45.png)

In my local dev environment, starting the server with `npm run start-staging`, I do not see this behavior, everything works fine there.

(I have turned this from an error into a warning in the code, because otherwise staging would be broken, but actually this should never happen because the type checker should catch it)

**Comment by tibetsprague** [comment]
looks like ethBalance is returning strings, not BNs. I dont know why this is ok on dev and not on staging though

**Comment by tibetsprague** [comment]
and i cant figure out why its returning strings yet either
