### ISSUE TITLE
check if account is set before sending transactions and show a warning or instructions if it is not

### ISSUE THREAD

**Issue by jellegerbrandy** [daostack/alchemy#338]
The behavior we want to see when the user is not logged in is that:

(1) action buttons are visible
(2) clicking on it will show this warning (now it just logs a warning to the console)

We need some specs @A-Zak and copy

**Comment by jellegerbrandy** [comment]
There is also the "special case" o fthe "enable predicting" button that covers the staking graph. This I think we do not want to have when the user is not logged in.

**Comment by jellegerbrandy** [comment]
thinkin about this some more, what we probably should when clicking on a aciton button when no account is avialble is:
- If MM is present and  unlocked but in private mode: open "enable account" diaglog in MM
- if MM is present but locked: open MM unlock screen
- if MM is not present: show a message wth insturctions to install it

I'm ignoring the portis project for now - but this can be later inserted as a more sophisticated variant of the last step.

**Comment by jellegerbrandy** [comment]
@A-Zak  we need some copy

**Comment by jellegerbrandy** [comment]
Ok, in #350 I have implemented a `checkNetworkAndWarn` function, and are calling that just before a transaction is sent. It checks the conditions, and shows an alert if something is wrong, and cancels the transaction. The function is defined here: https://github.com/daostack/alchemy/blob/jelle/src/lib/util.ts#L88

This is used like this 

 ```public async handleSubmit(values: FormValues, { props, setSubmitting, setErrors }: any ) {
    if (!checkNetworkAndWarn()) { return;} 
```

What we still need to do here is:

- get copy for the different error emssages
- do not use `alert` (of course) but a nicely formatted Modal [:leftarrow: need specs]
- the prediction widget has itś  own logic that handles some (but not all) cases: if fore example, the defaultAccount is not set, it will show this on hovering over the component. Question: which is the UX we want?  (a) disabling the button and informing the user with a overlay  as with the voting or (b) a lat-minute warning when the user clicks on submit.

**Comment by A-Zak** [comment]
@jellegerbrandy 
Question - what types of errors can we get?
I'm guessing, no network, wrong network, unknown network... anything else?

**Comment by jellegerbrandy** [comment]
So the account/network can be not available for the following reasons:

- MM not found. 
- MM found but not enabled
- MM found but connected to wrong network

There is a sepcial case in development/test mode, which works also without metamask. But that is not userland and we can ignore it.
