### ISSUE TITLE
UI in history tab is broken

### ISSUE THREAD

**Issue by jellegerbrandy** [daostack/alchemy#364]
![image](https://user-images.githubusercontent.com/1306173/54115669-3959b000-43ed-11e9-897b-6010fbfb0d9a.png)

**Comment by jellegerbrandy** [comment]
this may have to do with the following error in the console: 
![image](https://user-images.githubusercontent.com/1306173/54115761-70c85c80-43ed-11e9-9c6c-181f5b1832f7.png)

**Comment by tibetsprague** [comment]
@aaronb is still working on this, its just not done yet, so closing as duplicate of the History View card
