### ISSUE TITLE
Add proposal state label/icon to proposal details page

### ISSUE THREAD

**Issue by tibetsprague** [daostack/alchemy#378]
boosted - https://app.zeplin.io/project/5c4de2851386a637a927c270/screen/5c5702f70ddfba308d462244

pending - https://app.zeplin.io/project/5c4de2851386a637a927c270/screen/5c867ed0174bdf196a1168de

regular - https://app.zeplin.io/project/5c4de2851386a637a927c270/screen/5c61e8e0e2609499fd6195bb

**Comment by jellegerbrandy** [comment]
done
