### ISSUE TITLE
Multiple DAOs view

### ISSUE THREAD

**Issue by A-Zak** [daostack/alchemy#383]
bg should use the pattern generated by the dao's address using this lib: http://btmills.github.io/geopattern/geopattern.html

**Comment by A-Zak** [comment]
@A-Zak - think about different params we could show on day 1, and later we could add the "right" ones we have in the design :)

**Comment by A-Zak** [comment]
Until we can get the monthly stats like in the design, let's show Reputation holders, Open proposals, and GEN staked.
@tibetsprague @brodeur, are these stats we can show atm?

Also for now, please rename "monthly stats" to "stats" :)

**Comment by tibetsprague** [comment]
Gen currently staked on open proposals? Or Gen staked all time? Yeah I think we can gather that. 

Sent by m

**Comment by jellegerbrandy** [comment]
let me know if you ned some convenience fucntions in the client library for
this

**Comment by tibetsprague** [comment]
@A-Zak still need to know if you mean GEN staked on currently open proposals, or GEN staked all time?

**Comment by tibetsprague** [comment]
@jellegerbrandy @orenyodfat its not entirely clear to me whether a function that sum's the total GEN staked for a DAO should be in the subgraph, or a helper function in the client library, or in Alchemy. i think it would be most performant to have it in the subgraph

**Comment by tibetsprague** [comment]
similarly should the member count and open proposal count be subgraph fields?

**Comment by jellegerbrandy** [comment]
can someone add a link to the design here? I am a bit unclear on what you want to do here.

Also, should this not bee deep in the backlog?

**Comment by A-Zak** [comment]
@jellegerbrandy this is the design - https://zpl.io/a3e0nK1
And it's not in the backlog since after this milestone we'll be having multiple daos :)

**Comment by A-Zak** [comment]
@tibetsprague - Gen staked on open proposals 🙏 
And if the subgraph can do it it'll be much fast & better imo :)
I'll open a ticket for these on the subgraph :)

**Comment by A-Zak** [comment]
https://github.com/daostack/subgraph/issues/168

**Comment by tibetsprague** [comment]
https://github.com/daostack/client/issues/162

**Comment by tibetsprague** [comment]
implement random background patterns
