### ISSUE TITLE
All schemes view

### ISSUE THREAD

**Issue by A-Zak** [daostack/alchemy#384]
- [x] scheme card
- [x] multiple schemes layout
- - - - - - 
- [ ] fix visual bugs

**Comment by A-Zak** [comment]
Added some notes on these screenshots:
![image](https://user-images.githubusercontent.com/302774/57620659-1769de80-7592-11e9-9fd2-2a54761553ef.png)

![image](https://user-images.githubusercontent.com/302774/57621112-4e8cbf80-7593-11e9-9df5-f0f91f5b9e9e.png)

![image](https://user-images.githubusercontent.com/302774/57621255-9e6b8680-7593-11e9-9550-3a257de6cb03.png)


Also, some regressions from the production version:
=========
![image](https://user-images.githubusercontent.com/302774/57621467-30738f00-7594-11e9-9460-59cf18997be8.png)

![image](https://user-images.githubusercontent.com/302774/57620849-a2e36f80-7592-11e9-95b0-1a500058df3d.png)

**Comment by tibetsprague** [comment]
@A-Zak global constraint registrar and upgrade scheme are actual schemes on the DAO. we could hide them since we dont support proposals for them...

**Comment by brodeur** [comment]
The only part I haven't addressed here is related to Voting Disabled regression -- what should it look like? I can't find it in the designs for the detailView.

**Comment by brodeur** [comment]
@A-Zak
