### ISSUE TITLE
Integrate zendesk into our website

### ISSUE THREAD

**Issue by A-Zak** [daostack/alchemy#395]
So we're going to give zendesk a try... :)
These are the installation instructions from Zendesk:

> Adding the Web Widget to your websites
> To add the Web Widget to your websites, just copy and paste the following code into the website’s HTML source code between the <head> and </head> tags.
> 
> This code must be inserted into every page that you want to display the Web Widget.

```
<!-- Start of daostack Zendesk Widget script -->
<script id="ze-snippet" src="https://static.zdassets.com/ekr/snippet.js?key=53e64c0a-59b8-4771-bf08-053158aed7fc"> </script>
<!-- End of daostack Zendesk Widget script -->
```

**Comment by tibetsprague** [comment]
@A-Zak  inserting this code doesnt seem to do anything, is there setup that needs to happen on the Zendesk side? should i just commit the code with the script tag for now?

**Comment by jellegerbrandy** [comment]
Can we talk about this? What exactly do we expect from Zendesk? Are we going to give live customer support?
