### ISSUE TITLE
Make the genesis DAO the main page (for now)

### ISSUE THREAD

**Issue by A-Zak** [daostack/alchemy#406]
This means skipping the "homepage", and the "all DAOs" screens...

**Comment by tibetsprague** [comment]
This means we need to hardcode the DAO addresses, so wont work on staging on production until those DAOs are deployed... i wish there was a better way

**Comment by dkent600** [comment]
@tibetsprague The dx UI uses a json confiig file to store DAO addresses on a per-chain basis, but woud work equally well on a per-platform basis.  It uses [this package](https://www.npmjs.com/package/aurelia-configuration) which is quite easy and very convenient.  I'm not sure there is any reason you couldn't use it in Alchemy (or adapt the code if you want).

**Comment by jellegerbrandy** [comment]
We already have different configurations for dev, staging and production,
so we could handle it with that logic.

Thre is also a very cheap solution for this: we can do this on the
apache/nginx level, i.e. simply set the "homepage" of `
https://alcgemy.daostack.io/` to the particular DAO page.

We woudl still have the menu items for "view daos" and "home" which would
be kind of meaningless. But that is not specced in this issue :-)

**Comment by leviadam** [comment]
Obsolete.
