### ISSUE TITLE
Show all proposal stages titles in queue screen (even if no proposals in that stage)

### ISSUE THREAD

**Issue by A-Zak** [daostack/alchemy#407]
Right now we only show the titles of the sections that have active proposals in them.
We need to always show all the titles and indicate that the empty ones are empty (mini empty state).

Zeplin - https://zpl.io/VDB3ExW

**Comment by tibetsprague** [comment]
@A-Zak @brodeur do we still need a design here?

**Comment by brodeur** [comment]
https://github.com/daostack/alchemy/compare/show-all-stage-titles?expand=1

**Comment by A-Zak** [comment]
this is ok for now, but we have some time, we should make it look like the designs :)
