### ISSUE TITLE
deploy to staging :)

### ISSUE THREAD

**Issue by A-Zak** [daostack/alchemy#423]

**Comment by tibetsprague** [comment]
well this is an annoying bug, seems like an issue with an npm package, not sure why we are not seeing it locally though. or if we can fix. its in the websockets module depended on by web3-providers-ws

**Comment by tibetsprague** [comment]
updating the version of web3 might fix it, but could also break other things

**Comment by jellegerbrandy** [comment]
I've wanting to upgrade web3 for a while now but it has really nasty bugs in combinataion with the client: https://github.com/daostack/client/pull/124 for which I find no answers on google...

In any case, I resolved the deploy problem by disabling the cache according to these instructions: https://devcenter.heroku.com/articles/nodejs-support#cache-behavior
