### ISSUE TITLE
Disable the hovers on the proposals card (for now)

### ISSUE THREAD

**Issue by A-Zak** [daostack/alchemy#424]
Until we sort them out, let's remove the popups from the proposal card:
• profile hovers (both proposer, and beneficiary)
• reputation turn out (over the voting graph)
• not really a hover, but let's also disable the ability to vote using the thumbs up and thumbs down icons (the ones that are visible before the card expands).

**Comment by brodeur** [comment]
There are two branches out there right now -- one that disables hover, one that fixes hover. Guess we can decide tomorrow which is best?

**Comment by A-Zak** [comment]
So like we discussed, we'll keep the profile hovers, but let's please remove the reputation hover and the ability to vote using the thumbs up / down... :)
