### ISSUE TITLE
Only show the correct DAOs

### ISSUE THREAD

**Issue by A-Zak** [daostack/alchemy#437]
**On staging** we only need to have two DAOs:
• one with the genesis params
• one identical to that, but with a fast proposal lifecycle.

**On mainnet** we will only need the actual Genesis DAO.

[Latest Genesis config params](https://docs.google.com/spreadsheets/d/1fkybRjRR4rO53gkpEhwA3Q2UjAlkIe3q7rrs0_bZFqI/edit#gid=293802003)

**Comment by jellegerbrandy** [comment]
Let's fix this down the stack here: https://github.com/daostack/subgraph/issues/152
