### ISSUE TITLE
Enable predictions button shown when not logged into metamask

### ISSUE THREAD

**Issue by tibetsprague** [daostack/alchemy#453]
Right now when not logged into MetaMask you can still see and click on the Enable Predictions button. Should we disable the button with a tooltip saying please log in? The vote buttons do get disabled but dont have a tooltip, which i do think we should have

**Comment by tibetsprague** [comment]
Or maybe the button should launch metamask :)

**Comment by jellegerbrandy** [comment]
There may be no metamask to launch.

**Comment by brodeur** [comment]
How do I check if someone is logged in to MetaMask?

**Comment by tibetsprague** [comment]
in PredictionBox you can just check whether the currentAccountAddress prop is set

**Comment by A-Zak** [comment]
dup of #578
