### ISSUE TITLE
Redesign/bring back the tooltip for the redeem button that shows the reward details

### ISSUE THREAD

**Issue by tibetsprague** [daostack/alchemy#466]
With it being removed people dont really know what why they are getting what they are getting. We do show this in the pre redeem modal popup, this also needs to be redesigned.

**Comment by tibetsprague** [comment]
Oh wait, the tooltip is still there, just needs a look at the design to see if we like it

**Comment by A-Zak** [comment]
New issue for all tooltips - #478
