### ISSUE TITLE
Preboosted proposals should show un-boosting threshold

### ISSUE THREAD

**Issue by A-Zak** [daostack/alchemy#477]
zeplin: https://zpl.io/beDJGEq

**Comment by jellegerbrandy** [comment]
@A-Zak not sure where on that zeplin link I see this threshold. But in any case, the "threshold to be crossed to pass from preboosted back to queued" is the lowest of two values:

- `proposal.confidenceThreshold` is the confidencethreshold when the proposal was created, or of the last time the proposal was "executed" in the preboosted state.
- the current `confidenceTrheshold`.

(so, if the current score of the proposal is lower then both these values, AND execute is called, state will be set to Queued)

**Question: should we show such preoposals in the preboosted bucked, or just move them to the regular proposal anyway?**

**Comment by A-Zak** [comment]
@jellegerbrandy - yes, it is very small in the design 😅
![Screenshot 2019-04-03 at 1 10 28](https://user-images.githubusercontent.com/302774/55440288-d2748480-55af-11e9-903f-faa4de8db21e.png)

I've tested it today, and alchemy behaves as it should (imo) - it moves the proposal back to the queued list.

**Comment by A-Zak** [comment]
Waiting for https://github.com/daostack/client/issues/103

**Comment by A-Zak** [comment]
Also please note, that currently, the boosting threshold (gen to boost) value is wrong.

These are two (new) proposals in the regular queue (which suppose to have the same boosting threshold), and you can see that one has 0.02 gen staked for it, while on the other you can see that it should only take 0.01 gen to get them to boost.
![Screenshot 2019-04-02 at 18 22 58](https://user-images.githubusercontent.com/302774/55441261-d81f9980-55b2-11e9-9286-c53fcdac8767.png)

p.s.
It took about 17 boosted proposals (!!) to get a proposal with 0.02 gens up stake to not get boosted :D
