### ISSUE TITLE
Ethereum connection UX specifications

### ISSUE THREAD

**Issue by jellegerbrandy** [daostack/alchemy#493]
## Application states

The application has 2 states:

A. User is unknown
B. User is known, and wallet is available and connected to the right network  

# in state A

User is not known. We show all information that there is to show. 

- "please log in" button is visible on top right
- rewards page shows "please log in"
- all action buttons are enabled (cf. #492 ), but will prompt the user to "log in" when they are clicked

# in state B

All functionality just works :-)

## What happens when

1. **On first load**
   1. If Metamask is locked or unavailablle, load state A.
   1. If MM is available, check network. If network is wrong, just load state A
   1. MM is available, account is locked. Load state A.
   1. MM is available, connected to right network, account is enabled: load state B

2. **in state A** clicks on "please log in" or on an action button ("create proposal")
   1. if MM  is not availalbe, promt the user to isntall metamask, and return to state A
   1  if MM is avaiable, but wrong network: tell the user to reconnect, and return to state A
   1. if MM is availalbe, but not enabled: call the `enable()` method that will open a MM prompt to give access to the app. If user does this, load state B; if user refuses stay in state state A

3. When the user changes something in metamask (accunt, network). The application will reload completely.

**Comment by tibetsprague** [comment]
This sounds good to me, some designs still needed I think @A-Zak ?

**Comment by jellegerbrandy** [comment]
Yeah, what we need re:design is:

- copy ("please log in" is really wrong, + there are various messages to be written)
- design of the "please log in" button
- (perhaps) the alerts 

But we can implement the logic already.

**Comment by jellegerbrandy** [comment]
I've implemented this logic in https://github.com/daostack/alchemy/pull/491, just waiting for inputon copy and styling.

**Comment by jellegerbrandy** [comment]
this pr should implement this: https://github.com/daostack/alchemy/pull/693
