### ISSUE TITLE
Change voting percentage representation on proposal cards

### ISSUE THREAD

**Issue by jellegerbrandy** [daostack/alchemy#496]
perhaps these are rouinding errors, but this is not true:

![image](https://user-images.githubusercontent.com/1306173/55004476-999a4580-4fda-11e9-8b1b-86ffc7501da6.png)

![image](https://user-images.githubusercontent.com/1306173/55004626-dfefa480-4fda-11e9-947f-c1a88e5f1f9b.png)

**Comment by tibetsprague** [comment]
@jellegerbrandy can you explain more? what should it show? you mean that 10.28% should not round up to 11% but down to 10%?

**Comment by jellegerbrandy** [comment]
We should use consistent representatinos of these numbers. I.e. either round to integers or to two decimals, but not do both at the same time.That will at least avoid some of the confusion. (Because the current situation _is_ really confusing)

Rounding however is problematic in any case. Imagine the vote is 12.001% for and 12% against. We  must show that "for" is the winning vote here. 

I do not know how to solve this (@A-Zak  this has been an open question for a while now). But meanwhile, I'd strongly argue for at least adopting a consistent representation of the numbers thruoughout the app (and I'd say go for 2 decimals for now, but abstract it into a separate formatting function so we can easily and quickly change it later)

**Comment by A-Zak** [comment]
Yes, I agree, let's use two decimals (with rounding **down** after the second digit) :)

**Comment by A-Zak** [comment]
@tibetsprague

**Comment by tibetsprague** [comment]
So by rounding down you mean that 10.346 would show 10.34 instead of 10.35?

**Comment by A-Zak** [comment]
yes :)

**Comment by tibetsprague** [comment]
is this superseded by https://github.com/daostack/alchemy/issues/510 ?

**Comment by A-Zak** [comment]
Yes
