### ISSUE TITLE
close button of staking popup does not work

### ISSUE THREAD

**Issue by jellegerbrandy** [daostack/alchemy#497]
Or perhaps it is not a "close" button but a "fail" icon? If so, let's use another icon.

![image](https://user-images.githubusercontent.com/1306173/55004729-06154480-4fdb-11e9-9ece-377e642d774d.png)

**Comment by tibetsprague** [comment]
yeah not a close button, @A-Zak do we want another icon?

**Comment by dkent600** [comment]
Reason for closing?
