### ISSUE TITLE
none of the buttons on the detail page are clickable

### ISSUE THREAD

**Issue by jellegerbrandy** [daostack/alchemy#498]
https://daostack-alchemy-staging.herokuapp.com/dao/0x15354e4aa3ee99bd07bb0b660fabf885c413033e/proposal/0xc5f35f687f1787d71913947b3fabd4fa81d56d8850fa471ed59a33450769d675

**Comment by tibetsprague** [comment]
pass and fail predictions works for me, as does Execute. vote against also. but vote for does not work

**Comment by A-Zak** [comment]
@tibetsprague Also, hovering over the redeem button crashed the app... O_O

**Comment by tibetsprague** [comment]
I saw that. Not locally though...

Sent by m

**Comment by A-Zak** [comment]
yeah, for me everything works locally. 
let's wait to test on staging with the latest dev, and continue from there... :)


staging
