### ISSUE TITLE
we should inform the user about connection errors

### ISSUE THREAD

**Issue by jellegerbrandy** [daostack/alchemy#500]
I just tried to create a proposal on staging.  The dialog disappeared and then nothing happened.  I'm not sure what I should be expecting, but I think more than nothing.  :smiley:  I was viewing "Boosted Proposals" at the time.

Here is the console output:
![image](https://user-images.githubusercontent.com/1306173/55006129-863ca980-4fdd-11e9-8351-8bc2b3590e95.png)

**Comment by A-Zak** [comment]
This could add an error notification for this saying "We couldn't connect to our server, please try again later"

**Comment by jellegerbrandy** [comment]
This is actually a much more complex UX issue:

- If the proposal state is not updating, then basically the user will see false (outdated) informationk, and we not only inform the user, but we should probably disable all of the actions on the "live" proposals. It is hard to decide _when_ to do this - i.e. 1 second delays is normal, 5 minutes without a response means it is down, the sweet spot is somewhere in between)
-  If the ethereum node is not reachable, we do not need to inform the user immediately, but we should do so before sending the transaction. 
- If ipfs is not reachable, the only problem for the user is that he cannot save profile info, there is no need to warn until the user tries to do so. 
- If alchemy-server is down, we are missing account information, but everything else will work fine, so we probably should replace the "account profile" popup with something like "could not fetch ..."

**Comment by jellegerbrandy** [comment]
This is actually a much more complex UX issue:

- If the proposal state is not updating, then basically the user will see
false (outdated) informationk, and we not only inform the user, but we
should probably disable all of the actions on the "live" proposals. It is
hard to decide _when_ to do this - i.e. 1 second delays is normal, 5
minutes without a response means it is down, the sweet spot is somewhere in
between)
-  If the ethereum node is not reachable, we do not need to inform the user
immediately, but we should do so before sending the transaction.
- If ipfs is not reachable, the only problem for the user is that he cannot
save profile info, there is no need to warn until the user tries to do so.
- If alchemy-server is down, we are missing account information, but
everything else will work fine, so we probably should replace the "account
profile" popup with something like "could not fetch ..."

**Comment by A-Zak** [comment]
Ok, I think now I get it...
Definitely under spec needed... 💪
