### ISSUE TITLE
Style proposal URL (Attached Link) on proposal details page

### ISSUE THREAD

**Issue by tibetsprague** [daostack/alchemy#502]
If a proposal has a URL then we have an "Attached Link" link on the proposal details page, but right now it doesnt even look like a link. Should match the designs

**Comment by A-Zak** [comment]
link to zeplin: Attachment

**Comment by A-Zak** [comment]
The url button looks good, but it takes me to the wrong place...
proposal url: www.google.com
takes me to:
https://daostack-alchemy-staging.herokuapp.com/dao/0xb89370c74d929ca24daeb000e8f90b8c9685d375/proposal/www.google.com

:)
