### ISSUE TITLE
approve and stake in one tx

### ISSUE THREAD

**Issue by A-Zak** [daostack/alchemy#504]

**Comment by jellegerbrandy** [comment]
please spec this better. This means removing the "enable predicting" buton. But we may still want to keep the possibility to pre-approve, if only to save gas costs to an "advanced"  user. We want to make it an option?

**Comment by tibetsprague** [comment]
In the past we tried to do this but the functionality didn't yet exist in a good enough state to use in MetaMask, and also other wallets didn't support it at all.

**Comment by tibetsprague** [comment]
I wish I remembered the details better...

**Comment by jellegerbrandy** [comment]
This will be done in a generic way using 
https://github.com/daostack/web3-transaction-batcher
