### ISSUE TITLE
On fresh page load, action buttons are not clickable

### ISSUE THREAD

**Issue by A-Zak** [daostack/alchemy#509]
When you first load a dao (contribution reward scheme page), action buttons (vote & stake) are disabled. To get them working you need to change pages (e.g. go to rep holders and back to home).

**Comment by tibetsprague** [comment]
@A-Zak I cant replicate this locally. was this on staging?

**Comment by tibetsprague** [comment]
@A-Zak working for me with latest!

**Comment by A-Zak** [comment]
@tibetsprague this is still happening for me on staging /:

**Comment by tibetsprague** [comment]
weird, not for me. can you show me?

**Comment by A-Zak** [comment]
@tibetsprague I think you are correct!
I think all this day I was confused by #533

**Comment by tibetsprague** [comment]
so we can close this no?
