### ISSUE TITLE
String preparation for staking amounts

### ISSUE THREAD

**Issue by brodeur** [daostack/alchemy#510]
Never show less than .000...

0-1
< .001 - .999

0-100
00.00 - 99.99

100-1000
.1k - 1k

1000 - 100,000
1k, 100k

100,000 - 100,000,000
.1M - 100M

**Comment by tibetsprague** [comment]
Meaning if its less than .000 we just show .000? what about the really tiny stake amounts that the DAO makes on new proposals?

**Comment by jellegerbrandy** [comment]
Guys, we CANNOT show 0 if the value is different from 0. A proposal might pass or move to boosted because of such a value, and the user will be utterly confused.

**Comment by jellegerbrandy** [comment]
This holds for all differences: We cannot show "5.00% for and 5.00% against" and have the propsal fail because against was really "5.0000001".

**Comment by jellegerbrandy** [comment]
(I realize I am only noting a problem and not proposing a solution :-/)

**Comment by tibetsprague** [comment]
we could show 1e-10 for very small amounts, but tiny differences in percentage sound hard, maybe its enough though to just show which side is winning even if the numbers look the same. or we could use a > symbol like >5.00%

**Comment by tibetsprague** [comment]
or 5.00+% 
 
and put whole number in the tooltip

**Comment by jellegerbrandy** [comment]
To recapt what we said on the call yesterday:

- We  do not care so much about precision when showing balances and payouts and such 
- the only thing that a different of 0,000001% is relevant is when comparing values (votes or stakes)
- in the comparison widget, we aan also see which vote is witting (thumbs up, thumbs down, red line whatever). So whowing "5.00% for, 5.00% against, against wins" is ok
- we want a consistent rep throught the app (say two decimals + a mouseover with the whole precision)
- we have nto really decide what to do with small or big numbers (use the `e` notation, or the `100K` notatin.

**Comment by A-Zak** [comment]
I prefer 100k notation, as noted in the first comment...

**Comment by A-Zak** [comment]
I think zeros show up as '~0.001'.... if it's an absolute zero, please display them as '0'. :)

<img width="635" alt="Screenshot 2019-04-10 at 1 14 34" src="https://user-images.githubusercontent.com/302774/55841532-2f37e800-5b38-11e9-949c-a9e086fcc1ac.png">

**Comment by A-Zak** [comment]
@tibetsprague I've tried this out today, and it doesn't look so good... /:
<img width="175" alt="Screenshot 2019-04-10 at 10 45 20" src="https://user-images.githubusercontent.com/302774/55864235-c3c83780-5b84-11e9-9231-956058fecc06.png">

But I do believe I found a much more elegant notation for small numbers - [the signed zero](https://en.wikipedia.org/wiki/Signed_zero#Scientific_uses)

So basically if a number is smaller then '0.01', we can display is as '+0', which is both smaller, and (IMO) much nicer :)

-----

I also think it'd be nicer if we always stay with two decimal points, even for small amounts.... those should not happen too often, and it'll create a very consistent experience... can you please change that as well... 🙏

**Comment by A-Zak** [comment]
@tibetsprague, regarding #576, just to confirm, the current logic is not doing any rounding (up/down), but rather truncates the extra digits (essentially reducing precision)... right?

**Comment by tibetsprague** [comment]
@A-Zak yeah, no rounding, just truncating

**Comment by A-Zak** [comment]
great 10x :)

**Comment by A-Zak** [comment]
Looks great! thank you 🙏
