### ISSUE TITLE
Group transaction notifications

### ISSUE THREAD

**Issue by A-Zak** [daostack/alchemy#511]
Each transaction should have only one notification, with three stages:
• Waiting for the user to sign
• Sent -> waiting for confirmation
• Confirmed -> close after a timeout.

**Comment by jellegerbrandy** [comment]
I do not understand what this means. but if the proposal is to change the notification system, I'm strongly in favor of moving this to the bottom of the backlog.

**Comment by tibetsprague** [comment]
I think he means that instead of showing a new notification for each phase of the transaction we should just update a single notification

**Comment by A-Zak** [comment]
@jellegerbrandy yes, this is what Tibet mentioned.
That said, this is indeed in the backlog.
atm, the backlog is not prioritised at all, so there is no top or bottom, just a big blob of backlog... :)

**Comment by jellegerbrandy** [comment]
Ok, I get it now. I think it's a terrible idea. We can discuss once we get to doing it (or not :-))

**Comment by jellegerbrandy** [comment]
closing this as it is not in the scope of the LTS release
