### ISSUE TITLE
Executing doesn't seem to really "execute" the proposal... O_o

### ISSUE THREAD

**Issue by A-Zak** [daostack/alchemy#513]
@jellegerbrandy @leviadam @tibetsprague 
So right now, as I see in alchemy if a proposal to give me 10 reputation passes and I press execute - I don't get the 10 reputation.
I only get the reputation after pressing the redeem button.

I have two questions:
1. Do we know why this is how it works?
2. Can we make it so that pressing the execute button will also "execute" it? :)

**Comment by leviadam** [comment]
I think this is possible with a helper contract as both do not care about `msg.sender`.

**Comment by tibetsprague** [comment]
I thought this was on purpose. you can definitely execute and redeem at once, but I thought we decided to separate into two phases to ensure that all proposals got executed first (even if they dont have redemptions for someone), and then people can do their redemptions. @A-Zak are you saying that we want to show redemptions on the main queue page for boosted proposals that will pass once someone executes it?

**Comment by dkent600** [comment]
@A-Zak By **Arc** (not Alchemy) definition, executing and redeeming are two separate operations, so best not to conflate them in terminology.

**Comment by jellegerbrandy** [comment]
Yes, what tibet and doug say. Perhaps we need to clarify because the terminology that is used in the infra contracts that we are using here (genesisprotocol and contributionreward) is a bit counterintuitive and confusing. 

## what infra does:

So the gensisprotocl has an `execute()` function changes the state of the proposal  It does **not** change the state to "executed" (you may call "execute()" to move the propsal from the queue to preboosted) ,  and it does **not**  " transfer any rewards or reputation at all. 

The ContributionReward exposes a  `redeem()` function that sends the rewards to the beneficiaries (= what I would naively have called "executing the proposal")

Also the gensisprotocl has a `redeem()` function. Calling this function will give you the rewards you get based on voting an staking and such. It also has a `redeemDAoBounty`. 

# what alchemy actually does now

The top-right  button in the proposalcontainer (which has at it's label either "boost" or  a little triangle with an unspecified meaning) in alchemy calls the gensisprotocl.execute() button. 

The redeem button in alchemy calls a helper contract that calls the three different redeem functions mentioned above (and adds some further logic which purpose escapes my understanding)

#  So let's fix this terminology

For me, "executing a proposal" means "doing what has been proposed", in the case ofa contribution reward, this means giving their rewards as specified in the proposal. If you agree, that is the terminoogy we should use in alchemy.

As what the buttons should actually do: I don't know, you guys decide :-)

**Comment by dkent600** [comment]
Have you guys considered using the `Redeemer` helper class for redeeming?

**Comment by dkent600** [comment]
@jellegerbrandy 

> So the gensisprotocl has an execute() function changes the state of the proposal It does not change the state to "executed"

GP.execute does set proposal.state to `executed`:

https://github.com/daostack/infra/blob/ede50f61ceaaa3af5e7e4f8ab78b7c18455b2bec/contracts/votingMachines/GenesisProtocolLogic.sol#L572

**Comment by dkent600** [comment]
@jellegerbrandy 

> There is no need at all to use base the terminology in Alchemy on the function naming of the solidity contracts.

I think in the Alchemy UI we can try to be friendly and use words intuitive and informative to the user, but in discussing the code, that is another story.  I think diverging from the Arc terminology will be inviting no end of confusion in our conversations.

**Comment by jellegerbrandy** [comment]
We are using the Redeemer contract for redeeming. The function call can set the state to any state different from Queued, indeed. It should have just been called "updateState" and we would not have needed this discussion :-)

**Comment by A-Zak** [comment]
Thank you @jellegerbrandy for that explanation, definitely make everything much clearer :)

And yes, I agree with your suggested terminology, executing the proposal should call `genesisProtocol.execute()` AND `contributionReward.redeem()`.

The other two rewards - genesisProtocol.redeem & genesisProtocol.redeemDaoBounty.

**Comment by A-Zak** [comment]
If this is the Redeemer contract you were talking about - https://github.com/daostack/upgradeableContracts/blob/38956e20a34d6f370580134a47214acd8a9d0b77/contracts/utils/Redeemer.sol

It looks like it is also calling the `genesisProtocol.execute()` - which is exactly what we want for all the buttons...
Pending proposals - it'll just gp.execute it
Boosted (& quiet ending) proposals - it'll gp.execute, cr.redeem & get all the relevant rewards for the user that does the execution
Executed proposals (for the rest of the users) - it'll just collect the rewards...

Please correct me if I'm wrong ^_^

**Comment by A-Zak** [comment]
Another thought that crossed my mind - The redeemer will only work for Contribution Reward proposals - not for scheme registrar / generic action...

@leviadam I think it would make sense to integrate a generic version of it within the genesis protocol. That will allow us to also execute every proposal that confronts to `ProposalExecuteInterface`. :)

**Comment by A-Zak** [comment]
Oh wait, it looks like only contribution reward doesn't really "executes" on `executeProposal`, it only marks the execution time... /:

@leviadam @orenyodfat, why does contribution reward have it's own "execution" function?

**Comment by dkent600** [comment]
@A-Zak `CP.executeProposal` implements `ProposalExecuteInterface`.  The method is invoked in `GP.execute` when the proposal is executed.  It allows the "orgnization"  (in this case CR) to do its own thing upon execute.  It doesn't just mark the execution time, it also emits an event.

**Comment by tibetsprague** [comment]
lets's discuss this tomorrow, im still quite confused about what we want to happen

**Comment by A-Zak** [comment]
Right, so it's great that GP calls `executeProposal`, but CR `proposals.executeProposal` (other than marking the time, and emitting an event), don't actually execute the proposal...

**Comment by dkent600** [comment]
@A-Zak 

> CR proposals.executeProposal (other than marking the time, and emitting an event), don't actually execute the proposal

Right, it is not supposed to.  Only voting machines are responsible for doing that.

**Comment by tibetsprague** [comment]
documenting what I believe we decided:
- for now we will have the Execute button call the Redeemer helper function to both execute the proposal, redeem the beneficiary rewards, and redeem the rewards for the current user. This is mostly cool, but not ideal because the user who clicks the button won't see or know what rewards are going to be or are rewarded to them when they click the button. 
- So we are also going to create an issue in Infra (or is it in Arc?) to have a new function that will execute the proposal and redeem the CR beneficiary rewards.

**Comment by dkent600** [comment]
@tibetsprague   It is in Arc

To clarify ....

> to have a new function that will execute the proposal and redeem the CR beneficiary rewards _without redeeming for the beneficiary_

Would be easy by altering the existing `redeem` function to check if `_beneficiary` is `address(0)`, and if it is, skip the beneficiary rewards.

**Comment by jellegerbrandy** [comment]
@tibetsprague "not ideal because the user cannot see what she's getting": this is true but perhaps we can show it somehwere.

An argument against having a button that does  "redeem for beneficiary but not for yourself" button: it takes away the incentive to click that button.

**Comment by tibetsprague** [comment]
@jellegerbrandy how would we know what the user will get? the subgraph wont give us that right? i guess we could do all on the client, but thats annoying and duplicate code

**Comment by A-Zak** [comment]
@jellegerbrandy What we talked about (and what I think Tibet meant) was that the new function in arc will redeem the CR beneficiary - IN ADDITION to executing the proposal (which suppose to have its own incentive).
it's basically attaching the CR beneficiary redemption to the execution of the proposal instead of the GP rewards redemptions...

**Comment by A-Zak** [comment]
One thing to note (which I hope is not an issue), is that the execution incentive seem to happen only when you call `executeBoosted`, which the current version of Redeemer doesn't do (Redeemer calls `execute`).

@leviadam, you mentioned earlier that using a helper contract is not a problem since execute doesn't care about `msg.sender`. well, it seems like `executeBoosted` does care.

I just wanted to make sure this is not a problem, and if so, that we find out now.

@jellegerbrandy @dkent600 @orenyodfat @tibetsprague

**Comment by A-Zak** [comment]
Discussion moved to https://github.com/daostack/arc/issues/618

**Comment by tibetsprague** [comment]
Just call Redeemer.redeem for now

**Comment by tibetsprague** [comment]
@A-Zak and @jellegerbrandy one issue with just calling Redeemer.redeem is the notifications will talk about a "Reward transaction" not an Execute transaction

**Comment by A-Zak** [comment]
I think we should.
The protocol method & param names are confusing, but the client's don't have to be.
In other words - calling execute should do what every person would expect - execute the proposal... :)

**Comment by tibetsprague** [comment]
In theory the fix for this got merged in, but it's not actually working (@jellegerbrandy i forgot to mention that that PR was not really ready to go) because Redeemer.redeem is not sending the CR beneficiary their rewards. I created this issue: https://github.com/daostack/arc/issues/624

**Comment by A-Zak** [comment]
@tibetsprague Oren sais that our final solution (execute & distribute the CR, but not the GP reward and dao bounty) can be achieved by passing null as the beneficiary (like @dkent600 suggested)... :)
https://github.com/daostack/arc/issues/625#issuecomment-483215215

**Comment by tibetsprague** [comment]
@A-Zak can you help me test this and see if the current version is working on staging or not so we can tell Oren if it needs more work? at the same time, you want me to switch to passing in null so GP rewards are not redeemed?

**Comment by A-Zak** [comment]
OK, so I've tested it now, and it does work!

The problem you reported (@tibetsprague) was actually in the way we created the proposals... It seems we were using some sample code params that created all the proposals with 5 reward parts with a 12 seconds delay O_O. So when we tried the `redeemer.redeem`, it could never get the beneficiary its reward because we had to wait 12 seconds... 🤯

There is only one thing that I'd like us to try to pass null as the beneficiary...

**Comment by tibetsprague** [comment]
Ok, this is pending this PR in the client https://github.com/daostack/client/pull/181
