### ISSUE TITLE
Add an icon next to the proposal title to indicate it is the only clickable element

### ISSUE THREAD

**Issue by A-Zak** [daostack/alchemy#515]
Until we do the refactor, and can make the entire card clickable (#304), let's make sure the user knows it's the title that place to click :)

let's go with Tibet's proposal and add this icon next to the title
https://www.iconfinder.com/icons/1585225/exit_external_leave_link_open_website_window_icon

**Comment by brodeur** [comment]
Should be merged in. Take a look.

**Comment by A-Zak** [comment]
looks good
