### ISSUE TITLE
Do we need to show user more of a disclaimer?

### ISSUE THREAD

**Issue by tibetsprague** [daostack/alchemy#524]
In the old Alchemy we had a big disclaimer about the app on the homepage and if a user tried to go directly to a page we would first send them to the home page to see that and track in a cookie that they had seen it. Do we still want something like that or is the warning at the bottom of the page enough?

**Comment by dkent600** [comment]
Side note:  perhaps use web local storage instead of a cookie.

**Comment by A-Zak** [comment]
What was in that disclaimer? Was there anything other then what's in the bottom disclaimer?

**Comment by tibetsprague** [comment]
Hmm, im not quite sure, the home page doesnt have a disclaimer on it anymore... so seems unecessary

**Comment by A-Zak** [comment]
👍
