### ISSUE TITLE
create a smaller bundle

### ISSUE THREAD

**Issue by jellegerbrandy** [daostack/alchemy#529]
* the current bundle size is 11.4MB; this value (and the historical values) can be seen in https://travis-ci.org/daostack/alchemy/jobs/514552706#L4200
*  having less dependencies is low-hanging fruit: https://github.com/daostack/alchemy/issues/313
* we certainly should have a very light landing page and load the Big Bundle in the background
* `npm run analyze` analyzes the bundle and shows a nice pciture

**Comment by jellegerbrandy** [comment]
there are many possible improvements here:

![image](https://user-images.githubusercontent.com/1306173/55396160-868bf600-5543-11e9-952b-d2078a771aa1.png)

**Comment by tibetsprague** [comment]
https://hackernoon.com/optimising-your-application-bundle-size-with-webpack-e85b00bab579
https://hackernoon.com/reduce-webpack-bundle-size-for-production-880bb6b2c72f
https://github.com/GoogleChromeLabs/webpack-libs-optimizations
https://github.com/GoogleChromeLabs/webpack-libs-optimizations

**Comment by tibetsprague** [comment]
- Only load the exports we need in each import statement
- Ignore stuff we don't need from vendor libraries, like locales from moment
- separate vendor chunk
- code splitting by routes?
- GZIP compression
- Minimal source maps, figure out best options for each environment
...

**Comment by jellegerbrandy** [comment]
about the first point: we should enable the `no-unused-imports` in `tslint.json`
