### ISSUE TITLE
Action button states on preBoosted & boosted proposals that have expired - need execution

### ISSUE THREAD

**Issue by A-Zak** [daostack/alchemy#533]
This is required in a scenario where a proposal is (pre)boosted, and then other proposals are boosted-boosted, effectively raising the `confidenceThreshold`. When the pre-boosted proposal then times out and is ready to be boosted-boosted, it can no because it's confidence is below the `confidenceThreshold`. In that case, the only actions the user should be allowed to do is up stake it over the threshold and into the booted queue or down stake it into the regular queue (or into expiration)

**Comment by tibetsprague** [comment]
Are you sure about this? im pretty sure this causes a transaction revert

**Comment by tibetsprague** [comment]
Ah, so what happens is that it says that the staking transaction failed, but it moves the proposal to Boosted. so maybe we do want that and we just dont want to show an error?

**Comment by A-Zak** [comment]
Just to make sure I understand, the tx is reverting, but the proposal is moving to the boosted queue?
If not, what causes the error?

**Comment by A-Zak** [comment]
Making this a little more generic:
currently, both boosted and preBoosted proposals that have expired (require execution) show the voting buttons, but they have the "not-allowed" cursor, and they show the "enable predictions" button.

Boosted proposals - should have "Voting is disabled" and "Predictions are disabled" labels instead... :)
PreBooted proposals - should have both voting and staking enabled.

**Comment by tibetsprague** [comment]
well the staking doesnt happen and the client is expecting a Staking event to be fired so it fires an error.

**Comment by A-Zak** [comment]
This sounds like we're missing an event in the contracts O_O!
Can you send us a link to the tx?

Also, can you please deploy a version to staging that allows staking on these expired pre-boosted proposals so we can play with this and investigate...

**Comment by tibetsprague** [comment]
no I think this behavior is correct, it tries to stake, sees that the proposal is ready to be boosted, does that, and then doesn't do the staking because it doesnt need to happen anymore, its already boosted. So it's the client that needs updating to not error out on this case (@jellegerbrandy )

**Comment by A-Zak** [comment]
wait, I think we're talking about different things here......
In your scenario, you are correct. :)

I'm talking about the situation where you try to execute the pre-boosted proposal, but you can't because the proposals' score is lower than the scheme's `confidenceThreshold`.

(this can happen if proposals got added to the boosted queue, raising the `confidenceThreshold`)

In this case, you need to stake for the proposal, in order to raise its score above the `confidenceThreshold`, and only then it can be boosted.
(you can also `downStake` it out into the regular queue and possibly even expiration)

**Comment by tibetsprague** [comment]
right, so the question is do we need to track this scenario and disable or enable staking based on it? that will have to wait until we have the threshold stuff all working correctly. or we could just leave staking enabled for preboosted proposals always, and just not error out in the case when it boosts instead of staking

**Comment by A-Zak** [comment]
> just leave staking enabled for preboosted proposals always, and just not error out in the case when it boosts instead of staking
💪

**Comment by brodeur** [comment]
Not sure why I am in this ticket? Did I miss something?

**Comment by tibetsprague** [comment]
@brodeur removing you

**Comment by tibetsprague** [comment]
this is waiting on the threshold stuff being added to the client so we correctly know when to hide and show these buttons https://github.com/daostack/client/issues/103

**Comment by A-Zak** [comment]
#560 supersedes this
