### ISSUE TITLE
Show `Voting is Disabled` text when voting is disabled

### ISSUE THREAD

**Issue by tibetsprague** [daostack/alchemy#534]
Instead of buttons that you can't click on. @A-Zak do we also want a tooltip explaining why voting is disabled? there are numerous possible reasons. Same with staking

**Comment by A-Zak** [comment]
yeah, if it's simple then yes please :) 🙏

**Comment by A-Zak** [comment]
Looks great!
Can you please give me a list of the scenarios that disable the voting? I'd like to test them and see if the warning makes senes :)

**Comment by A-Zak** [comment]
@tibetsprague

**Comment by tibetsprague** [comment]
!currentAccountState ?
        "Cannot vote - please log in" :
      currentVote ?
        "Can't change your vote" :
      currentAccountState.reputation.eq(new BN(0)) ?
        "Voting requires reputation in " + dao.name :
      proposal.stage === IProposalStage.ExpiredInQueue || (proposal.stage === IProposalStage.Boosted && expired) ?
        "Can't vote on expired proposals" :
      proposal.stage === IProposalStage.Executed ?
        "Can't vote on executed proposals" (this one should never actually show since the proposal moves to the history)
      isVoting ?
        "Warning: Voting for this proposal is already in progress" (we don't support this one yet)
