### ISSUE TITLE
Enable to run against local nodes without MetaMask

### ISSUE THREAD

**Issue by dkent600** [daostack/alchemy#54]
Currently can't connect.

**Comment by dev-matan-tsuberi** [comment]
Is this supposed to be in the Vanille repo? because it's tagged as "vanille" in trello.

**Comment by tibetsprague** [comment]
you mean connecting to Parity or geth? I haven't tested this

**Comment by dkent600** [comment]
@dev-matan-tsuberi 

> Is this supposed to be in the Vanille repo? because it's tagged as "vanille" in trello.

Vanille needs the change and will code against it, hence the ticket in Vanille.

**Comment by dkent600** [comment]
@tibetsprague 

> you mean connecting to Parity or geth?

Yes, for me, parity.

**Comment by dkent600** [comment]
Sheesh, I meant to create this in the Vanille repo.  Vanille used to be called Alchemy.

**Comment by dkent600** [comment]
Alchemy would only need this if your node is using a different port number than 8545, you want to use the same port numbers as Arc.js uses (maybe because you are doing migrations), and you want to specify which network you are using by the network name, like "kovan", given in the OS env or your build script command, perhaps poked into the app via webpack.
