### ISSUE TITLE
production instance does not warn if connected to rinkeby istead of main net

### ISSUE THREAD

**Issue by jellegerbrandy** [daostack/alchemy#555]

**Comment by A-Zak** [comment]
would this also disable all action buttons if the user is on the wrong network?

**Comment by jellegerbrandy** [comment]
it should. It does not disable the button itself - instead of opening MM, the button will open a warning saying that you are connected to the wrong place.

**Comment by tibetsprague** [comment]
this was fixed by https://github.com/daostack/alchemy/pull/563
but the buttons at this point only warn when you try to actually do the transaction. probably we should disable buttons? though its kind of nice for people to see what actions they could do if only they had metamask setup correctly...

**Comment by jellegerbrandy** [comment]
closing this issue as it is resolved, if you guys want to continue the conversation we can open a new issue
