### ISSUE TITLE
check if MM is set up well before opening "create proposal" modal

### ISSUE THREAD

**Issue by jellegerbrandy** [daostack/alchemy#558]
We need to do the same check as for the other action buttons (i.e. call `checNetworkAndWarn()` before opening the modal).

This check may also be misssing on some other action buttons - it needs a systematic check

**Comment by A-Zak** [comment]
This check should happen before all the following actions:
• "Create proposal" button clicked (this ticket)
• Approve gen
• Stake (up / down)
• Vote (for / against)

Anything I've missed?

**Comment by jellegerbrandy** [comment]
* boost
* execute
* claim rewards

**Comment by tibetsprague** [comment]
I actually think its kind of cool the way we do it now where we only do the check and show the warning when they try to do the transaction. this way someone can see how the  app works without needing metamask setup and get more excited about it...

**Comment by A-Zak** [comment]
@jellegerbrandy 💪 
@tibetsprague yes I agree, we should allow the user to see the actions they can take, and we should show the warning as we do now. But for the create proposal button, this feels a little frustrating (especially now that changing networks would remove all the data entered in the proposal dialogue)...

does this make sense?
