### ISSUE TITLE
alchemy is not checking for network connection anymore

### ISSUE THREAD

**Issue by jellegerbrandy** [daostack/alchemy#562]
reproduce:

- have MM open and connected to main net
- visit https://daostack-alchemy-staging.herokuapp.com
- click on log in
- be NOT warned about the fact that you are connected to main while it should be rinkeby

it's a regression bug (=this used to work), we should have had a test

**Comment by tibetsprague** [comment]
How could we have a test? We don't use metamask in tests. Not sure if we can.

**Comment by dkent600** [comment]
Perhaps you can mock MM behavior (inject a mock web3 instance)

**Comment by tibetsprague** [comment]
Fixed by https://github.com/daostack/alchemy/pull/563

**Comment by A-Zak** [comment]
looks good! :)
