### ISSUE TITLE
Hide MetaMask login button if connected to wrong network

### ISSUE THREAD

**Issue by tibetsprague** [daostack/alchemy#564]
@A-Zak do you agree with this? Or should we change the text or something? The action required of them is different from logging in, its to change the network

**Comment by jellegerbrandy** [comment]
I'd just keep the text on the button as it is - but show a warning "please choose network XXX" and then (perhaps) opening metamask..

**Comment by A-Zak** [comment]
Yes, I think adding a big warning would be the best solution here... something that'll grab the user's attention... :)
