### ISSUE TITLE
The pre transaction modal for redeemptions looks wack

### ISSUE THREAD

**Issue by tibetsprague** [daostack/alchemy#569]
it has a little baby Genesis Protocol window sticking out next to it in a weird way with no content. For one issue.

**Comment by A-Zak** [comment]
yeah, that's a new one...
@brodeur please disable the side panels on all the popups (vote, stake, redeem, anything else)?

**Comment by brodeur** [comment]
Done.

**Comment by A-Zak** [comment]
💪
