### ISSUE TITLE
Small visual bugs in the staking popup

### ISSUE THREAD

**Issue by A-Zak** [daostack/alchemy#573]
<img width="536" alt="Screenshot 2019-04-10 at 10 29 04" src="https://user-images.githubusercontent.com/302774/55859893-b195cb80-5b7b-11e9-8f72-cb8a5678a2fe.png">

**Comment by tibetsprague** [comment]
I already fixed the erroneous error, and i working on formatting the amount to boost

**Comment by tibetsprague** [comment]
PR out
