### ISSUE TITLE
Can't stake small amounts :)

### ISSUE THREAD

**Issue by A-Zak** [daostack/alchemy#575]
<img width="501" alt="Screenshot 2019-04-10 at 11 20 26" src="https://user-images.githubusercontent.com/302774/55863289-e9544180-5b82-11e9-97c5-774650c23cb6.png">
<img width="974" alt="Screenshot 2019-04-10 at 11 20 34" src="https://user-images.githubusercontent.com/302774/55863295-ec4f3200-5b82-11e9-9421-1c26717d5f4b.png">

**Comment by jellegerbrandy** [comment]
Seems fixed
