### ISSUE TITLE
DAO holding aren't always updated / not precise 

### ISSUE THREAD

**Issue by A-Zak** [daostack/alchemy#576]
@jellegerbrandy @tibetsprague 
<img width="251" alt="Screenshot 2019-04-10 at 11 46 10" src="https://user-images.githubusercontent.com/302774/55865067-5a492880-5b86-11e9-94b7-524b88b2e16e.png">

Two things wrong with this image:
1. eth holdings is not displaying (sometimes it is, but most times it isn't)
2. gen amount is a little wrong ([avatar balance on etherscan](https://rinkeby.etherscan.io/token/0x543ff227f64aa17ea132bf9886cab5db55dcaddf?a=0xb89370c74d929ca24daeb000e8f90b8c9685d375), [snapshot image](https://user-images.githubusercontent.com/302774/55865267-aac08600-5b86-11e9-8f4c-255ff140908f.png))

What happened is I was unable to completely redeem my rewards because the dao had no gen to reward me with. so I transferred the dao 10 gen, which updated the balance correctly (10 gen).
I then was able to redeem my rewards, but after doing that the balance did not update.
I then transferred 1 more gen to the avatar (thinking that it will update to the correct amount) but it didn't, it updated it to 11 gen.

@orenyodfat I assume this second bug is related to the graph node, but I'm not sure.

**Comment by A-Zak** [comment]
@jellegerbrandy / @tibetsprague ?
^_^

**Comment by jellegerbrandy** [comment]
It may have to do with the new rounding logic, see also #577

**Comment by A-Zak** [comment]
@jellegerbrandy doesn't seem like there's much rounding going on [here](https://github.com/daostack/alchemy/blob/dev/src/lib/util.ts#L96), but I've asked tibet to confirm on #510...

**Comment by tibetsprague** [comment]
I think this is a client issue: https://github.com/daostack/client/issues/168

**Comment by pat-daostack** [comment]
I can confirm this issue is still ongoing with multiple users.

**Comment by dkent600** [comment]
This ticket is months old. The code involved has changed significantly. I just confirmed the values for Genesis Alpha are displaying perfectly on mainnet. I have no other way of reproducing this issue. So I’m declaring it fixed until further evidence is provided to the contrary.

**Comment by orenyodfat** [comment]
<img width="148" alt="Screen Shot 2019-10-12 at 23 15 09" src="https://user-images.githubusercontent.com/5994398/66707281-b9127900-ed46-11e9-80ff-f6244407af25.png">

still :(
