### ISSUE TITLE
rounding is not perfect yet

### ISSUE THREAD

**Issue by jellegerbrandy** [daostack/alchemy#577]
![image](https://user-images.githubusercontent.com/1306173/55867021-e9a00d00-5b81-11e9-9b31-871bdc0dafd3.png)

**Comment by A-Zak** [comment]
So this specific behaviour (~0.001 instead of 0) should already be fixed in #571 which just needs to be reviewed & merged.
But even when it works, it doesn't look so good, and I've found an alternative solution which I think is better, see #510 ^_^
