### ISSUE TITLE
Start collecting crash reports

### ISSUE THREAD

**Issue by A-Zak** [daostack/alchemy#583]
I've invited you to sentry.io
they are awesome ;)

we just need to go through this little guide, and we should have it installed :)

https://sentry.io/onboarding/daostack-technologies/react/configure/javascript-react/

**Comment by A-Zak** [comment]
@tibetsprague I see you're already part of the team (probably thanks to Adam), but I'd love it if you could integrate their snippet in as well...

@jellegerbrandy @brodeur you're also part of the team here on sentry, so feel free to check it out and let me know what you think of it (probably after we integrate it and start getting some actual data)...

**Comment by A-Zak** [comment]
So just to mention, customizing sentry could be a big project, which you might not want (and we might not need) to take up right now, but I will mention one nice one, and that is - attributes, and even more specific than that - the environment attribute... :D

attributes basically allow to later filter your errors and events, and filtering by the environment is really useful :)

**Comment by tibetsprague** [comment]
also i think we want separate projects for staging and production, right?

**Comment by tibetsprague** [comment]
i created a second project for staging
