### ISSUE TITLE
Integrate with mixpanel for analytics

### ISSUE THREAD

**Issue by A-Zak** [daostack/alchemy#584]

**Comment by A-Zak** [comment]
@tibetsprague I've sent you an invite to mixpanel (please accept it soon, I took my time and got it expired 😅)...
These are the [instructions to set it up](https://mixpanel.com/report/1956491/setup/quick/)...

Mixpanel should pick up all the url changes and buttons, but we should verify it on staging...
So for now, the only important customization I think we need is calling the identify method. later we can add more stuff, but for this will do... :)

**Comment by A-Zak** [comment]
Also, please note I created two projects - one for production and one for staging... ^_^

**Comment by tibetsprague** [comment]
@A-Zak you are saying that without any work Mixpanel will track clicks on any button and going to any URL? where do you see that?

**Comment by tibetsprague** [comment]
I kind of think we cant push this one out until we are at least tracking a few basis actions, how about proposal creation, voting, staking and redeeming?

**Comment by jellegerbrandy** [comment]
Not against this per se, but please note that these things are not free - they imply extra code to load, and for each thing that we track _another_ call to a server...
