### ISSUE TITLE
should not wait for metamask connection status to show the page

### ISSUE THREAD

**Issue by jellegerbrandy** [daostack/alchemy#587]
I've had this (maybe hard to reproduce) behavior where metamask was not responding and the app stayed on "checking connection status".

There is no need to wait at all for metamask do do anything _before_ loading the application..

**Comment by dkent600** [comment]
MM will hang for a long time when it can't connect to the selected network.  This often happens to me when I've told it to connect to localhost but no local node (like ganache) is running.
