### ISSUE TITLE
Reward display doesnt always update after redeeming

### ISSUE THREAD

**Issue by tibetsprague** [daostack/alchemy#588]
In particular it continues to show the Beneficiary reward even though it has already been sent to them

**Comment by jellegerbrandy** [comment]
I don't really get where this is (not) happening.

**Comment by tibetsprague** [comment]
In the proposal card on the redemptions page

**Comment by jellegerbrandy** [comment]
Ok, this actually needs a lot of logic that we do not have yet, starting from client issue https://github.com/daostack/client/issues/239

**Comment by jellegerbrandy** [comment]
seems to work now, closing it until further notice
