### ISSUE TITLE
Optimisation

### ISSUE THREAD

**Issue by jellegerbrandy** [daostack/alchemy#592]
# Some issues we should/could look at:

## bundle size

See issue #529 

Also, it often takes 20 seconds to download the (1.9mb compressed) bundle. We need to figure out why

- lose some dependencies
- have webpack zip the thing

## web sockets

We should look at how many websockets we are actually keeping open in alchemy, if we close them correctly, if we are not opening and closing them unecessary when re-rendering components, etc.

## apollo cache handling

Apollo provides very precise control over the cache, and we should use that to optimize the application. 

in particular, one model to try out is to set up a few "global" web subscriptions that provde all the ncessary data, and use `cache-only` queries for each of the components.

## refactor components

[...]

## linting

Not so much an optimization, more a code cleanup. Forbidding unused imports and variables can help us loosing unused packages or code.

## specific improvements

* The history page shows proposals that have static data, so it does not need to keep a subscription open for all proposal data.
* we can (probably) remove `operationsTracker` and other middleware (in configureSTore.ts)

**Comment by tibetsprague** [comment]
Can add things like the following .tsconfig:
    "forceConsistentCasingInFileNames": true,
    "noImplicitReturns": true,
    "noImplicitThis": true,
    "noImplicitAny": true,
    "strictNullChecks": true,
    "suppressImplicitAnyIndexErrors": true,
    "noUnusedLocals": true,
    "declaration": true,
    "allowSyntheticDefaultImports": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true
