### ISSUE TITLE
Getting feedback from vote made /bug

### ISSUE THREAD

**Issue by NathaliaScherer** [daostack/alchemy#596]
I voted for a proposal, but even after the transaction was made (got metamask confirmation) there was no feedback on the UI about it happening and it let me go through the process of voting again. 
<img width="1440" alt="Screen Shot 2019-04-13 at 8 34 01 AM" src="https://user-images.githubusercontent.com/35570812/56081218-0e85c180-5dc8-11e9-84dd-15fdae7afec7.png">

**Comment by jellegerbrandy** [comment]
either a fluke or it is fixed :-)
