### ISSUE TITLE
Scheme registrar

### ISSUE THREAD

**Issue by A-Zak** [daostack/alchemy#599]
Todo
======
- [x] Client support for creating a scheme registrar support
- [x] New proposal
- [x] Proposal Card
- [x] Proposal Details

Scheme Registrar specs
===================

Scheme registrar queue has three proposal types: Add scheme, remove scheme and edit scheme.
The three proposal types are accessible in the same create proposal form, via the tabs on the bottom part of the form.

Scheme registrar proposals
======================
* Remove scheme (tab title)
    * zeplin - https://zpl.io/2GyzQL4
    * Parameters
        * Scheme to remove (select)
            * The user can select one of the existing schemes
            * the list should display the scheme names or address if no name
    * Proposal summary
        * Icon - Trash icon
        * Text - Remove scheme
        * Extended details (proposal details):
            * Scheme name or address + link to etherscan + icon for is varified
* Add scheme (tab title)
    * Zeplin - https://zpl.io/2p4oOEQ
    * Parameters
        * Scheme to add (select / text)
            * The user can select one from the supported schemes (scheme registrar, generic action & contribution reward)
            * The user can select other, and supply the address of the new scheme (zeplin - https://zpl.io/2GyzAA4)
        * Parameter hash (text)
            * The parameter hash to use with the scheme
        * Scheme permissions (checkboxes)
            * The user can select which permissions to give the scheme
    * Proposal summary
        * Icon - plus icon
        * Text - Add scheme
        * Extended details (proposal details):
            * Scheme name
            * Scheme address + link to etherscan + icon for is verified
            * Param hash (can we read params? Doesn't have to be now)
            * The scheme permissions 
* Edit scheme (tab title)
    * Edit scheme is very similar to add scheme (uses the same method). The differences are:
    * Parameters
        * Scheme to add (select)
            * The user can only select one of the schemes in the dao
    * Proposal summary
        * Icon - pencil icon
        * Text - Edit scheme

**Comment by A-Zak** [comment]
Some UI bugs:
![image](https://user-images.githubusercontent.com/302774/57622691-d2947680-7596-11e9-8e65-c623063685f3.png)
![image](https://user-images.githubusercontent.com/302774/57633609-78061500-75ac-11e9-8091-63a49b759c3b.png)

**Comment by tibetsprague** [comment]
@A-Zak parameter hash is required

**Comment by leviadam** [comment]
@tibetsprague 
Why is it required?
If it is empty we can just have zero, some schemes do not need params.

**Comment by jellegerbrandy** [comment]
done
