### ISSUE TITLE
Generic Action (dxDAO)

### ISSUE THREAD

**Issue by A-Zak** [daostack/alchemy#600]
Todo
======
- [ ] New proposal
- [ ] Proposal Card
- [ ] Proposal Details

Generic scheme specs
==================

The generic scheme queue (for the dxDAO) will feature 4 proposal categories, with a total of 7 types of proposals (details below).

When clicking the create new proposal button it should show the list of categories. Changing between the proposal types within the category is done within the proposal creation form (via the tabs on the bottom part of the form).

The design for proposal summary (on proposal cards and proposal details page) will vary mostly on icons and text (details below).

The design for creating these proposals is just like the scheme registrar with differences in titles tabs and fields (zeplin - https://zpl.io/a7WJRQ8).

Upgrade the DutchX (category)
=========================
* Update mastercopy (tab title)
    * (wait for 30days, after the cooldown an additional tx is required to make it effective. in the future this might be possible from within alchemy, but not for now).
    * Parameters
        * New Contract address
    * Proposal summary
        * Icon - edit pencil
        * Text - Update Mastercopy 
        * Extended details (proposal details):
            * New master copy address -> link to etherscan + icon for is verified
* Change ETH:USD oracle (tab title)
    * Same as above except:
    * Proposal summary
        * Text - Change ETH:USD oracle
* Change DutchX owner (tab title)
    * Parameters
        * New owner address
    * Proposal summary
        * Icon - edit pencil
        * Text - Change DutchX owner
        * Extended details (proposal details):
             * New owner address -> link to etherscan

Update whitelisted tokens
=====================
* Add tokens
    * Parameters
        * Token address(s)
            * Should start as one field, and a plus button to add another field
    * Proposal summary
        * Icon - plus icon
        * Text - Whitelist 5 token(s) - only show 's' if more then one token
        * Extended details (proposal details):
            * List of tokens to be added with links to etherscan
* Remove tokens
    * Same as above except:
    * Proposal summary
        * Icon - minus icon
        * Text - Delist 3 tokens(s)

Update thresholds
===============
* Update new token pair threshold
    * Parameters
        * New threshold
            * Value in USD (contract expects the value * 10^18)
    * Proposal summary
        * Icon - pencil icon
        * Text - Set new token pair threshold to $7.4k
* Update new auction threshold
    * Same as above except:
    * Proposal summary
        * Text - Set new auction threshold to $3.2k

**Comment by jellegerbrandy** [comment]
If we can get rid of the tabs, this would b great.  One way would be change the "upgrade to dutchX" action into two different proposals (in the UX)

**Comment by tibetsprague** [comment]
probably would be good in the future to show the current values for all these things. like the current token pair threshold, current owner, current mastercopy... we do need to know the current set of whitelisted tokens already, so ill have to figure out how to get that @jellegerbrandy

**Comment by tibetsprague** [comment]
@A-Zak could use placeholder text for each field in the form

**Comment by jellegerbrandy** [comment]
Ok, so here's some questions regarding the relatino between the contract and the form

* update eth:usd oracle is a two-step process. See the contract here: https://github.com/gnosis/dx-contracts/blob/master/contracts/base/EthOracle.sol.
The proposal will propose to initalize the process; we have no clear way of calling (or deciding who will call) the update step.
* same with updating the master copy
* add, remove tokens: These are implemented as a single function: https://github.com/gnosis/dx-contracts/blob/master/contracts/base/TokenWhitelist.sol, whether it concerns "add"  or "remove" dpends on the parameter. It would fit our generic apporach better is this were also just a single form in the UX ("Add or remove tokens,", with a picklist "with values "add" and "remove" + a token list as input)

**Comment by tibetsprague** [comment]
these seem like major issues. the token one i  do still think it makes sense to have two separate tabs, one for add and one for remove, since the TokenWhitelist function only does one or the other at a time with an array of addresses

**Comment by leviadam** [comment]
This is already implemented in #718.
