### ISSUE TITLE
Some proposals are missing in the queue O_O

### ISSUE THREAD

**Issue by A-Zak** [daostack/alchemy#603]
Some of the proposals are missing from the queue. The count seems to be correct (currently 10), but only shows 6 proposals. 

For example this one: 0xf038967ac6e37121f54d5d4168df9d717282d63fac3f01f4c7e4b216268dfe6a

**Comment by jellegerbrandy** [comment]
For reference, this is the (ALMOST) the query: 

https://subgraph.daostack.io/subgraphs/name/v9/graphql?query=%7B%20%20proposals%20(where%3A%20%7B%20stage%3A%20%22Queued%22%20%7D)%20%7B%0A%20%20%0A%20title%0A%20%20expiresInQueueAt%0A%7D%0A%7D

It seems the total number is right, but we are indeed not rendering all proposals.

**Comment by jellegerbrandy** [comment]
(note that we are not showing ALL queued proposals under "regular proposals" - we are showing only those that are not `expiredInQueue`)

**Comment by A-Zak** [comment]
Right, but this proposal is still way before it's `expiredInQueue` (May 5th)...

@tibetsprague can you take a look... also, if you [navigate to directly](https://alchemy.daostack.io/dao/0x294f999356ed03347c7a23bcbcf8d33fa41dc830/proposal/0xf038967ac6e37121f54d5d4168df9d717282d63fac3f01f4c7e4b216268dfe6a), it seems like we do get the proposal title in the breadcrumbs, but not the proposal container...
Seems something is crashing while rendering it...

**Comment by A-Zak** [comment]
Maybe a clue - I'm pretty sure this proposal has been boosted and then unboosted...
hope this helps...

**Comment by tibetsprague** [comment]
PR out and ready to go pending a review
