### ISSUE TITLE
proposal stake test is not working well

### ISSUE THREAD

**Issue by jellegerbrandy** [daostack/alchemy#625]
I commented this out. It is failing because the user does not seem to ahve an allowance set (so the stake button is hidden behing "enable predictions")

This is the second time this test is failing;  perhaps because we are depending on the allowance to have been set in our ganache image (and that may have chanaged). The solution is to make sure at the start of the test that the default account has its allowance set.

this is in `test/integration/proposal.ts`

**Comment by tibetsprague** [comment]
sounds like this is because of the allowance bug in the client, so its a real bug

**Comment by jellegerbrandy** [comment]
return values of the allowanc() function changed, so it was in easy fix in alchemy

**Comment by jellegerbrandy** [comment]
this will teach me to NEVER COMMENT OUT TESTS
