### ISSUE TITLE
Vote failed.  Alchemy should set a better default gas price?

### ISSUE THREAD

**Issue by dkent600** [daostack/alchemy#627]
I tried to vote and Alchemy reported the attempt to vote had failed.  The js console showed the following message:

>Transaction was not mined within 50 blocks, please make sure your transaction was properly sent. Be aware that it might still be mined!

This usually happens when the gasPrice is too low.  Does Alchemy not attempt to set a reasonable default gas price?

**Comment by leviadam** [comment]
It actually does.
It gets it from EthGasStation's api, which usually is pretty good.

**Comment by dkent600** [comment]
EthGasStation lets you choose between various pricess that yield slow, medium and fast mining.  I wonder which we're using?

**Comment by dkent600** [comment]
@leviadam I just searched through the master branches of Alchemy, client and subgraph, and EthGasStation is nowhere used.

**Comment by dkent600** [comment]
Maybe you are thinking of the dxDAO UI, which *does* use it.

**Comment by leviadam** [comment]
Indeed. The old alchemy did use it I think.
Here it seems it counts on the web3 provider to choose the gas price correctly.

**Comment by dkent600** [comment]
Yes, the old Alchemy used it via arc.js which had that build-in.

**Comment by jellegerbrandy** [comment]
We are counting on metamask to provide a good gas price, we are not guessing it ourselves. 

We do not have any other reports on this, afaik. You just seem to have been unlucky :cry:
