### ISSUE TITLE
Expired proposals that I have staked on - should appear in the redemptions and allow me to redeem my gens back

### ISSUE THREAD

**Issue by A-Zak** [daostack/alchemy#643]
@jellegerbrandy do we need any new info from the subgraph?

**Comment by jellegerbrandy** [comment]
And yes, I just realized we do: https://github.com/daostack/subgraph/issues/273

**Comment by jellegerbrandy** [comment]
@A-Zak , this should be fixed in https://github.com/daostack/alchemy/pull/840, but I have no account with an expired proposal to test it with, do you have an example?
