### ISSUE TITLE
Support filtering DAO list by Registry

### ISSUE THREAD

**Issue by dOrgJelli** [daostack/alchemy#645]
**Thought:** On the front-page of Alchemy where the list of DAOs is shown, have a list filter where the user can choose what DAOregistry they're interested in. For example: "show all DAOs within the Genesis DAO's network (registry)".

Please respond with your thoughts in the comments. If you agree, we can improve the spec here and add mocks.

**Comment by A-Zak** [comment]
let's start by first supporting a single dao registry... :P

**Comment by dOrgJelli** [comment]
Agreed :) Just wanted to document the idea of supporting multiple registries.
