### ISSUE TITLE
Change supported exchanges

### ISSUE THREAD

**Issue by pat-daostack** [daostack/alchemy#651]
The current exchange list is:

IDEX
DDEX
Forkdelta
Etherdelta
Hotbit

Should be changed to, in this order, with these URLs:

IDEX https://idex.market/eth/gen
Liquid https://app.liquid.com/exchange/GENETH
Slow.trade https://slow.trade/#/
EthFinex https://www.ethfinex.com/
Coinswitch https://coinswitch.co/coins/daostack/ethereum-to-daostack

**Comment by pat-daostack** [comment]
I would add Uniswap to this once it is added.

Please consider prioritizing this with the launch of the PolkaDAO.

**Comment by leviadam** [comment]
This is implemented already.
