### ISSUE TITLE
"execute" button does not appear automatically when timer runs out to 0

### ISSUE THREAD

**Issue by jellegerbrandy** [daostack/alchemy#663]
I see this:

![image](https://user-images.githubusercontent.com/1306173/56953913-d3acb900-6b3d-11e9-8134-07d3b2b71e14.png)

But expected to see this:

![image](https://user-images.githubusercontent.com/1306173/56953946-e6bf8900-6b3d-11e9-81f5-8e156f6f5b9b.png)

**Comment by tibetsprague** [comment]
because we dont show seconds, did you wait a minute? I think we just need to show seconds

**Comment by dkent600** [comment]
Why was this closed?
