### ISSUE TITLE
Figure out how to handle proposal "execution" when DAO doesnt have funds to reward

### ISSUE THREAD

**Issue by tibetsprague** [daostack/alchemy#669]
Right now if you try to Execute a proposal with ETH or external token rewards when the DAO doesn't have enough funds it reverts and hangs around in the boosted proposal sections. Ideally it would still execute and then move to the redemptions page. Sound right to you?

**Comment by jellegerbrandy** [comment]
This does not sound right to me at all - if I read the code of the Redeemr.sol contract, it should not revert, but simply not claim those rewards for which the balance is insufficient. 

Could it be reverting for some other reason?

**Comment by tibetsprague** [comment]
hmm, yeah I guess it could...
