### ISSUE TITLE
Pre-boost button does not disappear if there isn't enough GEN staked

### ISSUE THREAD

**Issue by pat-daostack** [daostack/alchemy#671]
When proposals in the regular queue have the option to be pre-boosted, the button appears; however, the button does not disappear if they fall under the threshold again (due to additional boosted proposals).

In short:

The pre-boosting button is not dynamically responsive to the threshold needed to boost.

**Comment by pat-daostack** [comment]
Currently using latest version of Brave desktop.

**Comment by jellegerbrandy** [comment]
should be fixed
