### ISSUE TITLE
remove migration dependency

### ISSUE THREAD

**Issue by jellegerbrandy** [daostack/alchemy#673]
We are now reading hte contract addresses from tthe migration repo. The client now supports getting these contracts from the subgraph itself, which is more elegant and less error prone. Use this.

**Comment by orenyodfat** [comment]
it is more than elegant. it is needed for supporting contract multiple versions feature which coming soon.
also for some cases like [here](https://github.com/daostack/subgraph/issues/221)  which might introduce some security risks for the users
