### ISSUE TITLE
Cannot save social verification

### ISSUE THREAD

**Issue by pat-daostack** [daostack/alchemy#683]
When a user fills out their social profile, they cannot save it. Screenshot of error messaging below:

https://lh6.googleusercontent.com/kYZFDC6O9ZeOoKPaypn8qyChF7Dz3ysK8L87g3jn9YV-5JSnHzLmwTyXtykRe8BRDm-4IKcnHhs5zEW9_VUUAaTaqWNbd3zF4CmbQHaEZQunLisPq3ApZQqq_Uj0NGZTwgdw2O8

**Comment by jellegerbrandy** [comment]
fixed, it seems
