### ISSUE TITLE
DAO does not display Reputation total

### ISSUE THREAD

**Issue by papa-raw** [daostack/alchemy#684]
There is no display of the DAO's current Reputation in the interface, so users cannot calculate how much Reputation to ask for when submitting proposals.

**Comment by pat-daostack** [comment]
We've received some additional user complaints around this missing feature from members of the PolkaDAO and the Genesis DAO.

One concern that was also raised is that when asking for Reputation it would be great to be able to put in a % and not just a lump sum, and that the UI needs a better tooltip regarding this in the proposal submission form.

**Comment by pat-daostack** [comment]
Please consider prioritizing this as incorrect Reputation request inputs is our number #1 user issue currently (users ask for a percent instead of a value as they cannot see a value to calculate off of)
