### ISSUE TITLE
Logo Proposal: Alchemy

### ISSUE THREAD

**Issue by baranpirincal** [daostack/alchemy#69]
Hey, I am graphic designer and my aim is make my portfolio better with supporting open source project in field of graphic. I can contribute on your project with making a logo design. I would be very pleased if you interested. I am waiting your feedback, have a nice day! :)

Best Regards,
Baran Pirincal
Visual Communication Designer

**Comment by tibetsprague** [comment]
@baranpirincal sorry we didn't respond sooner! we may be open to this, we just haven't had a chance to discuss yet as a team. would you still like to consider you and reach out when we are ready to work on branding?

**Comment by baranpirincal** [comment]
@tibetsprague Of course, feel free to contact with me. My mail should be listed on my GitHub profile.
