### ISSUE TITLE
gen to boost on failed (time out) proposal ? 

### ISSUE THREAD

**Issue by orenyodfat** [daostack/alchemy#691]
https://alchemy.daostack.io/dao/0xecd657fe5c8ea9bc62af84c06e2a2f48e57079fa/proposal/0x6d8ebe983a6f8063feffd4a97286914db40839ba5f9087aae3eabac72f616709

![Screen Shot 2019-05-12 at 13 29 41](https://user-images.githubusercontent.com/5994398/57581031-11a0ca00-74ba-11e9-8aae-a86b16566feb.png)

**Comment by orenyodfat** [comment]
In this case the user cannot claim back its stakes (false)

**Comment by A-Zak** [comment]
Is this issue about the label "11.4 GEN to boost"?

> In this case the user cannot claim back its stakes (false)

@orenyodfat what do you mean by this?

**Comment by orenyodfat** [comment]
> Is this issue about the label "11.4 GEN to boost"?

yes, and also a boost button appears. 

> Also
> @orenyodfat what do you mean by this comment?
> 
> > In this case the user cannot claim back its stakes (false)

in this case the user who downstake as no button to redeem back its stake.

**Comment by orenyodfat** [comment]
does these UIs issues are not covered by the manual UI tests spec ? is there such a spec ?

**Comment by jellegerbrandy** [comment]
This is a straighforward ui bug, let's fix it tomorrow.

**Comment by tibetsprague** [comment]
I'm actually still not clear what the issues are here

**Comment by orenyodfat** [comment]
1. no need to present predictions banner + boost button + gen to boost on already timed out proposal which is part of the history,
2. user which downstakes on timeout proposal should be able to get back their stakes somehow.. though there is no ui for that ..(it does not appears on the redemption tab)
