### ISSUE TITLE
Quick UI fixes

### ISSUE THREAD

**Issue by A-Zak** [daostack/alchemy#692]
- [x] Make all cards the same hight (proposal title - up to two lines, then elipsis)
<img width="602" alt="Screenshot 2019-05-13 at 18 54 23" src="https://user-images.githubusercontent.com/302774/57635824-a128a480-75b0-11e9-9126-4bf8b6d8268d.png">

- [x] hide progress bar on the top of the proposal cards
![image](https://user-images.githubusercontent.com/302774/57635911-d59c6080-75b0-11e9-904f-c57b219ded8f.png)

- [x] pass & fail graphs and text on the proposal card should be vertically aligned.
![image](https://user-images.githubusercontent.com/302774/57635886-c1586380-75b0-11e9-8296-3adc0112ff74.png)

- [ ] when proposal time is less than 1 hour, show hours, minutes & seconds.

- [x] Remove semicolon between daos
![image](https://user-images.githubusercontent.com/302774/57636039-11372a80-75b1-11e9-8304-7df269d47858.png)

- [x] Update pass / fall / for / against icons on proposal card (pass fail need the smaller icons, for against need the blue icons)
![image](https://user-images.githubusercontent.com/302774/57636188-55c2c600-75b1-11e9-846d-a20dfcda1a21.png)

- [x] DAO holdings in the sidebar should have some more padding when screen is too short to fit the entire bar
![image](https://user-images.githubusercontent.com/302774/57633898-f5ca2080-75ac-11e9-9f6d-568554f4c5a2.png)

- [ ] Reputation holders - sort by rep (high to low)
- [x] Reputation holders page - add title
![image](https://user-images.githubusercontent.com/302774/57636510-f31dfa00-75b1-11e9-97de-cc209e34cec8.png)

- [x] History page - end date, align left
![image](https://user-images.githubusercontent.com/302774/57636653-31b3b480-75b2-11e9-8df5-0df9e0f1c856.png)

- [x] History page - wrap / trim & add ellipsis when long data (e.g. 🐲👹 𝔥 υｔcｈ 👑☠)
![image](https://user-images.githubusercontent.com/302774/57636702-4d1ebf80-75b2-11e9-94f9-994171074a01.png)

- [x] Profile page - add some padding between avatar and details. also, remove redundant "social accounts" title
![image](https://user-images.githubusercontent.com/302774/57637119-42185f00-75b3-11e9-8a38-65afedc7eb74.png)

- [ ] "Loading" indicator - don't show the label, just nothing until it loads.

**Comment by brodeur** [comment]
https://github.com/daostack/alchemy/issues/705 - timer ticket
https://github.com/daostack/alchemy/issues/706 - reputation sortin ticket

@A-Zak I don't understand the last checkmark -- "Loading" indicator - don't show the label, just nothing until it loads. 

Can you share more about what that means?
