### ISSUE TITLE
Sorting :)

### ISSUE THREAD

**Issue by A-Zak** [daostack/alchemy#704]
DAOs
=======
- [ ] always put genesis on top
- [ ] the rest lets just sort alphabetically for now

Proposals
==========
- [ ] boosted & pre-boosted proposals - by time left - ending soon first.
- [ ] regular proposals should be sorted by confidence (upstake / downstake ratio) - highest first.

**Comment by leviadam** [comment]
Should we not sort DAOs by activity?

**Comment by jellegerbrandy** [comment]
done
