### ISSUE TITLE
PreBoosting button is on - while 'confidence' is not enough

### ISSUE THREAD

**Issue by naverachman** [daostack/alchemy#710]
![image](https://user-images.githubusercontent.com/20316906/57759606-e78e1880-7702-11e9-9a97-538536eb623f.png)

submitted by @orenyodfat and @Nave

**Comment by naverachman** [comment]
In addition, there should be a message "x GEN to boost" (here =1)

**Comment by orenyodfat** [comment]
this looks like a bug in GEN to boost calculation. @jellegerbrandy

**Comment by leviadam** [comment]
I think this was fixed. Right @jellegerbrandy ?

**Comment by tibetsprague** [comment]
Fixed by https://github.com/daostack/alchemy/pull/790
