### ISSUE TITLE
Redemptions page show a large "pending rewards" number I can't seem to redeem

### ISSUE THREAD

**Issue by parrachia** [daostack/alchemy#712]
![image](https://user-images.githubusercontent.com/9451597/57808236-4ec6bf80-7739-11e9-82b1-ab14dafe1ce4.png)
When I hover the mouse over the redeem buttons, it shows no gen reward and when I tried to execute them the tx went successfully but nothing changed on Alchy.
Last two attempts etherscan links: [(1)](https://etherscan.io/tx/0x036641534a0fadef6fa68be19677158e677e87b4eec422913e496ec0c112f160), [(2)](https://etherscan.io/tx/0x3a990f04278a81f065aec172db25db541f3888bd90cd5bde9cab1d67428689a6)

**Comment by parrachia** [comment]
@A-Zak asked me to post [my address](https://etherscan.io/address/0x144c4e5027b69f7798b2b162d924bcae5c149f15#tokentxns) and what do I think my rewards should be and why: 
I'm ok with what the UI shows in the image above (about 1k). Because it is proporcional to what I staked and, well, it's what the dapp is showing to me.

**Comment by jellegerbrandy** [comment]
I believe this is because the redemptions list shows proposals that already ahve been redeemed.  In that case, clicking the redeem button does nothing. This should be fixed by #778

**Comment by parrachia** [comment]
Sorry for the delay, it's still happening.
