### ISSUE TITLE
Can't submit a proposal

### ISSUE THREAD

**Issue by arsena21** [daostack/alchemy#713]
Getting this: http://prntscr.com/np5aos

Looks like a lot of errors are showing up in the console: http://prntscr.com/np5b51

[alchemy.daostack.io-1557968821378.log](https://github.com/daostack/alchemy/files/3184994/alchemy.daostack.io-1557968821378.log)

**Comment by jellegerbrandy** [comment]
Hi @arsena21 , this issue is very old, and, I assume, not relevent anymore. Thanks for reporting :-)
