### ISSUE TITLE
'new proposal' button should be disable if governance not started yet.

### ISSUE THREAD

**Issue by orenyodfat** [daostack/alchemy#737]
otherwise the proposal tx will revert. 
this depend on genesisProtocol activationTime parameter , which is currently under the proposal itself ...which does not help much in this case :)  

so first there is a need for https://github.com/daostack/subgraph/issues/239

**Comment by orenyodfat** [comment]
https://github.com/daostack/subgraph/blob/master/src/mappings/Controller/schema.graphql#L109

**Comment by dkent600** [comment]
This is already done.
