### ISSUE TITLE
Cannot redeem proposal if the token address is invalid

### ISSUE THREAD

**Issue by pat-daostack** [daostack/alchemy#758]
Trying to redeem this proposal:

https://alchemy.daostack.io/dao/0x294f999356ed03347c7a23bcbcf8d33fa41dc830/proposal/0x1a13d7f098a4379ab1fe96645bb80be1302a90e50521240ebb71c97149862a64

Receiving: "Reward: transaction failed :-(" error message

Console log:

inpage.js:1 MetaMask - RPC Error: gas required exceeds allowance or always failing transaction {code: -32000, message: "gas required exceeds allowance or always failing transaction"}code: -32000message: "gas required exceeds allowance or always failing transaction"__proto__: constructor: ƒ Object()hasOwnProperty: ƒ hasOwnProperty()isPrototypeOf: ƒ isPrototypeOf()propertyIsEnumerable: ƒ propertyIsEnumerable()toLocaleString: ƒ toLocaleString()toString: ƒ toString()valueOf: ƒ valueOf()__defineGetter__: ƒ __defineGetter__()__defineSetter__: ƒ __defineSetter__()__lookupGetter__: ƒ __lookupGetter__()__lookupSetter__: ƒ __lookupSetter__()get __proto__: ƒ __proto__()set __proto__: ƒ __proto__()
(anonymous) @ inpage.js:1
(anonymous) @ inpage.js:1
(anonymous) @ inpage.js:1
u @ inpage.js:1
(anonymous) @ inpage.js:1
We @ inpage.js:1
(anonymous) @ inpage.js:1
value @ inpage.js:1
(anonymous) @ inpage.js:1
n @ inpage.js:1
o @ inpage.js:1
(anonymous) @ inpage.js:1
(anonymous) @ inpage.js:1
n @ inpage.js:1
o @ inpage.js:1
(anonymous) @ inpage.js:1
(anonymous) @ inpage.js:1
(anonymous) @ inpage.js:1
(anonymous) @ inpage.js:1
u @ inpage.js:1
a @ inpage.js:1
(anonymous) @ inpage.js:1
(anonymous) @ inpage.js:1
(anonymous) @ inpage.js:1
r @ bundle-ea484ec6.js:77
setTimeout (async)
(anonymous) @ bundle-ea484ec6.js:77
(anonymous) @ inpage.js:1
write @ inpage.js:1
b @ inpage.js:1
(anonymous) @ inpage.js:1
g.write @ inpage.js:1
y @ inpage.js:1
(anonymous) @ inpage.js:1
s.emit @ inpage.js:1
w @ inpage.js:1
_ @ inpage.js:1
b.push @ inpage.js:1
_write @ inpage.js:1
b @ inpage.js:1
(anonymous) @ inpage.js:1
g.write @ inpage.js:1
y @ inpage.js:1
(anonymous) @ inpage.js:1
s.emit @ inpage.js:1
w @ inpage.js:1
_ @ inpage.js:1
b.push @ inpage.js:1
i._onMessage @ inpage.js:1
postMessage (async)
t._write @ contentscript.js:1
h @ contentscript.js:1
(anonymous) @ contentscript.js:1
W.write @ contentscript.js:1
G @ contentscript.js:1
(anonymous) @ contentscript.js:1
Z.emit @ contentscript.js:1
L @ contentscript.js:1
I @ contentscript.js:1
h.push @ contentscript.js:1
_write @ contentscript.js:1
h @ contentscript.js:1
(anonymous) @ contentscript.js:1
W.write @ contentscript.js:1
G @ contentscript.js:1
(anonymous) @ contentscript.js:1
Z.emit @ contentscript.js:1
L @ contentscript.js:1
I @ contentscript.js:1
h.push @ contentscript.js:1
_write @ contentscript.js:1
h @ contentscript.js:1
(anonymous) @ contentscript.js:1
W.write @ contentscript.js:1
G @ contentscript.js:1
(anonymous) @ contentscript.js:1
Z.emit @ contentscript.js:1
L @ contentscript.js:1
I @ contentscript.js:1
h.push @ contentscript.js:1
t._onMessage @ contentscript.js:1
bundle-ea484ec6.js:77 Reward: transaction failed :-(
(anonymous) @ bundle-ea484ec6.js:77
(anonymous) @ bundle-ea484ec6.js:41
t.__tryOrUnsub @ bundle-ea484ec6.js:16
t.error @ bundle-ea484ec6.js:16
t._error @ bundle-ea484ec6.js:16
t.error @ bundle-ea484ec6.js:16
(anonymous) @ bundle-ea484ec6.js:107
(anonymous) @ bundle-ea484ec6.js:107
(anonymous) @ bundle-ea484ec6.js:107
o @ bundle-ea484ec6.js:107
Promise.then (async)
c @ bundle-ea484ec6.js:107
s @ bundle-ea484ec6.js:107
Promise.then (async)
c @ bundle-ea484ec6.js:107
o @ bundle-ea484ec6.js:107
Promise.then (async)
c @ bundle-ea484ec6.js:107
(anonymous) @ bundle-ea484ec6.js:107
r @ bundle-ea484ec6.js:107
(anonymous) @ bundle-ea484ec6.js:107
e._trySubscribe @ bundle-ea484ec6.js:16
e.subscribe @ bundle-ea484ec6.js:16
(anonymous) @ bundle-ea484ec6.js:41
(anonymous) @ bundle-ea484ec6.js:41
r @ bundle-ea484ec6.js:41
(anonymous) @ bundle-ea484ec6.js:41
(anonymous) @ bundle-ea484ec6.js:306
(anonymous) @ bundle-ea484ec6.js:41
(anonymous) @ bundle-ea484ec6.js:63
o @ bundle-ea484ec6.js:63
Promise.then (async)
c @ bundle-ea484ec6.js:63
(anonymous) @ bundle-ea484ec6.js:63
r @ bundle-ea484ec6.js:63
handleClickAction @ bundle-ea484ec6.js:63
(anonymous) @ bundle-ea484ec6.js:128
d @ bundle-ea484ec6.js:128
(anonymous) @ bundle-ea484ec6.js:128
D @ bundle-ea484ec6.js:128
k @ bundle-ea484ec6.js:128
x @ bundle-ea484ec6.js:128
M @ bundle-ea484ec6.js:128
wn @ bundle-ea484ec6.js:128
Ls @ bundle-ea484ec6.js:128
Ne @ bundle-ea484ec6.js:128
kn @ bundle-ea484ec6.js:128
(anonymous) @ bundle-ea484ec6.js:128
t.unstable_runWithPriority @ bundle-ea484ec6.js:142
Vs @ bundle-ea484ec6.js:128
En @ bundle-ea484ec6.js:128
r @ bundle-ea484ec6.js:77
bundle-ea484ec6.js:77 Returned error: gas required exceeds allowance or always failing transaction

**Comment by jellegerbrandy** [comment]
Actually, this fails because the token address is not valid (it tries to distribute a token that does not exist)

**Comment by jellegerbrandy** [comment]
Ok, closing this. We fixed the part where these corrupt prposals are created by accident, and @A-Zak is preparing a post with an explantion of how to fix this in individual cases
