### ISSUE TITLE
Need to change copy of bottom warning label

### ISSUE THREAD

**Issue by pat-daostack** [daostack/alchemy#761]
The bottom warning label is confusing users of other DAOs, as it implies that their Reputation will be slashed (this is not the case). This copy was Genesis exclusive. Additionally, the copy is not relevant enough.

Suggested new copy:

Alchemy and Arc are in Alpha. There will be BUGS!  We don't guarantee complete security. *Play at your own risk*

**Comment by jellegerbrandy** [comment]
done
