### ISSUE TITLE
bug in schemeregistrar proposal

### ISSUE THREAD

**Issue by jellegerbrandy** [daostack/alchemy#765]
Oren reports "
I asked only for generic call permission and it say I asked for all
"

**Comment by jellegerbrandy** [comment]
@orenyodfat 

This may be just a visualization bug, and fixed with this PR: https://github.com/daostack/alchemy/pull/764

**Comment by orenyodfat** [comment]
thanks . please confirm though the proposal is correct on the blockchain.

**Comment by leviadam** [comment]
I'm assuming this is fixed @jellegerbrandy?

**Comment by jellegerbrandy** [comment]
fixed
