### ISSUE TITLE
cannot comment as guest on discuss 

### ISSUE THREAD

**Issue by orenyodfat** [daostack/alchemy#768]

**Comment by pat-daostack** [comment]
This is arguably on purpose, as it serves as a spam protection measure.

**Comment by orenyodfat** [comment]
well, it say that the comment need to be "moderate" . 
where can I find the "moderators" list ?

if this is a feature (which I am not sure) there need to be some text re that and disable this option at all.

**Comment by A-Zak** [comment]
Since we're not monitoring these guest comments, I disabled this feature....
In the future, if you'll want to comment @orenyodfat, you'll have to login... :)

**Comment by orenyodfat** [comment]
or find someone to delegate my comment :)

**Comment by A-Zak** [comment]
haha, yes, that is also an option :)
