### ISSUE TITLE
should be feedback on what one has staked on a proposal

### ISSUE THREAD

**Issue by dkent600** [daostack/alchemy#769]
I staked on a proposal (demonstrated on etherscan) but can see no feedback on Alchemy to confirm that I did so.  It seems important that the user be able to know that Genesis has recorded the stake.

![image](https://user-images.githubusercontent.com/1821666/58703341-595a9900-8376-11e9-8c83-172387848d90.png)

**Comment by jellegerbrandy** [comment]
We get feedbackw hen the tx is mined. It is true that alchemy does not show how much you actually staked before, which is annoying, but I'd consider that a separate feature, and I don't think it fits in the LTS (@A-Zak ?)
