### ISSUE TITLE
should be feedback that a transaction is underway

### ISSUE THREAD

**Issue by dkent600** [daostack/alchemy#770]
When I vote or stake on a proposal, there is no indication, until the tx has been mined, that the transaction is being processed.  It seems important to me that the user understand that something is actually happening.

**Comment by jellegerbrandy** [comment]
there should be. Do you see this behavior only on voting or staking, or with all transactions?

**Comment by jellegerbrandy** [comment]
closing this bc inactivity

**Comment by dkent600** [comment]
@jellegerbrandy I never see something that tells me a tx is in progress. I only see a fleeting msg that tells me that a tx has been initiated.  It disappears and then I don't know what is happening.

**Comment by tibetsprague** [comment]
I agree, I would like to bring back this feature at some point
