### ISSUE TITLE
Footer should not be clipped and should be able to be closed

### ISSUE THREAD

**Issue by dkent600** [daostack/alchemy#771]
The footer that says "There will be BUGS!" is clipped at the bottom of the screen.  It shouldn't be clipped.  Further, it shows an X that implies that I can close it, but clicking on the X does not close it.  It should.

**Comment by dkent600** [comment]
This may relate to that the layout is not accounting for the existence of a horizontal scroll bar, which BTW probably shouldn't exist there when there is no need to scroll horizontally.

**Comment by dkent600** [comment]
The vertical scrollbar is needed, but oddly shows no scroll button, though it should.

**Comment by jellegerbrandy** [comment]
not relevant anymore I thikn
