### ISSUE TITLE
Embed Uniswap (GEN) prompt into Alchemy interface when trying to stake without GEN

### ISSUE THREAD

**Issue by papa-raw** [daostack/alchemy#774]
It would be great if Uniswap was embedded directly into Alchemy if a user is trying to stake but doesn't have GEN tokens:

https://uniswap.io/

An alternative would be KyberSwap (once integrated) or perhaps some app on top of the DutchX protocol:

https://github.com/KyberNetwork/KyberSwap

**Comment by jellegerbrandy** [comment]
@A-Zak

**Comment by jellegerbrandy** [comment]
We have the "buy Gen" link in the meny on the left.
