### ISSUE TITLE
DAO avatar is not identified by name in interface

### ISSUE THREAD

**Issue by papa-raw** [daostack/alchemy#776]
This address: https://alchemy.daostack.io/profile/0xbe1a98d3452f6da6e0984589e545d4fc25af7526?daoAvatarAddress=0x294f999356ed03347c7a23bcbcf8d33fa41dc830 should be titled "dOrg" as it is the avatar of the dOrg DAO.

However, when asking for Rep in the Genesis Alpha, the address has no designation.

**Comment by tibetsprague** [comment]
closing this one in favor of this slightly nicer description: https://github.com/daostack/alchemy/issues/1199
