### ISSUE TITLE
How to convert threshold fields in dutchx generic proposals to WEI

### ISSUE THREAD

**Issue by tibetsprague** [daostack/alchemy#779]
Apparently we are supposed to multiple the USD values entered by the user by 10^18. How do we specify that this is supposed to happen in the JSON file that defines the form?

**Comment by jellegerbrandy** [comment]
Good question :-)

**Comment by jellegerbrandy** [comment]
How do you know we are "supposed to multiply the USD values"?

**Comment by tibetsprague** [comment]
According to @A-Zak

**Comment by jellegerbrandy** [comment]
Actually, this is a more general problem: any field where we input a token value will have it's multiplication factor to convert it "to wei".

**Comment by dkent600** [comment]
dxDAO UI maintains all WEI values as WEI.  It is very useful to be consistent about this.  For all UI display and input, it uses an Aurelia "valueConverter" to convert WEI values to ETH (or whatever), piped with other valueConverters to format the ETH result as desired.
