### ISSUE TITLE
Different color user icons

### ISSUE THREAD

**Issue by arsena21** [daostack/alchemy#780]
see image: http://prntscr.com/nxr7ux

It has been like this for a while... not sure if I'm the only one.

**Comment by tibetsprague** [comment]
hi @arsena21 actually what is happening here is that you are looking at someone's else's profile :)

**Comment by tibetsprague** [comment]
although wait, actually if you are able to edit the profile then thats not true. this is very strange. how did you get into this state?

**Comment by arsena21** [comment]
No idea... When I started using Alchemy, my user icon was green. At some point, it changed colors to the red in the top nav: http://prntscr.com/o1xwhr

On Etherscan, it is also green: http://prntscr.com/o1xw7x

**Comment by tibetsprague** [comment]
and you are sure that you are still logged into MetaMask with this same user with the address 0xa15...

**Comment by arsena21** [comment]
Yes, I see both colours within the same account...

**Comment by arsena21** [comment]
![image](https://user-images.githubusercontent.com/2105072/59895919-4fd3b800-939b-11e9-9db0-cd9f091507a2.png)
