### ISSUE TITLE
Can't submit a proposal

### ISSUE THREAD

**Issue by arsena21** [daostack/alchemy#781]
I can't seem to be able to submit a proposal.. I've tried a number of times and reset Metamask without success:

https://www.loom.com/share/03f98b2f958045019e5dc370d55e882b

**Comment by A-Zak** [comment]
@Arsena21
Can you please add the logs from the console?
It might help us understand what’s going on there...

**Comment by arsena21** [comment]
Not sure if this is what you are looking for... Here is information in the log: http://prntscr.com/ny0vgw

Below is the text

Promise.then (async) |   |  
-- | -- | --
  | c | @ | bundle-dfcaf3c2.js:107
  | (anonymous) | @ | bundle-dfcaf3c2.js:107
  | r | @ | bundle-dfcaf3c2.js:107
  | (anonymous) | @ | bundle-dfcaf3c2.js:107
  | e._trySubscribe | @ | bundle-dfcaf3c2.js:16
  | e.subscribe | @ | bundle-dfcaf3c2.js:16
  | (anonymous) | @ | bundle-dfcaf3c2.js:41
  | (anonymous) | @ | bundle-dfcaf3c2.js:41
  | r | @ | bundle-dfcaf3c2.js:41
  | (anonymous) | @ | bundle-dfcaf3c2.js:41
  | (anonymous) | @ | bundle-dfcaf3c2.js:306
  | (anonymous) | @ | bundle-dfcaf3c2.js:41
  | (anonymous) | @ | bundle-dfcaf3c2.js:266
  | o | @ | bundle-dfcaf3c2.js:266
  | Promise.then (async) |   |  
  | c | @ | bundle-dfcaf3c2.js:266
  | (anonymous) | @ | bundle-dfcaf3c2.js:266
  | r | @ | bundle-dfcaf3c2.js:266
  | handleSubmit | @ | bundle-dfcaf3c2.js:266
  | n.executeSubmit | @ | bundle-dfcaf3c2.js:47
  | (anonymous) | @ | bundle-dfcaf3c2.js:47
  | Promise.then (async) |   |  
  | n.submitForm | @ | bundle-dfcaf3c2.js:47
  | n.handleSubmit | @ | bundle-dfcaf3c2.js:47
  | (anonymous) | @ | bundle-dfcaf3c2.js:128
  | d | @ | bundle-dfcaf3c2.js:128
  | (anonymous) | @ | bundle-dfcaf3c2.js:128
  | D | @ | bundle-dfcaf3c2.js:128
  | k | @ | bundle-dfcaf3c2.js:128
  | x | @ | bundle-dfcaf3c2.js:128
  | M | @ | bundle-dfcaf3c2.js:128
  | wn | @ | bundle-dfcaf3c2.js:128
  | Ls | @ | bundle-dfcaf3c2.js:128
  | Ne | @ | bundle-dfcaf3c2.js:128
  | kn | @ | bundle-dfcaf3c2.js:128
  | (anonymous) | @ | bundle-dfcaf3c2.js:128
  | t.unstable_runWithPriority | @ | bundle-dfcaf3c2.js:142
  | Vs | @ | bundle-dfcaf3c2.js:128
  | En | @ | bundle-dfcaf3c2.js:128
  | r | @ | bundle-dfcaf3c2.js:77

**Comment by migbusiness** [comment]
Have the same issue:
`<div style="position: relative; padding-bottom: 62.5%; height: 0;"><iframe src="https://www.loom.com/embed/82189f328be746a0ab854a16c5276285" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen style="position: absolute; top: 0; left: 0; width: 100%; height: 100%;"></iframe></div>`

**Comment by arsena21** [comment]
I tried again this morning... error showed up a bit differently:

![image](https://user-images.githubusercontent.com/2105072/59045435-e9945480-8834-11e9-9260-591ab4d0a128.png)

**Comment by tibetsprague** [comment]
@arsena21 @migbusiness thank you for the report, this should be fixed now! please let us know if it is working for you again.
