### ISSUE TITLE
schemeregistrar edit proposal should fill in the existing values

### ISSUE THREAD

**Issue by jellegerbrandy** [daostack/alchemy#784]
On the form, if you select an existing proposal to edit, we should fil in the form with the current values for the paramsHash and (especially) the permissions.

**Comment by jellegerbrandy** [comment]
this is important, because it needs to be clear to the user that the proposal will remove the permissions that are not checked...

**Comment by dkent600** [comment]
If adding a known new scheme, should also provide suggested "default" values.

**Comment by A-Zak** [comment]
on tp:
https://daostack.tpondemand.com/entity/1071-schemeregistrar-edit-proposal-should-fill-in
