### ISSUE TITLE
should show GEN balance also (especially!) if it is zero

### ISSUE THREAD

**Issue by jellegerbrandy** [daostack/alchemy#799]
now, if a DAO has no GEN, we do not show it: 

![image](https://user-images.githubusercontent.com/1306173/59331390-23150600-8cf4-11e9-83d4-0121131e464c.png)

However, it is quite important for stakers to know that the DAO does not have any GEN (because it means they will not get the payout you may expect)

**Comment by leviadam** [comment]
Already implemented.
