### ISSUE TITLE
Long tokens name are out of the dao square boarder.

### ISSUE THREAD

**Issue by orenyodfat** [daostack/alchemy#8]
![Uploading Screen Shot 2018-03-04 at 16.18.38.png…]()

**Comment by dev-matan-tsuberi** [comment]
image was not uploaded

**Comment by tibetsprague** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Long names break the DAO UI](https://trello.com/c/xlJ1iTil/129-long-names-break-the-dao-ui)

**Comment by jellegerbrandy** [comment]
obsolete
