### ISSUE TITLE
show avatar's erc20 tokens balance  (if it is >0)

### ISSUE THREAD

**Issue by orenyodfat** [daostack/alchemy#809]
currently alchemy maintain hard coded (white list) list of token to show balance.
so the process of adding new erc20 token to the list is a bit "heavy" .
how about automate that ?
 
I guess that services like etherscan provides an api to get all erc20  tokens on a specific address .

**Comment by jellegerbrandy** [comment]
I do like this idea, but it adds a new dependeny on etherscan, which is something we should consider well.

If we go the etherscan way, we could also get the erc20 token **balances** there.
