### ISSUE TITLE
button text should be the same size

### ISSUE THREAD

**Issue by dkent600** [daostack/alchemy#817]
![image](https://user-images.githubusercontent.com/1821666/59788628-22531580-929a-11e9-9664-8d6d653cceed.png)

**Comment by jellegerbrandy** [comment]
unrelated but still: what does "xxx GEN pass to stay boosted" even mean?  If it is alreadyb oosted, why would one need to add GEN?

**Comment by dkent600** [comment]
@jellegerbrandy   

> what does "xxx GEN pass to stay boosted" even mean? If it is alreadyb oosted, why would one need to add GEN?

I have wondered about this too.  I'm not sure, my guess is that the proposal is actually pre-boosted, and because of other activity is unstable and threatening to fall back to queued.  If thi is true then the msg could definitely be improved.

**Comment by tibetsprague** [comment]
@jellegerbrandy @dkent600 if the boosting threshold changes then you might need to add GEN to keep it in the pre-boosted section, otherwise it will drop down to regular again.

**Comment by jellegerbrandy** [comment]
follow up in target process: https://daostack.tpondemand.com/RestUI/Board.aspx#page=board/4789434231796866533&appConfig=eyJhY2lkIjoiMEFGRDcyNjIyOTgzRjFFMkMwRjIwMDBCNzA0QjRGMzQifQ==&boardPopup=bug/1133/silent
