### ISSUE TITLE
wrong proposal's voting percentage view

### ISSUE THREAD

**Issue by jellegerbrandy** [daostack/alchemy#823]
they should have been automatically accepted

![image](https://user-images.githubusercontent.com/1306173/59873317-63375100-93a4-11e9-9700-c40672f9a79d.png)

https://alchemy.daostack.io/dao/0x33658686cbefe289b55814d0b3f3d45de6c50fd9/proposals/0x0d4b874488383bcbf71aa714b8fe6a26667d00f3cc0af7d20e5af4cbaa56992e

I suspect tha t the state actually did change, but  Alchemy is not showing the propsoals in the right place...

**Comment by orenyodfat** [comment]
One need to calculate voting percentages according to reputation total supply when the proposal is created
use proposal.totalRepWhenCreated
see
daostack/subgraph#266

**Comment by tibetsprague** [comment]
depends on https://github.com/daostack/client/pull/261

**Comment by leviadam** [comment]
Looks like [daostack/client#261](https://github.com/daostack/client/pull/261) is merged @tibetsprague

**Comment by jellegerbrandy** [comment]
fixed by #873
