### ISSUE TITLE
Redemption copy error (?)

### ISSUE THREAD

**Issue by arsena21** [daostack/alchemy#830]
On the redemptions page, when a proposal does not pass (such as the one below):
http://prntscr.com/o5onmk

It shows you some false information: http://prntscr.com/o5ool8

**Comment by arsena21** [comment]
Another example:

![image](https://user-images.githubusercontent.com/2105072/60029045-3e1d3980-9655-11e9-8571-6ea91f6aef43.png)

**Comment by jellegerbrandy** [comment]
Many thanks for opening an issue, @arsena21 

Indeed, it's a bug, we're on it (but we have a huge backlog, so it may take some time :-))

**Comment by jellegerbrandy** [comment]
this is fixed in https://github.com/daostack/subgraph/issues/263, the fix will bubble up in the next days
