### ISSUE TITLE
User Profile Not Updating

### ISSUE THREAD

**Issue by Moshiach770** [daostack/alchemy#831]
In Alchemy - Profile...

After clicking save (and successfully signing with Metamask of course), the input form where I entered my information is still in Input state, instead of transitioning to a read only element displaying ythe entered text.

The same is true for the Name input element.

**Comment by jellegerbrandy** [comment]
Thanks for opening an issue!

What is your account (your ethereum address that you are using?). And on reload, had it saved your info? Did you try a second time?

**Comment by tibetsprague** [comment]
@Moshiach770 this is actually how the current UI works, it is always in "edit" state when you are looking at your own data. I agree its not the best UI, at least we should make it more clear that your data has been saved

**Comment by Moshiach770** [comment]
Thanks for the feedback. The application is amazing and I think this is an
easy change that with big payout in terms of UX.
