### ISSUE TITLE
MaxListenersExceededWarning: opening to many web3 listeners

### ISSUE THREAD

**Issue by jellegerbrandy** [daostack/alchemy#834]
visiting a long history or reputation holders page will give, in the console, a MaxListenersExceededWarning . 

![image](https://user-images.githubusercontent.com/1306173/60115919-4a011c80-9777-11e9-9b0f-aad3788447f8.png)

this is (in all probability) because we open a listener for each user balance

**Comment by jellegerbrandy** [comment]
Not sure what the correct solution is here. Here are some approaches:

* do not show the balances at all 
* show the balances, but just query for them, not subscribe to changes
* do not get the balances fromt he blockchain, but from some provider (etherscan, like)

**Comment by A-Zak** [comment]
@jellegerbrandy This is also happening on the queue page where if we have a lot of proposals showing at the same time...

**Comment by A-Zak** [comment]
Which balances are we listening to on the history page / on the proposal queue?

**Comment by jellegerbrandy** [comment]
ok, it is none of the things I thought. 

The problem is not balances, it is contract instances. A web3 thing. Something to fix in the client. 

I'll just fix it instead of guessing in github comments :-)
