### ISSUE TITLE
remove .scss.d.ts files from version control, as they are generated by webpack

### ISSUE THREAD

**Issue by jellegerbrandy** [daostack/alchemy#838]

**Comment by leviadam** [comment]
Is there a reference that this is indeed the common practice?
I also don't see webpack is generating them. If I delete one of them and then do `npm run build` I get an error.

**Comment by jellegerbrandy** [comment]
the error is because of a bug: https://github.com/Jimdo/typings-for-css-modules-loader/issues/33
This workaroudn seems to work, cf. #923
