### ISSUE TITLE
Wrong network should show feedback to the user

### ISSUE THREAD

**Issue by dkent600** [daostack/alchemy#844]
STEPS:

1) Browse in Chrome to:  https://daostack-alchemy-staging.herokuapp.com/

2) click the "Please log in!" button
3) do the Metamask thing (login and connect) to Rinkeby

EXPECT:
I should be logged into Alchemy

RESULT:
 "Please log in!" button is still visible, but unresponsive.  Chrome output:  

> Uncaught (in promise) Error: Please connect to "rinkeby"
    at Object.<anonymous> (app.bundle-84142221.js:23)
    at Generator.next (<anonymous>)
    at o (app.bundle-84142221.js:23)

even though I am connected to rinkeby.

**Comment by dkent600** [comment]
I suspect the reason for this is that `arc.checkMetaMask` does not allow the use of rinkeby unless the "NODE_ENV" is staging.

**Comment by jellegerbrandy** [comment]
follow up here: https://daostack.tpondemand.com/RestUI/Board.aspx#page=board/4789434231796866533&appConfig=eyJhY2lkIjoiMEFGRDcyNjIyOTgzRjFFMkMwRjIwMDBCNzA0QjRGMzQifQ==&boardPopup=bug/1175/silent
