### ISSUE TITLE
redemption error

### ISSUE THREAD

**Issue by arsena21** [daostack/alchemy#848]
Looks like I can't redeem post the most recent update.

Here is error:

![image](https://user-images.githubusercontent.com/2105072/60231358-d54ce180-984d-11e9-803d-3658c61f0b9a.png)

**Comment by jellegerbrandy** [comment]
thanks @arsena21 , we'v efinally found the cause of this bug :-)
Rolling out a solution in next day.

**Comment by jellegerbrandy** [comment]
cf also #880
