### ISSUE TITLE
dxDAO function call is wrong

### ISSUE THREAD

**Issue by jellegerbrandy** [daostack/alchemy#863]
reports Anxo: 
"
I couldn’t change the price oracle. I did a bit of debugging in the tx and it seams it’s not calling to the right method. It calls "0xf625ee28" but the correct one should be "0x403fbf54" (initiateEthUsdOracleUpdate(address _ethUSDOracle).
"

**Comment by A-Zak** [comment]
@anxolin @denisgranha

**Comment by jellegerbrandy** [comment]
I can not reproduce tis, @anxolin - I've just tried it out and it does create a proposal for 0x403fbf54, as expected. Where did you see this? Can you point me to a transaction on etherscan?

**Comment by jellegerbrandy** [comment]
@anxolin if you are referring to your test proposal [here](https://daostack-alchemy-staging.herokuapp.com/dao/0x1eb3bcae24d42fde2f90e91d26313ac3946c4764/proposal/0xb407e225ade788b286b63136a3be86a54fcda30c48df5d053439a9891f37456c): that does seem to have the correct calldata (at least in our  [index](https://rinkeby.subgraph.daostack.io/subgraphs/name/v23/graphql?query=%7B%0A%20proposals%20(where%3A%20%7B%20id%3A%20%220xb407e225ade788b286b63136a3be86a54fcda30c48df5d053439a9891f37456c%22%20%7D)%20%7Bid%20%0A%0AgenericScheme%20%7B%20%0A%0AcallData%0A%7D%0A%7D%0A%7D)
