### ISSUE TITLE
Beneficiary reward redemption for failed proposal

### ISSUE THREAD

**Issue by stratisdaostack** [daostack/alchemy#866]
In my redemptions page, I see the option to redeem a beneficiary reward for a proposal that I posted that failed. When I click on the "Redeem for beneficiary" button I get the "Reward: transaction failed" error message.

<img width="445" alt="Screenshot 2019-07-08 at 09 34 06" src="https://user-images.githubusercontent.com/41568024/60790262-bada0880-a169-11e9-9e3d-67d6829d9769.png">
<img width="501" alt="Screenshot 2019-07-08 at 09 34 44" src="https://user-images.githubusercontent.com/41568024/60790263-bb729f00-a169-11e9-9eb3-c540c6377631.png">

**Comment by jellegerbrandy** [comment]
many thanks @stratisdaostack <3
