### ISSUE TITLE
Kyber DAO exp#2 is broken

### ISSUE THREAD

**Issue by littleboy0k** [daostack/alchemy#869]
Kyber DAO exp#2 doesn't show any proposals.

![image](https://user-images.githubusercontent.com/32856591/60819878-2cde3c00-a1c2-11e9-9937-6cc91b6855bc.png)

How to reproduce:
1.  Visit https://alchemy.daostack.io/dao/0x6bee9b81e434f7afce72a43a4016719315069539

**Comment by jellegerbrandy** [comment]
thank you very much @littleboy0k . This should be solved now
