### ISSUE TITLE
Using local testnet

### ISSUE THREAD

**Issue by macsilber** [daostack/alchemy#87]
When I deploy Alchemy to a local testnet (rather then Ganache) I get the following issue;
$ npm explore @daostack/arc.js -- npm start migrateContracts
  Deploying ControllerCreator...
  ... 0xba1723d484bf8cff0a39490e9e0a21c501779f5f8409b2c8c4263743f40c9e72
  ControllerCreator: 0x7fa1f52d08e82f91210bb16f45387f2e892fa57e
  Deploying DaoCreator...
  ... 0x9a5dc1b02c5f93b4698b908cf940dc9b73ebdce742140deffc057966fef63612
  DaoCreator: 0xc36b8324e6a366ad30c2476b30d9501ba8d3cb0a
  Deploying UController...
  ... undefined
Error encountered, bailing. Network state unknown. Review successful transactions manually.
Error: exceeds block gas limit

Any ideas?

(I think the documentation in Home.md referring to testnets is incomplete; !!! note
    See [Work with Arc Contracts](#work-with-arc-contracts) and [Deploy to Other Testnets](#deploy-to-other-testnets).

Thanks

**Comment by tibetsprague** [comment]
When you say you are running an local testnet do you mean with geth, or parity? Which testnet are you connecting to?

**Comment by macsilber** [comment]
running geth 
geth --networkid 4224 --mine --minerthreads 1 --datadir "~/Apps/chain/private" --nodiscover --rpc --rpcport "8545" --port "30303" --rpccorsdomain "*" --nat "any" --rpcapi eth,web3,personal,net --unlock 0 --password ~/Apps/chain/private/password.sec --ipcpath "~/Library/Ethereum/geth.ipc"

**Comment by dkent600** [comment]
@macsilber Try raising the gasLimit values that are used during migration.  They are stored in node_modules/@daostack/arc.js/gasLimits.js and node_modules/@daostack/arc.js/truffle.js.

**Comment by jellegerbrandy** [comment]
not relevant anymore
