### ISSUE TITLE
Unable to redeem automatic early voter's reward from own proposal

### ISSUE THREAD

**Issue by stratisdaostack** [daostack/alchemy#880]
When I click redeem I get "reward: transaction failed" error

Proposal url: https://alchemy.daostack.io/dao/0x294f999356ed03347c7a23bcbcf8d33fa41dc830/proposal/0x5661364c93105a47acf629f7c8e03a47725c257bd86439613c40dd003ba5abc3

My address:
0x6ac0a885ed84f4a2d062c60fb7daaf504fc8c47f

Note: I may have already redeemed this in the past without noticing but it still shows up in my redemptions page

<img width="344" alt="Screenshot 2019-07-10 at 09 29 35" src="https://user-images.githubusercontent.com/41568024/60945871-6e233880-a2f5-11e9-9b23-e59de753f626.png">

**Comment by jellegerbrandy** [comment]
this is caused by a contract bug: https://github.com/daostack/arc/issues/643

shoudl be resolved early next week

thansk, @stratisdaostack !

**Comment by leviadam** [comment]
Is this fixed @jellegerbrandy ?

**Comment by jellegerbrandy** [comment]
no,  oren should deploy the new redeemer contract today - i think this is this issue here: https://github.com/daostack/migration/issues/159

**Comment by jellegerbrandy** [comment]
now waiting for a new subgraph to deploy so we can get the correct redeemer contract
https://github.com/daostack/subgraph/issues/290
