### ISSUE TITLE
proposal page does not showed correctly ...

### ISSUE THREAD

**Issue by orenyodfat** [daostack/alchemy#890]
might be due to long proposal name

https://alchemy.daostack.io/dao/0x70c36947837b43665ed5ea85c112aa0f72cf9fb3/proposal/0x795250f93f0d5748af78a1389f9fc99d4afa885d58af35abba1bd01f4cf7aa73

**Comment by orishim** [comment]
it gets even worse when you embed a large picture :/

https://alchemy.daostack.io/dao/0x294f999356ed03347c7a23bcbcf8d33fa41dc830/proposal/0xd5b8892891b7ed7ffc422abe62cfa86f14f97dba31a158514a7cf94e9cc3da0f

**Comment by brodeur** [comment]
This will fix the image related issue: https://github.com/daostack/alchemy/pull/933

 The fix that alex committed yesterday should address the top one.

**Comment by A-Zak** [comment]
lgtm
