### ISSUE TITLE
Proposal page is now left justifying on desktop

### ISSUE THREAD

**Issue by pat-daostack** [daostack/alchemy#893]
Something broke methinks

![Capture](https://user-images.githubusercontent.com/42677601/61063250-ed9d2e80-a3ff-11e9-98e9-f8f6d025011d.PNG)

**Comment by jellegerbrandy** [comment]
![image](https://user-images.githubusercontent.com/1306173/61200616-54616700-a6e2-11e9-859f-a10f5cc48b30.png)
