### ISSUE TITLE
Check for eth address validity before submitting.

### ISSUE THREAD

**Issue by orenyodfat** [daostack/alchemy#9]
Use this to validate 
https://web3js.readthedocs.io/en/1.0/web3-utils.html?highlight=isAddress#isaddress

**Comment by tibetsprague** [comment]
yup, already have this card: https://trello.com/c/oLQ1C6Wg

**Comment by tibetsprague** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Validation of create proposal form](https://trello.com/c/oLQ1C6Wg/73-validation-of-create-proposal-form)
