### ISSUE TITLE
Some proposals do not appear in History tab

### ISSUE THREAD

**Issue by orishim** [daostack/alchemy#901]
For example, [this proposal](https://alchemy.daostack.io/dao/0xbe1a98d3452f6da6e0984589e545d4fc25af7526/proposal/0xcc267fe8f0514dcca85f995465dffbf82574886937815bc8fe46899b1db78d45) titled "Pay the Lawyers" does not show up in our [History](https://alchemy.daostack.io/dao/0xbe1a98d3452f6da6e0984589e545d4fc25af7526/history/) tab.

**Comment by tibetsprague** [comment]
https://daostack.tpondemand.com/RestUI/Board.aspx#page=board/5209716961861964288&appConfig=eyJhY2lkIjoiQjgzMTMzNDczNzlCMUI5QUE0RUE1NUVEOUQyQzdFNkIifQ==&boardPopup=bug/1293/silent

**Comment by tibetsprague** [comment]
working on this

**Comment by jellegerbrandy** [comment]
@tibetsprague wrote in discord:

@jelle im confuse about the new history query, it does look broken to me. the old way was two queries that were combined: 
{where: { stage_in: [IProposalStage.ExpiredInQueue, IProposalStage.Executed] }
&
{where:  { stage: IProposalStage.Queued, expiresInQueueAt_lte: Math.floor(new Date().getTime() / 1000) }
now it's one query:
where: {
                    stage_in: [IProposalStage.ExpiredInQueue, IProposalStage.Executed, IProposalStage.Queued],
                    closingAt_lte: Math.floor(new Date().getTime() / 1000)
                  }
now if the closingTime is in the future it doesnt show the proposal even if its been executed
i guess the best solution is for the subgraph to change closingAt to be now when the proposal gets executed?

**Comment by jellegerbrandy** [comment]
So this in indeed true for proposals that are executed with an absolute majority (as in the issue)
