### ISSUE TITLE
`Transaction Failed` on vote for Scheme Registrar proposal

### ISSUE THREAD

**Issue by orishim** [daostack/alchemy#904]
When I try to vote FOR either of these proposals [[1](https://alchemy.daostack.io/dao/0xbe1a98d3452f6da6e0984589e545d4fc25af7526/proposal/0x84e855e489ac88923ec0d130656566109c79fa23b0f110e84a0e0c97f3a11255)][[2](https://alchemy.daostack.io/dao/0xbe1a98d3452f6da6e0984589e545d4fc25af7526/proposal/0x21cc40c5587fec1dd138391849be93fcb6decd647ecd54be9f60fe28a593489d)] in dOrg's Scheme Registrar, I receive a `Vote: Transaction Failed` error in Alchemy.

<img width="310" alt="Screen Shot 2019-07-13 at 7 31 02 PM" src="https://user-images.githubusercontent.com/10736693/61177497-e6fbec00-a5a4-11e9-8d9f-0b43461f837d.png">

<img width="561" alt="Screen Shot 2019-07-13 at 1 33 28 PM" src="https://user-images.githubusercontent.com/10736693/61177480-8d93bd00-a5a4-11e9-8ea3-4c41f817fec2.png">

Interestingly I do not get this error when voting AGAINST the proposals. I have tried restarting metamask, clearing the browser cache, etc.

**Comment by jellegerbrandy** [comment]
MM, that _is_ surprising.
What is the Eth address that you are voting with? (if you do not want to share that here, ping me on discord on @jelleg on telegram)
