### ISSUE TITLE
Proposal not boosted after 24 hours.

### ISSUE THREAD

**Issue by GraceRachmany** [daostack/alchemy#910]
I posted a proposal on noon Friday and it was voted up "Pending" within a few hours, but it has been pending for 2 days and now (Sunday, 8 pm) says 15 hours left Pending. 
https://alchemy.daostack.io/dao/0x294f999356ed03347c7a23bcbcf8d33fa41dc830/proposal/0x6cdb9af782fab8894ee15d9fad459200538715e894d3ad806d8ceb12cd6f1e99

My understanding if that if I have enough GEN then in 24 hours it is supposed to move from Pending to Boosted. 2 other proposals are now Boosted that were pending, but mine was not Boosted.

**Comment by jellegerbrandy** [comment]
Hi Grace, thanks for your report.  I'm not sure what went wrong here, if anything (the logic is quite complex, and perhaps your proposal was moved from "pending" to "regular" and back, which would have reset the pending time). In any case, the proposal is boosted now, so you're good :-)

**Comment by GraceRachmany** [comment]
Yay! thank you

On Mon, Jul 15, 2019 at
