### ISSUE TITLE
new tslint.json proposal

### ISSUE THREAD

**Issue by jellegerbrandy** [daostack/alchemy#915]
[I'll do this :-)]

**Comment by leviadam** [comment]
I have came across this article. Not sure how far they got already. What do you think?

“TSLint in 2019” by Palantir https://link.medium.com/DdDHi7odlY

**Comment by jellegerbrandy** [comment]
https://www.npmjs.com/package/@typescript-eslint/parser has over >1M dowloads, against tslint > 2.5M, so it looks like it is possible to use... let's try it out and see how it plays with react..

**Comment by leviadam** [comment]
Sounds good.

**Comment by leviadam** [comment]
@jellegerbrandy. Can we close this?
