### ISSUE TITLE
GEN hard coded in `PredictionBox.tsx`

### ISSUE THREAD

**Issue by macsilber** [daostack/alchemy#92]
Wanted to point out that it is hard coded in this spot as opposed to other places where it comes from the migration contract;

              <tr className={stakeDownClass} >
                <td className={failPrediction}>
                  { proposal.state == ProposalStates.PreBoosted
                    ? <button onClick={this.showModal.bind(this, 2)}>FAIL +</button>
                    : "FAIL"
                  }
                </td>
                <td>{proposal.stakesNo} GEN</td>

and here

          <input type="number" min="1" ref={(input) => { this.stakeInput = input; }} className={css.predictionAmount}/>
          <span className={css.genLabel}>GEN</span>
          <div className={css.clearfix}>
            <button className={css.cancelPrediction} onClick={this.closeModal.bind(this)}>
              <img src="/assets/images/Icon/Close-black.svg"/>
            </button>
            <button className={css.placePrediction} onClick={this.handleClickStake.bind(this, showStakeModal)}>Place stake</button>
          </div>

**Comment by jellegerbrandy** [comment]
not relevant anymore
