### ISSUE TITLE
missing permission value on SchemeRegistrar's proposal page

### ISSUE THREAD

**Issue by orenyodfat** [daostack/alchemy#928]
https://alchemy.daostack.io/dao/0xbe1a98d3452f6da6e0984589e545d4fc25af7526/proposal/0xfdd3136c8cbc6f259b8f762e17a3a2472ff76dd0d64c57cb2df2c3a620114232

<img width="495" alt="Screen Shot 2019-07-17 at 9 09 06" src="https://user-images.githubusercontent.com/5994398/61351190-a1744300-a872-11e9-849f-2cd9a3867e09.png">

**Comment by jellegerbrandy** [comment]
follow up here: https://daostack.tpondemand.com/RestUI/Board.aspx#page=board/4789434231796866533&appConfig=eyJhY2lkIjoiMEFGRDcyNjIyOTgzRjFFMkMwRjIwMDBCNzA0QjRGMzQifQ==&boardPopup=bug/1307/silent
