### ISSUE TITLE
form url validation allows invaid url

### ISSUE THREAD

**Issue by dkent600** [daostack/alchemy#936]
The contributionreward create proposal form allows the following urls:  

>http://google,com
> http://toot/tank^com
> http://toot*tank.com
> \> http://toot/tank.com  (with the gt and space

Note I haven't tested all possibilities.

Recommend that:

1) we define the regex string for URLs in one single place rather than duplicating everywhere
2) we find a regex that really works

**Comment by jellegerbrandy** [comment]
yes and yes.

We could use the one from the accepted answer here: https://stackoverflow.com/questions/161738/what-is-the-best-regular-expression-to-check-if-a-string-is-a-valid-url

**Comment by jellegerbrandy** [comment]
Fixed, right?

**Comment by dkent600** [comment]
yes, fixed.
