### ISSUE TITLE
Changing user account in metamask doesn't change account in Alchemy

### ISSUE THREAD

**Issue by dkent600** [daostack/alchemy#954]
Changing the user account in metamask doesn't change the account used in Alchemy.  One can change the account in MM but it doesn't cause Alchemy to restart and doesn't affect what is stored in localStorage.  Alchemy continues to use the originally-stored address.

**Comment by tibetsprague** [comment]
Did this just break? It has been working

**Comment by dkent600** [comment]
All I can say is that it happened to me repeatedly until I manually removed the localStorage setting.

**Comment by dkent600** [comment]
The essence of this problem is that:

1) When Privacy Mode is enabled in MM, and before asking for permission to access the account, we have no idea what is the currently-selected account in MM.  We just use the cached account, if available.
2) We don't ask for permission to access the account until we absolutely need to in order to send a tx.

Once we ask for permission to access the account, then the app does a hard reboot, and the app and MM are then in sync.

**Comment by dkent600** [comment]
So this is known and accepted behavior if we want readonly mode with a cached account.
