### ISSUE TITLE
dxDAO Generic Scheme is being called "Generic Scheme" instead of "DutchX"

### ISSUE THREAD

**Issue by dkent600** [daostack/alchemy#959]
The dxDAO Generic Scheme is being called "Generic Scheme" instead of "DutchX"

**Comment by dkent600** [comment]
![image](https://user-images.githubusercontent.com/1821666/61695069-d06e3700-ad00-11e9-89b4-9997383434a3.png)

**Comment by jellegerbrandy** [comment]
where do you see this? (I see no "generic scheme" in your screen shot)

**Comment by dkent600** [comment]
Sheesh sometimes I read things far too hastily.

**Comment by dkent600** [comment]
I swear I saw that though, and I saw and fixed the code that was causing the bug.
