### ISSUE TITLE
Unable to see passed proposals in History tab.

### ISSUE THREAD

**Issue by dOrgJelli** [daostack/alchemy#960]
These proposals are not showing up in our DAO's history:
https://alchemy.daostack.io/dao/0xbe1a98d3452f6da6e0984589e545d4fc25af7526/proposal/0xf0faca8bb9c4276efee86b840a6f8b3c7430a3c571d86acf56b1d02098b0fa27

https://alchemy.daostack.io/dao/0xbe1a98d3452f6da6e0984589e545d4fc25af7526/proposal/0xd57da8197456c9cd75c92bf3fced0cfd52c7a7e9f0139f83ece6939712b805e1

**Comment by jellegerbrandy** [comment]
Thanks @dOrgJelli 
We are aware of the issue and should roll out the fix soon. 
As this duplicates https://github.com/daostack/alchemy/issues/901, I'm closing it.
