### ISSUE TITLE
Feature: tab order in new proposal popups

### ISSUE THREAD

**Issue by dkent600** [daostack/alchemy#964]
Would be nice if the tab order in new proposal popups were such that tabbing from "Title" goes straight to "Description" rather than detouring in netherland as it does.

**Comment by tibetsprague** [comment]
yeah this is a bug with the Markdown editor we are using, I filed an issue with them, they know about it and are working on it

**Comment by dkent600** [comment]
@tibetsprague Any status on the issue you filed?

**Comment by tibetsprague** [comment]
no, I pinged them

**Comment by tibetsprague** [comment]
hah, apparently he did a release with the fix today!
