### ISSUE TITLE
ProposalHistory header and columns are not aligned

### ISSUE THREAD

**Issue by dkent600** [daostack/alchemy#969]
The ProposalHistory header columns are not aligned with the row columns

![image](https://user-images.githubusercontent.com/1821666/61832816-66f54200-ae40-11e9-8fc2-dcc45352d6de.png)

**Comment by jellegerbrandy** [comment]
follow up in target process: https://daostack.tpondemand.com/RestUI/Board.aspx#page=board/4789434231796866533&appConfig=eyJhY2lkIjoiMEFGRDcyNjIyOTgzRjFFMkMwRjIwMDBCNzA0QjRGMzQifQ==&boardPopup=bug/1515/silent
