### ISSUE TITLE
Non-unique keys  keys in RedeemProposal popup

### ISSUE THREAD

**Issue by dkent600** [daostack/alchemy#970]
When the RedeemProposal modal appears, a huge error message appears that starts with this:

> Warning: Encountered two children with the same key, `0xd12f250353e18a58898bbfc325848b5b0af2cbd016e4ba615dd6f0e93006fc12`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.

(I saw this on my local machine running against ganache)

**Comment by jellegerbrandy** [comment]
follow up here: https://daostack.tpondemand.com/RestUI/Board.aspx#page=board/4789434231796866533&appConfig=eyJhY2lkIjoiMEFGRDcyNjIyOTgzRjFFMkMwRjIwMDBCNzA0QjRGMzQifQ==&boardPopup=bug/1510/silent
