### ISSUE TITLE
Reputation Reward Details Don't Show # of REP

### ISSUE THREAD

**Issue by dOrgJelli** [daostack/alchemy#979]
When you hover over a reputation reward, it only shows the total number of REP in the DAO, and doesn't show the number of reputation tokens that're being minted.

An example can be seen here: https://alchemy.daostack.io/dao/0xbe1a98d3452f6da6e0984589e545d4fc25af7526/proposal/0x6b8447c594499abd73941a5c6d5810f72765486cbb5f995842ae5c9c88e107ce

**Comment by jellegerbrandy** [comment]
issue in target process: https://daostack.tpondemand.com/RestUI/Board.aspx#page=board/4789434231796866533&appConfig=eyJhY2lkIjoiMEFGRDcyNjIyOTgzRjFFMkMwRjIwMDBCNzA0QjRGMzQifQ==&boardPopup=bug/1496/silent
