### ISSUE TITLE
tests fail on presence of disclaimer prompt

### ISSUE THREAD

**Issue by dkent600** [daostack/alchemy#985]
When run locally, not headless, several tests fail due to the presence of disclaimer prompt.  Would be nice to close this popup prior to every test (except a test of the disclosure popup itself).  Ideally is a single piece of code that works prior to every test.

**Comment by jellegerbrandy** [comment]
follow up in target process: https://daostack.tpondemand.com/RestUI/Board.aspx#page=board/4789434231796866533&appConfig=eyJhY2lkIjoiMEFGRDcyNjIyOTgzRjFFMkMwRjIwMDBCNzA0QjRGMzQifQ==&boardPopup=bug/1500/silent
