### ISSUE TITLE
two children with the same key with multiple unsupported schemes

### ISSUE THREAD

**Issue by dkent600** [daostack/alchemy#992]
In rinkeby, Gustatory Engineering DAO with two unsupported schemes (I suspect that is the repro case here), when browsing to the All Schemes page, I see in the console:

```
Warning: Encountered two children with the same key, `0x72939947e7a1c4ac94bb840e3304b322237ad1a8`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.
```

**Comment by jellegerbrandy** [comment]
follow up here: https://daostack.tpondemand.com/RestUI/Board.aspx#page=board/4789434231796866533&appConfig=eyJhY2lkIjoiMEFGRDcyNjIyOTgzRjFFMkMwRjIwMDBCNzA0QjRGMzQifQ==&boardPopup=bug/1495/silent
