### ISSUE TITLE
Text is duplicated ( and not aligned properly?)

### ISSUE THREAD

**Issue by peculiarity** [daostack/alchemy#995]
OS: Linux
Browser: Chrome 74.0.37..

When I visited exactly this [proposal](https://alchemy.daostack.io/dao/0x519b70055af55a007110b4ff99b0ea33071c720a/proposal/0x9c5e2ea7878c3e721f431b77d7e5eda45baed3164a2da0e660d21deb5cbb95c3) I have noticed the following thing:

![image](https://user-images.githubusercontent.com/23715025/62276106-9a892b00-b443-11e9-9f96-1732dd4b7d12.png)

I've noticed that this text is under the proposal description so I would assume that those 2 rows shouldn't be there at all. If one of them is supposed to be there then I would assume it's not aligned correctly.

**Comment by A-Zak** [comment]
should be fixed :)
