### ISSUE TITLE
Text is placed where it shouldn't and layout is broken

### ISSUE THREAD

**Issue by peculiarity** [daostack/alchemy#997]
OS: Linux
Chrome: 74.0.37...

Visited [`contribution rewards`](https://alchemy.daostack.io/dao/0x519b70055af55a007110b4ff99b0ea33071c720a/scheme/0x28d5c82734905e9708c4d1332ba6d4753ac04836a4fcf4c5451c2dc5d5d76237/proposals) section.

Scrolled down to the pending proposals.
One of the proposals was half visible, half hidden behind the header of the section.
Once I hovered with mouse the proposal appeared  completely ( I guess it's intentional so you see all the information but it feels weird, like something is broken )
Hovered on the  three vertical dots to see the options for voting.

![image](https://user-images.githubusercontent.com/23715025/62277577-b9d58780-b446-11e9-9871-ca9b67331cf1.png)

As displayed in the imaged above the text - `This member is not found` is both visible on the proposal itself and the voting options menu.

**Comment by jellegerbrandy** [comment]
I cannot reproduce this - I assume this was fixed
