### ISSUE TITLE
Proposal box is floating on scrolll

### ISSUE THREAD

**Issue by peculiarity** [daostack/alchemy#998]
OS: Linux
Browser: Chrome 74.0.37..

Visited [`contribution rewards`](https://alchemy.daostack.io/dao/0x519b70055af55a007110b4ff99b0ea33071c720a/scheme/0x28d5c82734905e9708c4d1332ba6d4753ac04836a4fcf4c5451c2dc5d5d76237/proposals) section.

Hover over any of the proposals.
It gets selected.
Start two-fingers scrolling 

![image](https://user-images.githubusercontent.com/23715025/62277815-37999300-b447-11e9-879c-13ce4a47049c.png)

As seen in the screenshot above the selected proposal is floating  up/down above the normal flow. ( the bottom is visible at the top of the screen in this example , below `contribution reward` title ).

**Expected behavior**
If the proposal is getting "popped" to the user I would assume that once mouse is not over the given proposal it get's back into the normal flow and hides behind the header on scrolling.

**Comment by tibetsprague** [comment]
this is fixed for me @peculiarity , let me know if it looks fixed to you!
